### ISSUE TITLE
"Semi-Brick" with the Network Package.

### ISSUE THREAD

**Issue by CosmoXDD** [exelix11/SysDVR#1]
A few hours ago, I installed the **"Network"** package and it happened to restart my console and did not want to boot any more, but I managed to solve this problem by reinstalling **Atmosphere 0.9.4**, Try to check if the package works. But if it's any use, pass the package to the `Atmosphere/titles` folder using FTP and my firmware version is 8.0.0.

**GOOD LUCK WITH THIS AWESOME PROJECT!.**

**Comment by suchmememanyskill** [comment]
One thing i'd like to note: did you try deleting the streaming sysmodule from the atmosphere/titles folder? Also, be more descriptive, what happens at boot, provide error logs so exelix can actually pinpoint the issue. Did you have any other sysmodules installed at the time? That kind of stuff

**Comment by CosmoXDD** [comment]
(Sorry for my bad level of English but I am using the Google Translator.)


1- The start: When the Atmosphere starts, the Nintendo Switch logo comes out and remains static, I was waiting for 10 minutes and it never started until it forced off.

2- The streaming module: As far as I know xD, I have not deleted any sysmodule, but the module that I deleted is that of the USB package, because then I wanted to install the Network but I have not deleted any more packages.

3- I do not know exactly what modules I have because I use "[RetroReloaded](https://github.com/RetroGamer74/RR_RetroReloaded)" which brings the following modules (I DON'T KNOW THE NAME BUT I LEAVE THE "ID" THROUGH I SAY THE MODULES:
 
`010000000000000D`, `01000000000032`, `0100000000000034`, `0100000000000352`, `0100000000001000.RR`, `0100000000001000.SB`, `420000000000000E`, `4200000000000010`.

GOOD LUCK!

**Comment by exelix11** [comment]
Not sure about retroloader but it looks like a memory issue. Some sysmodules are particularly memory heavy and don't work fine alongside others (eg sysftpd), try using vanilla atmosphere when launching this.
Also try using the usb version with your setup as it uses less memory.

**Comment by CosmoXDD** [comment]
I'm going to try the USB module, but I wonder what it will be like to see what happened through FTP.

**Comment by CosmoXDD** [comment]
I just tried to install the USB package and it WORKS!. As you said for sure it was some conflict with memory. THANK YOU.
GOOD LUCK WITH THIS INCREDIBLE PROJECT!

**Comment by ELY3M** [comment]
I have same issue with network too.  I just have to pull out my sd card and manually delete one folder.  USB is only one that is working for me.

**Comment by exelix11** [comment]
As said both here and in the readme, you have too many sysmodules or one in particular that uses too much memory. Nothing i can do about it.
