### ISSUE TITLE
[Help] help to confirm the drive type for "WIFI(TCP) mode" and "USB mode"

### ISSUE THREAD

**Issue by songyuyx** [exelix11/SysDVR#100]
**Where do you get stuck ?**
No stuck, the ticket is for information confirm

**What's the error message you get ?**
No error, the ticket is for information confirm

**Setup information**
 - PC OS: [Windows 10 x64]
 - Console firmware [5.0.0]
 - Custom firmware name and version [TX  10.0.2]
 - SysDVR version [5.0.0]

**Additional context**
Thanks for good software.  I have runned it success in both of "WIFI(TCP) mode” and ”USB mode”. 
What the drive I use for ”WIFI(TCP) mode” is LIBUSB,  but WINUSB for ”USB mode“。
I would like to kown if have a drive type, which could support both of both of "WIFI(TCP) mode” and ”USB mode”. so that It dont need to change the drive type when connection mode changes

**Comment by exelix11** [comment]
None of the wifi modes need a driver, they use standard network protocols.
You just need to install winusb once for the usb mode. If you don't use usb you don't need any driver.

**Comment by exelix11** [comment]
I think i answered the question, if there's anything else reply here.
