### ISSUE TITLE
[Bug] macOS "Unable to load shared library 'SDL2'

### ISSUE THREAD

**Issue by kirankunigiri** [exelix11/SysDVR#101]
I'm on macOS Mojave and followed the guide. I installed .net 5.0, ffmpeg and SDL2 (although it did say that SDL2 was already installed since it's a prerequisite installed with ffmpeg). I then ran the basic command to test it. It crashes with an error about SDL2. I tried both updating it and uninstalling and reinstalling it. None of these worked. Trying it with the bridge command and IP address also didn't work. Any help would be appreciated, thanks!

On another note, after opening the SysDVR settings app my Switch gets stuck on "Connecting to SysDVR. If you just turned on your console this may take up to 20 seconds. If you can't get past this screen SysDVR is probably not running, make sure your setup is incorrect." I tried recopying the files to the right folders again and this shows up again. Not sure what to do.

Below is the error from the macOS terminal after running the basic command:

```
Basic usage:
Simply launching this exectuable will show this message and launch the video player via USB.
Use 'SysDVR-Client usb' to stream directly, add '--no-audio' or '--no-video' to disable one of the streams
To stream in TCP Bridge mode launch 'SysDVR-Client bridge <switch ip address>'
There are more advanced options, you can see them with 'SysDVR-Client --help'
Press enter to continue.


Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 1): image not found
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.Main(String[] args)
Abort trap: 6
```

**Comment by exelix11** [comment]
> On another note, after opening the SysDVR settings app my Switch gets stuck on "Connecting to SysDVR. If you just turned on your console this may take up to 20 seconds. If you can't get past this screen SysDVR is probably not running, make sure your setup is incorrect." I tried recopying the files to the right folders again and this shows up again. Not sure what to do.

After copying the sysmodule you should reboot the console. In case you don't use atmosphere you must rename the folders in the release zip first.

> I'm on macOS Mojave and followed the guide. I installed .net 5.0, ffmpeg and SDL2 (although it did say that SDL2 was already installed since it's a prerequisite installed with ffmpeg). I then ran the basic command to test it. It crashes with an error about SDL2. I tried both updating it and uninstalling and reinstalling it.

Are you sure you installed SDL2 and not just SDL ? Unfortunately i don't have a mac to test so i can only offer suggestions.
First try downloading the dmg from SDL's website](https://www.libsdl.org/download-2.0.php)
If it still doesn't work you could try setting [loader flags](https://apple.stackexchange.com/questions/378007/how-to-find-which-shared-library-is-missing) to check what fails or manually searching for SDL2.dylib in your filesystem and adding it to DYLD_LIBRARY_PATH.

**Comment by kirankunigiri** [comment]
I'm 100% sure I have SDL2 installed. I just tried installing it using the DMG as well but no luck. I'll try to look for why the library isn't being found. My only guesses are that it's in a different location than expected or it's been named differently for some reason.

For the Switch issue, I did after rebooting and I do use Atmosphere. Also, if I press the home button on the settings loading screen it just crashes the console. I'm going to try deleting it and placing the files one more time, but I was sure I pasted them in the right locations already. Let me know if you have any other ideas for what this issue could be.

**Comment by exelix11** [comment]
> For the Switch issue, I did after rebooting and I do use Atmosphere. Also, if I press the home button on the settings loading screen it just crashes the console.

No clue, maybe you have something that manages sysmodules that disables it or changed atmosphere settings ? 

>  I'm going to try deleting it and placing the files one more time, but I was sure I pasted them in the right locations already. Let me know if you have any other ideas for what this issue could be.

You're supposed to extract everything in the zip to the root of your SD and everything should be at its place, no manual file copy is needed. Maybe you need to update atmosphere ?

**Comment by kirankunigiri** [comment]
Hey! Just wanted to say I ended up getting everything working, and it is AMAZING! Can't believe how good the quality is without needing a $100 capture card. It's simple and fast.

So here's how I fixed the issue for anyone else who comes along with the same problem. It's actually kind of dumb and simple. First off, on the Switch, either I copied some of the files wrong, or it somehow fixed itself after updating to the latest version of Atmosphere. I both recopied and updated and it started working perfectly after that.

Second, on macOS, the sdl2 error still shows up if you still run the test function by itself (dotnet SysDVR-Client.dll). I should have read it more carefully, but it does already say that running the SysDVR client without any IP address inputs will just launch the player, and since there is no built-in player for mac, that's probably why it crashes. Since I had the Switch version working this time, if I did the proper bridge command and then open it in MPV, it just works.
`dotnet SysDVR-Client.dll bridge <ip address> --rtsp`

Thanks for all the help @exelix11, really appreciate the fast replies and how well you've built this thing. I will now go enjoy SysDVR so I can finally start streaming games with my friends.

**Comment by exelix11** [comment]
The built-in player should work on mac, had people test before release. Idk which OSX version though.

**Comment by kirankunigiri** [comment]
I just realized, the sdl2 error pops up again if I omit the --rtsp tag. So I'm guessing the sdl2 error was just related to the built-in player not working for me.

**Comment by exelix11** [comment]
Yes that's the only component that uses sdl.

**Comment by kirankunigiri** [comment]
@exelix11 I finally found the fix! I manually copied the following files from the /usr/local/lib/ folder of my Mac and copied them to the root of the SysDVR-Client folder. The built-in player works now. (note for other Mac users: your dylib files may have an extra version numbers added at the end - make sure to rename them to the exact names below)
libavcodec.58.dylib
libavutil.56.dylib
libSDL2.dylib

**Comment by kirankunigiri** [comment]
One last question though - is it possible to increase the quality by allowing for increased latency? I would be OK with the latency being a few seconds longer if I can somehow get better FPS. The quality is good but its only around 30fps now while the Switch plays at 60.

**Comment by exelix11** [comment]
> 
> 
> @exelix11 I finally found the fix! I manually copied the following files from the /usr/local/lib/ folder of my Mac and copied them to the root of the SysDVR-Client folder. The built-in player works now. (note for other Mac users: your dylib files may have an extra version numbers added at the end - make sure to rename them to the exact names below)
> libavcodec.58.dylib
> libavutil.56.dylib
> libSDL2.dylib

That's the issue then, the version in the name. There's the same issue with libusb on linux so i ask to make a symlink when needed, you can probably do the same without copying the libs.



> 
> 
> One last question though - is it possible to increase the quality by allowing for increased latency? I would be OK with the latency being a few seconds longer if I can somehow get better FPS. The quality is good but its only around 30fps now while the Switch plays at 60.

Currently it's not possible, video encoding uses the stock configuration of the console, i don't know if it's possible to change it but that will probably cause reduced performances in games.

**Comment by cheft** [comment]
me too

**Comment by lotuspar** [comment]
if anyone still gets this error try running these commands (in the SysDVR working directory)

`
cp $(brew --prefix ffmpeg)/lib/libavcodec.dylib libavcodec.58.dylib
cp $(brew --prefix ffmpeg)/lib/libavutil.dylib libavutil.56.dylib
cp $(brew --prefix sdl2)/lib/libSDL2.dylib libSDL2.dylib
cp $(brew --prefix libusb)/lib/libusb-1.0.dylib libusb-1.0.dylib
`
