### ISSUE TITLE
[Bug] SysDVR Crash on 11.0

### ISSUE THREAD

**Issue by Mathaeuz** [exelix11/SysDVR#102]
**Describe the bug**
Atmosphere crashes shortly after booting up Switch's home screen. Crash reports mention SysDVR, and removing the related atmosphere content 'solves' the issue.

The new switch firmware introduces big changes, and the new Atmosphere pre-release is just out, so I expected most sysmodules to act up in some way. [The latest patch notes](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.16.0) also mention the necessity to rebuild code that depends on the `usb:ds` service with the latest libnx, so that could be of use.

**To Reproduce**
Simply fire up Atmosphere CFW from hekate. (no emuMMC)

**Expected behavior**
"Pls no crash. I want to strem more."

**Setup information**
 - n/a
 - Console firmware: 11.0.0
 - Custom firmware: Atmosphere 0.16.0-prerelease
 - SysDVR version: 5.0.1

**Additional context**
Crash Reports below.
[crash_reports.zip](https://github.com/exelix11/SysDVR/files/5639129/crash_reports.zip)

**Comment by exelix11** [comment]
Yeah it's most likely usb if you set it to default mode on boot, to clear the configuration delete the config/sysdvr folder from your sd card.
Network modss should work fine.
Will post an updated version in the next few days.

**Comment by Mathaeuz** [comment]
I just tried it out and it works. Thanks!

Off: This app has been so convenient it's convinced me to get a LAN adapter. Nice going.

**Comment by exelix11** [comment]
Shoud be fixed in [latest release](https://github.com/exelix11/SysDVR/releases/latest)
