### ISSUE TITLE
super smash bros ultimate doesnt work for streaming

### ISSUE THREAD

**Issue by Kurumin7-gif** [exelix11/SysDVR#103]
some games can be streamed, but it doesnt happen with super smash bros ultimate

**Comment by Flyken271** [comment]
The only games that can be streamed with SysDVR are those that are capable of recording, to check if a game can be streamed, go into the game and hold the screenshot button, if you see a notification regarding "Recording", then it can be streamed, if it does nothing and or take a screenshot, it cannot be streamed.

**Comment by exelix11** [comment]
What Flyken said.
I'm looking into ways to enable recording for all games but i can't guarantee i'll manage to do that so for the time being smash bros and other games that disable game recording are not supported.
