### ISSUE TITLE
How can I merge the video.h264 and audio.raw?

### ISSUE THREAD

**Issue by Conan179** [exelix11/SysDVR#104]
Hello, I have a question.

My switch are on 10.2.0 and i make a save to usb movie from Zelda bttw.
How can I merge the video.h264 and audio.raw?

Greetz

**Comment by Flyken271** [comment]
I'm not  entirely sure but I'm confident there are some muxing tools on windows, there are as well
 FFmpgeg CLI commands too.

**Comment by exelix11** [comment]
Yes you need ffmpeg. The command is along the lines of 
`ffmpeg -fflags +genpts -framerate 30 -i video.264 -f s16le -ar 48000 -ac 2 -i audio.raw -c:v h264 -c:a aac output.mp4`
to convert just the video you can do ` ffmpeg -r 30 -i video.264 -vcodec copy video.mp4`

**Comment by Conan179** [comment]
@exelix11 Thanks.
Its working.
I converted a file of about 3 minutes.
The only problem is that the video is finished faster than the sound.
https://www.dropbox.com/s/35voxj9kcexwe43/output.mp4?dl=0

**Comment by exelix11** [comment]
i'm not sure. Maybe ffmpeg got the framerate or sample rate wrong. Try converting audio and video separately and then mux them together.
This save to file thing was intended mostly for debug, should probably look into implementing and actual mp4 file writer.

**Comment by exelix11** [comment]
[Release 5.1](https://github.com/exelix11/SysDVR/releases/latest) replaced video.h264/audio.raw file exporting with proper mp4 recording, this shouldn't be an issue anymore.

**Comment by Conan179** [comment]
Thx!
