### ISSUE TITLE
[Bug] All homebrew nsp fail to open(11.0.1/M.16.2/E)

### ISSUE THREAD

**Issue by carcaschoi** [exelix11/SysDVR#105]
**Describe the bug**
After put the sysdvr 5.0.2 file in the sd card, all homebrew nsp fail to open

**To Reproduce**
1. put the version 5.0.2 of sysdvr into sd card
2. open homebrew nsp
3. show error(photo 1 is error after opening tinfoil，photo 2 is error after opening hbmenu 3.1.1 nsp，I also test with pfba forwarder and the error is the same as photo 1)

**Expected behavior**
fix the problem and release a newer version

**Setup information**
 - PC Os: NA
 - Console firmware 11.0.1
 - Custom firmware name and version: Atmosphere M.16.2
 - SysDVR version 5.0.2

My environment: 11.0.1/AMS M.16.2/E

**Additional context**
1. 10.2.0/AMS M.16.2/E doesn't have issue
2. 11.0.1/AMS M.16.1/E doesn't have issue
2. After remove sysdvr(11.0.1/AMS M.16.2/E), problem will be fixed

**Comment by exelix11** [comment]
I don't think this is a sysdvr issue as it's got nothing to do with that.
Either way nsp launchers for homebrew cause bans and are not recommended, it's something i'm not interested in testing even if it was an actual issue.
