### ISSUE TITLE
[Bug] Usb descriptors misconfigured

### ISSUE THREAD

**Issue by parkerlreed** [exelix11/SysDVR#106]
**Describe the bug**

When attempting to use the USB mode on Linux, errors are thrown constantly.

```
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=22
``` 

**To Reproduce**

1. Extract latest release on Linux
2. Run `dotnet SysDVR-Client.dll usb`

**Expected behavior**

Streaming from USB

**Setup information**
 - PC OS: Arch Linux
 - Console firmware: 11.0.1
 - Custom firmware name and version: Atmosphere 0.16.2 Mesosphere
 - SysDVR version: 5.0.2

**Additional context**

libusb 1.0.23-3

```
$ dotnet --version
3.1.108
```

**Comment by parkerlreed** [comment]
Just saw the --usb-debug option

[log.txt](https://github.com/exelix11/SysDVR/files/5753145/log.txt)

**Comment by exelix11** [comment]
From the log the error code seems to be 22 aka "invalid argument", not sure what could be causing this. Can confirm that it works fine on ubuntu for me.

On linux the usual suspects are permissions, i'd suggest making sure your account can access the switch with an udev rule or just try running the client as root. Also try a different usb cable and ports on your PC, if you're using an hub try connecting directly to the motherboarad.

Unfortunately can't help more than that cause there could be multiple points of failure both software and hardware and even googling the same error links to several different causes.

**Comment by parkerlreed** [comment]
Yeah without changing permissions it doesn't connect at all. This was after setting the permissions on the USB device. 

Thanks. That's what I was afraid of. Cable and everything seem to be okay so I'm not sure what's going on.

**Comment by unresolvedsymbol** [comment]
I'm also running into the exact same libusb error on Void Linux (glibc), another rolling release distro that's similar to Arch. Error 22 spam. Perhaps it's a USB 3.x bus issue?

**Comment by unresolvedsymbol** [comment]
Well sadly permissions didn't fix the issue. You'd get a permission denied error instead of spam anyway. Rule I tried: ` SUBSYSTEMS=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3006", GROUP="users", MODE="0660"` also tried way less strict mode.

**Comment by parkerlreed** [comment]
Doing some more digging: Is SysDVR using 1024 byte packets for USB? It seems some 2.0 and 3.0 controllers have issues with that.

**Comment by parkerlreed** [comment]
Max packet size is 64. 

```
Bus 003 Device 008: ID 057e:3006 Nintendo Co., Ltd SysDVR (Nintendo Switch)
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x057e Nintendo Co., Ltd
  idProduct          0x3006 
  bcdDevice            1.00
  iManufacturer           1 exelix
  iProduct                2 SysDVR (Nintendo Switch)
  iSerial                 3  https://github.com/exelix11/SysDVR 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0037
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    255 Vendor Specific Subclass
      bInterfaceProtocol    255 Vendor Specific Protocol
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
```

**Comment by exelix11** [comment]
Uhm are you using latest sysdvr on your console? In your output i see 4 bulk endpoints but i changed them to two pairs of interrupt and bulk endpoints to cut latency. Usb descriptors are defined [here[(https://github.com/exelix11/SysDVR/blob/master/sysmodule/source/USB/Serial.c#L62)

**Comment by parkerlreed** [comment]
Yeah I made sure it was updated (first through HB Appstore and then manually afterwards because I was questioning myself)

**Comment by exelix11** [comment]
Could this mismatch be causing the issue? Will check tomorrow on both windows and linux if the endpoints are properly recognized.
This could be very well a switch/libnx bug as usb is not very common in homebrew.

**Comment by exelix11** [comment]
Can confirm that windows detects two bulk endpoints as well.
```
          ---===>Open Pipes<===---

          ===>Endpoint Descriptor<===
bLength:                           0x07
bDescriptorType:                   0x05
bEndpointAddress:                  0x81  -> Direction: IN - EndpointID: 1
bmAttributes:                      0x02  -> Bulk Transfer Type
wMaxPacketSize:                  0x0200 = 0x200 max bytes
bInterval:                         0x00

          ===>Endpoint Descriptor<===
bLength:                           0x07
bDescriptorType:                   0x05
bEndpointAddress:                  0x01  -> Direction: OUT - EndpointID: 1
bmAttributes:                      0x02  -> Bulk Transfer Type
wMaxPacketSize:                  0x0200 = 0x200 max bytes
bInterval:                         0x00

          ===>Endpoint Descriptor<===
bLength:                           0x07
bDescriptorType:                   0x05
bEndpointAddress:                  0x82  -> Direction: IN - EndpointID: 2
bmAttributes:                      0x02  -> Bulk Transfer Type
wMaxPacketSize:                  0x0200 = 0x200 max bytes
bInterval:                         0x00

          ===>Endpoint Descriptor<===
bLength:                           0x07
bDescriptorType:                   0x05
bEndpointAddress:                  0x02  -> Direction: OUT - EndpointID: 2
bmAttributes:                      0x02  -> Bulk Transfer Type
wMaxPacketSize:                  0x0200 = 0x200 max bytes
bInterval:                         0x00
```

I changed libusb config to treat the request endpoint as bulk , check if this [build](https://github.com/exelix11/SysDVR/files/5789014/SysDVR-Client.zip) fixes your issue (just replace the dll in the release)

**Comment by unresolvedsymbol** [comment]
@exelix11 Thanks, that build seems to have solved the issue that this thread pertains to. I'll wait for Parker to test it before I assume it has anything to do with this, but I can't seem to get any video or audio output. I'm typically a wayland compositor user (sway) and the window won't ever show up so I temporarily started a simple X window manager (i3) and got a window but nothing would be drawn except for noise or whatever window was under it before.

**Comment by parkerlreed** [comment]
Working great here 
![image](https://user-images.githubusercontent.com/841440/104083458-abc79100-520c-11eb-994f-a87408e6f501.png)

Thanks!

**Comment by unresolvedsymbol** [comment]
Indeed you are correct, it does work! Strangely the USB only sysmodule doesn't seem to work for me, but when I saw you had the settings homebrew I installed the full version, switched over to USB mode in the homebrew and sure enough it started working flawlessly.

**Comment by exelix11** [comment]
Can't check rn can you post lsusb output for the usb only version, could that behave in a different way ?

**Comment by unresolvedsymbol** [comment]
Yes, of course. It doesn't seem to change a bit even at the highest verbosity output. [Here's ](https://hastebin.com/qezulekena.apache) my output. It seems to be hit or miss for me but I think I need to keep the USB unplugged before entering USB mode (either before starting a game?/turning on with USB only variant) or before switching with the homebrew on the full variant

**Comment by exelix11** [comment]
It shouldn't matter, the usb interface is always enabled when usimg the usb only sysmodule. 
Same for the full version except when switching modes depending on the system state sysdvr may wait for you to launch a compatible game before enabling usb, after that it's always enabled even if you change the game.
Note that if you're switching sysdvr versions (aka full to usb only or vice versa) you're supposed to reboot the console

**Comment by exelix11** [comment]
I was looking through the code, there's a huge copy-paste mistake introduced when i updated the usb code for 11.0, turns out my usb descriptors aren't being actually used and i'd say it's an incredible coincidence that usb streaming works at all.
This needs to be fixed so i'll reopen the issue till then. 
When i have a build with proper endpoints will ask one of you to test it on your set up to make sure interrupt endpoints don't break anything.

**Comment by exelix11** [comment]
Latest commit should have fixed it, could you try [this build](https://github.com/exelix11/SysDVR/files/5826092/exefs.zip) ? It's an usb-only build, just replace the `/atmosphere/contents/00FF0000A53BB665/exefs.nsp` file with the one in the zip. Use the client app from latest release and not the one i provided earlier.

**Comment by cosmopool** [comment]
> Latest commit should have fixed it, could you try [this build](https://github.com/exelix11/SysDVR/files/5826092/exefs.zip) ? It's an usb-only build, just replace the `/atmosphere/contents/00FF0000A53BB665/exefs.nsp` file with the one in the zip. Use the client app from latest release and not the one i provided earlier.

Had the same issue as the guys here and this build solve the problem. Thanks!

**Comment by exelix11** [comment]
The fix made it into [latest release](https://github.com/exelix11/SysDVR/releases/latest). The USB descriptors are now properly configured and should work fine on linux.
