### ISSUE TITLE
Sound missing when streaming homebrew menu

### ISSUE THREAD

**Issue by CosmicWave116** [exelix11/SysDVR#107]
When I stream gba emulator games from the homebrew menu, video is normal but no audio is streamed

To trigger the bug: Open homebrew menu from an app that can be recorded (pressing R while opening the app) and then use any homebrew app with sound

It should stream sound normally like every other game!

**Setup information**
 - PC Os: Windows 10 x64
 - Console firmware 11.0.1
 - Custom firmware name and version Atmosphère 0.16.2
 - SysDVR version 5.0.2 USB Only

(I am not really sure if this is a bug, but I hope you can help me)

**Comment by Conan179** [comment]
Your are only start the homebrew menu with pressing r? or with a homebrew menu forwarder?

**Comment by exelix11** [comment]
This is a libnx bug, same as #79.
Old libnx didn't handle audio correctly and causes this issue, it should have been fixed by now but homebrew compiled with previous versions are still broken. Only solution is to recompile the gba emulator with latest libnx.

**Comment by CosmicWave116** [comment]
> This is a libnx bug, same as #79.
> Old libnx didn't handle audio correctly and causes this issue, it should have been fixed by now but homebrew compiled with previous versions are still broken. Only solution is to recompile the gba emulator with latest libnx.

And how do I do that?

**Comment by exelix11** [comment]
Check if the developer made an update recently, that should work.
To compile on your own you'll need devkita64 and run make in the source directory, if you're not into coding maybe it's better to open an issue on the emulator's repo asking for an update and mentioning this issue.
