### ISSUE TITLE
Write in the screen record[Bug] 

### ISSUE THREAD

**Issue by Lola458** [exelix11/SysDVR#108]
Hello,

Everything is ok but when I start recording the game (Hyrule Warriors AoC for example), I have something written like ©Ninte... I want to remove it but I don't how to do that. There is a solution?

Great day to you.

**Comment by exelix11** [comment]
This is not a sysdvr issue, game publishers can decide to force an overlay on recorded clips, sysdvr just shows whatever the game ouputs.

I've seen around a patch for am which will disable that overlay (only for 10.2 but shouldn't be hard to port). I may provide such patches in the future but won't be bundling them in sysdvr as they depend on the firmware and will break with updates.
