### ISSUE TITLE
NXUSBS\DEVICES\0000

### ISSUE THREAD

**Issue by ImanCol** [exelix11/SysDVR#109]
Can't find the device, two unknown devices appear in my drivers

![image](https://user-images.githubusercontent.com/26169049/104105705-f6cdbc80-527d-11eb-94d6-17c0f53d4e28.png)

`SysDVR-Client - 5.0.1 by exelix
https://github.com/exelix11/SysDVR

Initializing video player with h264 codec.
libusb: error [enumerate_hcd_root_hub] program assertion failed - HCD 'ROOT\NXUSBH\0000' child not found
Unhandled exception. System.Exception: Device not found
   at SysDVR.Client.UsbContext..ctor()
   at SysDVR.Client.UsbContext.GetInstance()
   at SysDVR.Client.Program.Main(String[] args)`

**Comment by exelix11** [comment]
Did you install the driver as explained in the guide ?

**Comment by ImanCol** [comment]
YES. A week ago it worked. But now she no longer does. These unknown drivers are interfering. I've tried to uninstall them, but nothing, they come back

**Comment by exelix11** [comment]
Not sure, try installing the drivers again with zadig, then unplug and plug the console back in. If you're using an usb hub try connecting the switch directly to the motherboard.

**Comment by ImanCol** [comment]
FIX Uninstall NOMACHINE
![image](https://user-images.githubusercontent.com/26169049/107597877-0415f800-6bea-11eb-9623-543164cf2254.png)
