### ISSUE TITLE
Some games lose Stream when entering gameplay

### ISSUE THREAD

**Issue by Nepsyneptune** [exelix11/SysDVR#11]
Pokemon sword and sheild both "work" but as soon as you gain char control the stream stops.
In game dvr still functions tho (hold button and it takes 30 second clip)

**Comment by NoyTheBiche** [comment]
Works for me (Both shield and sword). I just launch sysdvr before launching the game.

**Comment by Nepsyneptune** [comment]
not for me 
Freeze on loading a save (pokeball loading icon)

**Comment by Nepsyneptune** [comment]
Also
Sems to work fine over USB 

just not network stream

**Comment by exelix11** [comment]
Haven't personally tested as i'm not interested in getting the game, from what i've been told the game is always in "local play" mode to find other players, this disconnects the switch from internet even if you're using a lan adapter, it seems to be a system limitation.
There's nothing i can do on SysDVR side to fix it and USB mode is not affected..

That said a patch could be developed to disable local play and a possible workaround would be using ldnmitm to prevent it from diconnecting. As i said not interested in doing the first and can't test ldnmitm so it would be great if someone could try and report back.

Closing as there's nothing i can do, but if anyone finds a workarond feel free to post here.

**Comment by Nepsyneptune** [comment]
Can confirm ldnmitm Fixes and allows for network streaming !
thanks!
