### ISSUE TITLE
[Help] problem when running SysDVR-Client.exe usb

### ISSUE THREAD

**Issue by rodralvarez** [exelix11/SysDVR#111]
**Where do you get stuck ?**
When running dotnet SysDVR-Client.exe usb

**What's the error message you get ?**
  An assembly specified in the application dependencies manifest (SysDVR-Client.deps.json) has already been found but with a different file extension:
    package: 'SysDVR-Client', version: '5.0.0'
    path: 'SysDVR-Client.dll'
    previously found assembly: '/home/user/sysdvr/SysDVR-Client.exe'

**Setup information**
openSUSE Tumbleweed x86_64, kernel 5.8.0-1

**Additional context**
I haven't been able to find anything online.
The SysDVR settings app on the switch is configured to work in usb mode already.  
I followed all the instructions, I only have this issue.

**Comment by exelix11** [comment]
The exe is a windows launcher. 
Do `dotnet SysDVR-client.dll help`

**Comment by rodralvarez** [comment]
Yes, that works. In the wiki it says "Launch SysDVR-Client usb to begin streaming." how do I do that on linux? Do I have to run wine SysDVR-Client.exe usb? (If that's the case I have to fix my wine configuration)

**Comment by exelix11** [comment]
No you do dotnet SysDVR-client.dll for everything, it's written in the client setup on linux maybe i should clarify that.

**Comment by rodralvarez** [comment]
thanks that fixed it.
