### ISSUE TITLE
[Help] very good software. Does it have anyway to power charge SWITCH , when USB is streaming  connection

### ISSUE THREAD

**Issue by songyuyx** [exelix11/SysDVR#112]
Its very very good software, works very nice!

just a question:  Does it have anyway to power charge SWITCH , when USB is streaming  connection

**Comment by exelix11** [comment]
Unfortunately regular PC usb ports can only provide 500mA of power, maybe you can try with an externally powered usb hub (even though i don't reccomend usb streaming through usb hubs).
Another option would be network streaming through a lan adapter from the dock, that should eliminate all the latency issues that come with wifi.
There's nothing that can be done via software about this.

**Comment by songyuyx** [comment]
thanks for answers, good software
