### ISSUE TITLE
Audio and Video devices not found in Zadig, error message ensues

### ISSUE THREAD

**Issue by Mechaghostman2** [exelix11/SysDVR#113]
**Where do you get stuck ?**
[I got stuck when I needed to install USB drivers for audio and video interface. They simply aren't there. So when I go to launch, I just get more or less an error message.]

**What's the error message you get ?**
[Unhandled exception. System.Exception: Assertion failed: -1WASAPI can't find requested audio endpoint: Element not found.

At SysDVR.Client.Player.Exten.Assert(Intl3w code, Func'1 MessageFun)
At SysDVR.Client.Player.InitSDLAudio(AudioStreamTarget target)
At SysDVR.Client.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
At SysDVR.Client.Player..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
At SysDVR.Client.Program.Main(String[] args)
]

**Setup information**
 - PC OS: [Windows 10 x64]
 - Console firmware [11.0.1]
 - Custom firmware name and version [Atmosphere M1.17.1]
 - SysDVR version [5.0.2]
C:\Users\User\Desktop\SysDVR-Client>

**Additional context**
So clearly while this is being shown, no game footage will run. Just the error message.

It does work when running MVP, but it has like a 30 second delay, which previous versions didn't have. Also, it doesn't have audio.

I'm speculating that it's the new OS updates on the Switch that are preventing this, or possibly the fact that my PC is entirely offline at the moment. Either way, these are the problems.

**Comment by exelix11** [comment]
I see two different problems here.
First installing the driver, if you installed the driver in the past zadig will not show the device you have to click like on view -> show hidden devices or something similar. If it still doesn't show probably SysDVR is not in usb mode, change it with the settings app from the homebrew menu.

Second:
> [Unhandled exception. System.Exception: Assertion failed: -1WASAPI can't find requested audio endpoint: Element not found.
At SysDVR.Client.Player.Exten.Assert(Intl3w code, Func'1 MessageFun)
At SysDVR.Client.Player.InitSDLAudio(AudioStreamTarget target)

This is not a sysdvr problem but SDL fails to initialize audio, i haven't seen this before, is audio working normally on your PC ? Found a [thread](https://trac.ffmpeg.org/ticket/6891) related to this issue by searching on google and it includes a workaround which you could try.

> It does work when running MVP, but it has like a 30 second delay, which previous versions didn't have. Also, it doesn't have audio

Again points towards audio drivers being messed up on your OS.
About the delay try enabling low latency mpv modes from advanced settings in the GUI, if you don't enable those mpv will run with default buffering settings which will cause some delay.

**Comment by Mechaghostman2** [comment]
Ok. The audio issue was simply due to lacking any kind of speaker or headphone being connected.

As for the drivers, I had to unplug my Switch a few times. It just says SysDVR (Nintendo Switch) and not video interface 0 etc. However, it's now fully working, even with the integrated player.

One thing people should be aware of is to access it through the album folder and not by holding down R and selecting a game.

**Comment by exelix11** [comment]
> As for the drivers, I had to unplug my Switch a few times. It just says SysDVR (Nintendo Switch) and not video interface 0 etc. However, it's now fully working, even with the integrated player.

Assuming you're using latest version it's possible that zadig will show only one device if you installed the custom driver previously, it's not a problem.

> One thing people should be aware of is to access it through the album folder and not by holding down R and selecting a game.

I don't know about this, it should work with both methods.
