### ISSUE TITLE
[Bug] Linux Libusb not working

### ISSUE THREAD

**Issue by BlockListed** [exelix11/SysDVR#115]
**Where do you get stuck ?**
[Which step of the guide ? Did you read the Troubleshooting section at the end ?]
Starting Sysdvr in usb mode

**What's the error message you get ?**
[If you see a black window appearing and disappearing quickly and can't read the error you can launch the program in a command prompt manually so it won't disappear, [here's how](https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8)]
libusb: error [submit_bulk_transfer] submiturb failed, errno=22 (3o times a second)

**Setup information**
 - PC OS: Arch X64
 - Console firmware: 11.0.1
 - Custom firmware name and version: 0.16.2
 - SysDVR version: 5.0.2

**Additional context**
Started as root, because libusb denies access otherwise.
Libusb 1.0.24-2 from Arch repos.

**Comment by exelix11** [comment]
Looks like the same issue as https://github.com/exelix11/SysDVR/issues/106, can you check if the test build provided there fixes the issue for you ?

**Comment by BlockListed** [comment]
Thanks so much! Could you please add this fix to the next release?

**Comment by exelix11** [comment]
Yes, haven't released it yet because i'm working on other features and it's a bug that doesn't affect many people.
I'm closing this as duplicate, if you have more questions you can post them in the other issue.
