### ISSUE TITLE
[Bug] Game Freezes When Opening Text/Controller Connect Menu

### ISSUE THREAD

**Issue by JackTYM** [exelix11/SysDVR#116]
**Describe the bug**
Whenever I play a game (in this example BOTW) And I have to use the keyboard to input a name etc, it will freeze the game and cause me to restart it. This also happens when a local multiplayer game opens up the controller connect screen. I troubleshooted and one by one removed my sysmodules until i found out this was causing the problem.

**To Reproduce**
Have SysDVR installed and go into a game that requires text to be inputted or controllers to be added

**Expected behavior**
I expected the text / controller screen to open like it did when SysDVR was deleted from atmosphere/contents

**Setup information**
 - PC Os: Windows 10 x64
 - Console firmware 11.0.1
 - Custom firmware name and version Atmosphere 17.0
 - SysDVR version 5.0.2

**Additional context**

**Comment by exelix11** [comment]
Haven't tried this recently but i don't remember it being an issue, could you try with just sysdvr running? Maybe you just have too many sysmodules.

**Comment by JackTYM** [comment]
> Haven't tried this recently but i don't remember it being an issue, could you try with just sysdvr running? Maybe you just have too many sysmodules.

Okay yeah it seems it is conflicting sysmodules because it doesn’t happen when SysDVR is taken out, and it doesn’t happen when only SysDVR is in. What is the fastest / most effective way to go about troubleshooting this?

**Comment by exelix11** [comment]
Most likely there's no single culprit sysmodule but just the combination of them so i'd say start with a fresh copy of atmosphere and install only the ones you need, one at a time if you want to find out what's the limit.
