### ISSUE TITLE
[Bug]  [submit_bulk_transfer] submiturb failed

### ISSUE THREAD

**Issue by iMonZ** [exelix11/SysDVR#117]
Using Ubuntu 20.10 with the normal SysDVR Client on my Nintendo Switch 10.2.0 emuNand on SXos.

When I try to connect my switch with this command: 
`sudo dotnet SysDVR-Client.dll usb --rtsp-any-addr --rtsp`
It will throw this error after i opened a game:
`libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=22`

**Comment by exelix11** [comment]
Most likely duplicate of https://github.com/exelix11/SysDVR/issues/106
