### ISSUE TITLE
Lossless screenshots?

### ISSUE THREAD

**Issue by mariomadproductions** [exelix11/SysDVR#12]
Would it be possible for this to output lossless screenshots to the PC (or SD)?

**Comment by exelix11** [comment]
Not with this sysmodule.
Lossless screenshot is a special function accessble only to system applets, the only way to get them currently is xortroll's uLaunch, but that feature requires usb access and can't work with SysDVR.
I'm working on a custom overlay which will be able to do it as well but it's not yet released and no eta currently.

**Comment by TheGreatRambler** [comment]
Pardon me for asking, but could you share the Api function call you are referring to? I have been looking for the way to get the raw framebuffer and you seem to know about this subject.

**Comment by exelix11** [comment]
This one: https://reswitched.github.io/SwIPC/ifaces.html#nn::am::service::IDisplayController(5)
Note that it's not actually accessing the framebuffer, it copies it at every call so you can't edit it.
Also it's pretty slow so no video recording and you can only call it from system applets like the home menu and overlay.

**Comment by TheGreatRambler** [comment]
Oh... hmmm. How much latency does the actual `grcdServiceRead` function call in your code take? I know that the program in its entirety has about a second of delay, but does `grcdServiceRead` run instantaneously?

**Comment by exelix11** [comment]
Tbh never measured it, pretty sure most of the delay is hardware encoding and caching for decoding on the pc side.
