### ISSUE TITLE
Streaming issues while playing pokemon sword VIA TCP

### ISSUE THREAD

**Issue by sanaguj** [exelix11/SysDVR#125]
Streaming would be fine with other games like outlast, animal crossing, tetris. But when it comes to pokemon sword it works for awhile only at the loading screen but once i get into the game where my character appears no audio comes out and screen is frozen, im assuming its something to do with local communications? is there any fix to this

**Comment by exelix11** [comment]
Yes, pokemon sw/sh always enters local play mode which disconnects the switch from the wifi. A workaround is to use ldnmitm to prevent it from disconnecting, there's nothing i can do about it on the sysdvr side.

**Comment by sanaguj** [comment]
whats idnmitm

**Comment by exelix11** [comment]
[this](https://github.com/spacemeowx2/ldn_mitm), it's for online play on games that use local communication. You'd only need it to prevent pokemon from disconnecting from the wifi.
