### ISSUE TITLE
[Bug] Usb C to C cable does not work.

### ISSUE THREAD

**Issue by Celisot** [exelix11/SysDVR#126]
**Describe the bug**
When I'm trying to install the custom driver on zadig, my switch wont show up in connected devices even after selecting list all devices

**To Reproduce**
It happened while installing the custom driver in Zadig

**Expected behavior**
I expected for my switch to show up in connected devices

**Setup information**
 - PC Os: Windows 10 x64
 - Console firmware 11.0.1
 - Custom firmware name and version Atmosphere 0.18.1
 - SysDVR version 5.1 SysDVR

**Additional context**
Im using a mac charger as the usb c cable because my pc supports usb c (I know it supports data transfer since I use it to inject payloads from my windows to switch)
![Screenshot 2021-04-09 174406](https://user-images.githubusercontent.com/82245617/114252649-367a7200-995b-11eb-807f-1a7b9749ae2e.png)

**Comment by exelix11** [comment]
Did you enable usb mode with sysdvr settings on your switch?
If you did I'd suggest trying with an usb c to A cable to be safe, i did not test a c to c cable.

**Comment by Celisot** [comment]
I enabled USB mode but I don't have a USB a to c cable

**Comment by exelix11** [comment]
Unfortunately i can't help you, if zadig doesn't see the switch at all it's some hardware problem.
Even when sysdvr is not running windows should show a device called "Nintendo Switch" but in your case it's not being detected at all.

**Comment by Celisot** [comment]
Ill try to get a usb a to c cable but thx for the info
