### ISSUE TITLE
[Feature request] USB Port invalid on system 11.0.1

### ISSUE THREAD

**Issue by gnatydnac** [exelix11/SysDVR#127]
Steaming via wifi is still ok, USB got a whitescreen. Heard something changed with USB on sys 11.x. Hope to be fixed.

**Comment by exelix11** [comment]
11.0 support was added a few releases ago. Download latest version and it should work.
If you have issues reinstall the WinUsb driver with zadig, before i was using libusb but had to switch to get better performances. Follow the [usb setup guide](https://github.com/exelix11/SysDVR/wiki/USB-Driver)
