### ISSUE TITLE
Stream to file

### ISSUE THREAD

**Issue by NO-ob** [exelix11/SysDVR#13]
Is there a way to make it stream to a file or do we just need to record with some screen capture software

**Comment by exelix11** [comment]
For usb you can save to file, you'll have to manually convert it and merge audio and video afterwards.
For network stream you could probably pipe a netcat to a file but there's no direct option.
Next version will have saving directly to mp4, maybe support for network stream too.

**Comment by exelix11** [comment]
SysDVR V3 is out, in the end decided to scrap this feature as it was more complex than it sounded like, good news is that with RTSP support you can receive the stream with a software like OBS and use it to record to disk, much more stable and uses already battle-tested software.
