### ISSUE TITLE
[Bug] SysDVR-conf.nro（v5.1） can not work in SXOS 11.0.0 

### ISSUE THREAD

**Issue by broardshore** [exelix11/SysDVR#131]
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**
There is QR code interface."It's not a latest version".
But I did use the latest version.

v5.0.2 works normally on my switch.

**To Reproduce**
[Explain how to trigger the bug]
The same to v5.0.2.
**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Setup information**
 - PC Os: [Windows 10 x64]
 - Console firmware [TX 11.0.0]
 - SysDVR version [3.0 Usb-Only]

**Additional context**
No.

**Comment by exelix11** [comment]
I think you installed only the new settings app and not the actual sysmodule.
The release zips are in atmosphere format, you'll have to rename `atmosphere` to `sxos` and `contents` to `titles` before extracting to your sd or else the main sysmodule won't get updated.
After you copy the files you have to reboot the console.

**Comment by broardshore** [comment]
I did rename atmosphere to sxos and contents to titles before extracting to my sd.Then I reboot my NS,open the nro app in HOMEDREW menu.
I tried it twice and it didn't work.

**Comment by broardshore** [comment]
![QQ截图20210416153814](https://user-images.githubusercontent.com/20060544/114989413-fa4e9080-9ec9-11eb-918f-444c4fe0b796.jpg)
![QQ截图20210416153829](https://user-images.githubusercontent.com/20060544/114989430-fd498100-9ec9-11eb-8713-571decba55ff.jpg)

**Comment by exelix11** [comment]
Are you trying to copy both 5.1 and 5.0.2 versions at the same time ?

**Comment by broardshore** [comment]
In order to compare and test, in case of confusion, I specially divided two folders to store two versions of files.
I only copy the contents of one folder to my sd card at a time.

**Comment by broardshore** [comment]
When v5.1 fails,I copy v5.0.2 files to my sd to replace the v5.1 files。Restart the device，the nro file works normally.

**Comment by broardshore** [comment]
SysDVR version [5.1 full version]
not SysDVR-USB-Only

**Comment by exelix11** [comment]
mh i think you may have mixed up the files in the folders you copy, could you try downloading a fresh copy of 5.1 from github ?

**Comment by broardshore** [comment]
> mh i think you may have mixed up the files in the folders you copy, could you try downloading a fresh copy of 5.1 from github ?

of course.
![QQ截图20210416163604](https://user-images.githubusercontent.com/20060544/114996931-ed359f80-9ed1-11eb-9602-bcb32ba0cfb2.jpg)
![QQ截图20210416163540](https://user-images.githubusercontent.com/20060544/114996958-f45cad80-9ed1-11eb-81c7-29741d42469b.jpg)
i will try again half an hour later.i'm working in a company before 17:00(Beijing).

**Comment by broardshore** [comment]
This time there are some changes.
"SysDVR is already switching modes
Enter a game to complete the operation"

**Comment by exelix11** [comment]
iirc that's after the version check so it should be working.
Try launching a compatible game

**Comment by broardshore** [comment]
I reboot device again.finally,the option UI shows. 
Thank you very much!

**Comment by exelix11** [comment]
👍
