### ISSUE TITLE
[Feature request] Disable mouse cursor on Linux?

### ISSUE THREAD

**Issue by potatoxbe** [exelix11/SysDVR#133]
**Is your feature request related to a problem? Please describe.**
I'm on a desktop-less Linux on Pi, and trying to get the mouse cursor to hide when SDL window shows. Reading around, seems has to be disabled from the program.

**Describe the solution you'd like**
No mouse cursor would be great =D

**Comment by exelix11** [comment]
With [Latest release](https://github.com/exelix11/SysDVR/releases/latest) the mouse cursor is hidden in full screen mode.

**Comment by Johny-LPM** [comment]
> With [Latest release](https://github.com/exelix11/SysDVR/releases/latest) the mouse cursor is hidden in full screen mode.

With SysDVR 6.2.1 it's not hidden. Using headless Raspberry Pi OS Bookworm on RPi 400. 
Anything we can change in the code or something to fix it?

**Comment by Johny-LPM** [comment]
Could be a bug with SDL on the Debian12 repo, but I'm not running a DE, just headless like I had said. I just launch SysDVR-Client from console with dotnet. I'll look into it, thank you!

**Comment by exelix11** [comment]
The interesting part is that imgui already supports hiding/showing the mouse cursor. Since you changed that flag it means that code path gets somehow hit on your rpi. Wonder if it will get fixed ifi just stop calling the SDL function manually and rely on imgui instead. I'll give that a shot

**Comment by Johny-LPM** [comment]
The only thing I can point to is this video from a few years ago already where it also happened [DOCK Nintendo Switch Lite on TV with Raspberry Pi (2021 HOW TO)](SysDVRhttps://www.youtube.com/watch?v=mJ4-HXS2H74)

I guess not that many people are using headless setups like these for this purpose and/or it took someone who was bothered enough and had a vague knowledge of these components and what they do to look a little bit more into it xD

Either that or there are more people using --legacy for headless, which makes sense, but for some reason in my setup it results in a very stuttery stream, and with CimguiCross it's way better. People not running headless/not being bothered by it/not knowing how (or wanting) to report/using --legacy, makes sense.

Anyways, I'll look into compiling latest commit to test it later and let you know, I was just using 6.2.1 currently.

**Comment by exelix11** [comment]
CimguiCross uses proper vsync rendering with imgui, the legacy player updates the screen manually only when there's a new frame. I'd expect the former to work better on crappy drivers.

You can grab a build from github actions. The "dotnet" package is the plain build of the client with no third party libraries, for use on windows merge them from a release, on raspberry you don't need much else.

**Comment by exelix11** [comment]
Yeah sounds great. The sysdvr guide is hosted in the wiki tho, I think you cant PR directly. you'll have to fork that and I'll need to manually push the updated files.

For CimguiCross you can directly pr there.
