### ISSUE TITLE
[Bug] Warning: libusb error Timeout while reading header - on Pi Linux

### ISSUE THREAD

**Issue by potatoxbe** [exelix11/SysDVR#134]
**Describe the bug**
There's a stutter every 10 seconds or so on USB mode with Pi 3 and 4. Tried on multiple OSs like Raspberry, Gentoo64, Manjaro, same behaviour. No issues on bridge mode. Trying to debug what's wrong, hope you can help.

Using - - print-stats, I see that with every stutter, there's a warning for
Warning: libusb error Timeout while reading header

**To Reproduce**
USB mode

**Expected behavior**
Hope USB mode runs smoothly. 

**Setup information**
 - PC Os: Raspberry Pi OS 32bit, 64bit, Gentoo64, Manjaro on Raspberry Pi 3B+ and Raspberry Pi 4B
 - Nintendo firmware 10.2.0
 - SXOS 3.1.0
 - SysDVR 5.1

**Comment by exelix11** [comment]
Unfortunately i don't know the reason and i'm not sure how to debug this on linux.
There could be several reasons both hardware and software, first thing i'd suggest trying with a different usb cable after that you could try a different libusb version.

If i remember correctly in some raspberry models the usb and lan ports shared the same bus, i don't know if that's still the case but could you check if that's related to network activity ?
