### ISSUE TITLE
[Bug] Does not run on Linux

### ISSUE THREAD

**Issue by Martmists-GH** [exelix11/SysDVR#135]
Output below

<details>
<summary>without sudo</summary>
<code><pre>
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/069, errno=13
libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
LibUsbDotNet.LibUsb.UsbException: Access denied (insufficient permissions)
   at LibUsbDotNet.LibUsb.ErrorExtensions.ThrowOnError(Error error)
   at LibUsbDotNet.LibUsb.UsbDevice.Open()
   at SysDVR.Client.Sources.UsbContext..ctor()
   at SysDVR.Client.Sources.UsbContext.GetInstance()
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)
</pre></code>
</details>

<details>
<summary>with sudo</summary>
<code><pre>
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
System.Exception: Asserition failed: -1 ALSA: Couldn't open audio device: Device or resource busy
   at SysDVR.Client.Player.Exten.Assert(Int32 code, Func`1 MessageFun)
   at SysDVR.Client.Player.Player.InitSDLAudio(AudioStreamTarget target)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)

</pre></code>
</details>

**Comment by exelix11** [comment]
> ALSA: Couldn't open audio device: Device or resource busy

Possibly you can't open an audio session from root ? Try creating an [udev rule](https://askubuntu.com/questions/978552/how-do-i-make-libusb-work-as-non-root) to let sysdvr access the usb without root then run without sudo and it should work.

Sysdvr vid is 0x057e and pid is 0x3006

**Comment by SBence** [comment]
I know this is an old issue but it's still open and I encountered it as well so I figured why not comment that making a file in `/etc/udev/rules.d` with the contents of `SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3006", TAG+="uaccess"` solved the issue for me. No need to reload rules nor reboot, just unplug then replug the Switch, then run the SysDVR client without sudo (simply `dotnet SysDVR-Client.dll` in my case).

**Comment by FelipeSilva93** [comment]
Guys, any other possible solution for that?

I'm having the following issue:

System.Exception: Asserition failed: -1 ALSA: Couldn't open audio device: Host is off (the message is in portuguese here, but it says that the host is offline).

Tks.

**Comment by weirdal3333** [comment]
Someone should rewrite this app in something that's not dotnet. Writing it in C or python would allow it to run much faster on any operating system. There wouldn't need to be any fancy dotnet commands or installations.

**Comment by exelix11** [comment]
Feel free to do it.

**Comment by PhazonicRidley** [comment]
personally i think we should rewrite it in tegrascript.

**Comment by CitricDolphin1** [comment]
> I know this is an old issue but it's still open and I encountered it as well so I figured why not comment that making a file in `/etc/udev/rules.d` with the contents of `SUBSYSTEM=="usb", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="3006", TAG+="uaccess"` solved the issue for me. No need to reload rules nor reboot, just unplug then replug the Switch, then run the SysDVR client without sudo (simply `dotnet SysDVR-Client.dll` in my case).

Can you please specify the name of the file you created? I've tried 51-usb-device.rules and 50-usb-scale.conf but neither of them do anything.

**Comment by giga** [comment]
Maybe use lsusb to make sure idVendor and idProduct are correct.
