### ISSUE TITLE
[Help] Zadig does not find Drivers

### ISSUE THREAD

**Issue by wellmentz** [exelix11/SysDVR#137]
**Where do you get stuck ?**
[Zadig does not show Audio and Video Drivers, list my switch only on RCM mode as APX]

**Setup information**
 - PC OS: [Windows 10 x64]
 - Console firmware [12.0.1]
 - Custom firmware name and version [Atmosphere M19.3|E]
 - SysDVR version [5.1]

**Comment by exelix11** [comment]
Are you trying to use zadig while your switch is in RCM mode ? 
You have to be running atmosphere with the sysdvr sysmodule, then switch to usb mode with sysdvr settings and then zadig should show the correct devices.

**Comment by wellmentz** [comment]
I also did with sysdrv open, it does not find on zadig

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: exelix ***@***.***>
Enviado: Sunday, June 6, 2021 6:30:28 AM
Para: exelix11/SysDVR ***@***.***>
Cc: wellmentz ***@***.***>; Author ***@***.***>
Assunto: Re: [exelix11/SysDVR] [Help] Zadig does not find Drivers (#137)


Are you trying to use zadig while your switch is in RCM mode ?
You have to be running atmosphere with the sysdvr sysmodule, then switch to usb mode with sysdvr settings and then zadig should show the correct devices.

**Comment by exelix11** [comment]
You probably did something wrong or are using a bad usb wire. Try again following step by step the [usb setup guide](https://github.com/exelix11/SysDVR/wiki/USB-Driver).
In particular try the following:
1) Open sysdvr settings on your switch
2) Select usb mode, then click save and exit
3) You should be in the homebrew menu, connect the console to the pc
4) Open zadig and you should see the sysdvr devices

If you still don't see them try enabling show hidden devices in zadig options. If this still doesn't work try a different usb cable and ports of your pc.

**Comment by wellmentz** [comment]
That s really weird, I’ve tryied with 3 different cables, changed all usb ports, Tegra it is able to find it, but zadig not.

De: exelix ***@***.***>
Enviada em: domingo, 6 de junho de 2021 09:05
Para: exelix11/SysDVR ***@***.***>
Cc: wellmentz ***@***.***>; Author ***@***.***>
Assunto: Re: [exelix11/SysDVR] [Help] Zadig does not find Drivers (#137)


You probably did something wrong or are using a bad usb wire. Try again following step by step the usb setup guide<https://github.com/exelix11/SysDVR/wiki/USB-Driver>.
In particular try the following:

  1.  Open sysdvr settings on your switch
  2.  Select usb mode, then click save and exit
  3.  You should be in the homebrew menu, connect the console to the pc
  4.  Open zadig and you should see the sysdvr devices

If you still don't see them try enabling show hidden devices in zadig options. If this still doesn't work try a different usb cable and ports of your pc.
