### ISSUE TITLE
Could write data to device

### ISSUE THREAD

**Issue by Laproxi** [exelix11/SysDVR#14]
![d](https://user-images.githubusercontent.com/40793608/70380498-3bc54800-1934-11ea-80cb-6dedc2a760be.png)

**Comment by exelix11** [comment]
If you launched from the gui try enabling detailed logs.
Either way this issue usually happens if you did not configure the driver properly or if you didn't enable USB mode in sysdvr. Read the reaadme carefully.

**Comment by Laproxi** [comment]
Issue semi-resolved; I translocated MPV to within the same folder as the USB client and it resolved this issue: might have something to do with downloading a portable version of MPV.
