### ISSUE TITLE
[Help] Problem connecting in TCP/IP bridge mode

### ISSUE THREAD

**Issue by azh97** [exelix11/SysDVR#141]
First of all, thank you for this amazing app. My issue is, I usually use the USB mode, and it works flawlessly till now but when I switch to TCP/IP bridge mode, it seems that Sysdvr couldn't establish a connection with my PC. I already allow the app through firewall settings, and also port forwarding port 6666 and 6667 on my router. Hope you could give me some insight regarding this. Thanks in advance. 

I attached the error message that appeared on the CMD window below.

![image](https://user-images.githubusercontent.com/40840494/122641471-31def080-d138-11eb-8c9b-b4dcb61ef447.png)

**Setup information**
 - PC OS: Windows 10 x64
 - Console firmware : 12.0.0
 - Custom firmware name and version : Atmosphere 0.19.3
 - SysDVR version : ClientGUI

**Comment by exelix11** [comment]
The error says "the target machine actively refused the connection" so either you typed the wrong ip addres or sysdvr on your console is not in tcp bridge mode. Open the settings app and switch to tcp bridge mode, it will also show the right ip address.
> port forwarding port 6666 and 6667 on my router

Port forwarding is useless here as it's a LAN connection, Disable it. Also those are the RTSP ports and not the tcp bridge ones so it's wrong either way.

**Comment by azh97** [comment]
I checked the switch IP address using the router app and used that. So I assume that the IP address I used is already correct. I also changed the mode to TCP/IP, the app said that 'mode is already changed, please switch to your game' when I double check, so I'm assuming that that's also correct. But the problem is still there. I'll try again just to be sure.

Btw, I'm using 90dns. Is this affects anything?

**Comment by exelix11** [comment]
Resuming your game should complete the mode switch and it should work. There's a bug that sometimes this doesn't happen, rebooting the console should fix it.

**Comment by azh97** [comment]
So I tried setting up the TCP/IP mode as current and on boot after rebooting my Switch. This somehow made it to work. Thank you very much. Really appreciate the fast replies.
