### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by dragon2snow** [exelix11/SysDVR#142]
**Setup information**
 - PC OS: [ Windows 10 x64]
 - Console firmware [12.0.3]
 - Custom firmware name and version [ Atmosphere 0.19.4]
 - SysDVR version [SysDVR 5.1]

**Additional context**
The streaming will be disconnected while some games are being saved

**Comment by exelix11** [comment]
Could you show an example? I think it's something specific to the game you tried.
Usualy when the game loses focus (eg when opening the keyboard or the user select screen) sysdvr stops streaming, i suspect you're seeing something similar. That is a limitation of the os and can't be fixed for now.
