### ISSUE TITLE
[Help]Does not work on Win11

### ISSUE THREAD

**Issue by Memotherfuck123** [exelix11/SysDVR#144]
**Setup information**
 - PC OS: [e.g. Windows 11 x64]

**Comment by exelix11** [comment]
At least provide the error message you get, with no information like this there's nothing i can do.
Does it work with your same setup but on 10 ?

**Comment by Danker1990** [comment]
if this helps out here is my error codes.

C:\Users\danny\Desktop\SysDVR-Client>dotnet SysDVR-Client.dll usb
SysDVR-Client - 5.1 by exelix
https://github.com/exelix11/SysDVR

Initializing video player with h264 codec.
Starting stream, close the player window to stop.
Press F11 for full screen, esc to quit.

Initialized SDL with direct3d renderer
[h264 @ 000001f369406a00] error while decoding MB 56 5, bytestream -6
[h264 @ 000001f369406a00] concealing 3193 DC, 3193 AC, 3193 MV errors in P frame
[h264 @ 000001f369406a00] error while decoding MB 47 40, bytestream -45
[h264 @ 000001f369406a00] Frame num change from 13 to 7
[h264 @ 000001f369406a00] decode_slice_header error
[h264 @ 000001f369406a00] concealing 402 DC, 402 AC, 402 MV errors in P frame
