### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Royyeuh** [exelix11/SysDVR#145]
**Describe the bug**
the built-in sysdvr player only shows a black screen, and the command prompt indicates the following error:"libusub:error [udev_hotplug_event] ignoring udev action bind

**To Reproduce**
1) install the sysdvr client and all of its dependencies, and the sysdvr sysmodule
2)run the sysdvr client

**Expected behavior**
sysdvr streaming the game image

**Setup information**
 - PC Os: [Ubuntu 20.04]
 - Console firmware [12.0.2]
 - Custom firmware name and version [Atmosphere 0.19.3]
 - SysDVR version [5.1]

**Comment by exelix11** [comment]
a quick google search of the error suggests this may be an issue with your usb hub, see: https://github.com/libusb/libusb/issues/421

**Comment by Royyeuh** [comment]
im connected directly to the pc though, weird

**Comment by Royyeuh** [comment]
changing the port worked the usb is plugged in worked
have a nice day :)
