### ISSUE TITLE
higher recording framerate (maybe resolution?)

### ISSUE THREAD

**Issue by zhubibaba** [exelix11/SysDVR#147]
;Game Recording FPS and Bitrate
[am.debug]
;30 or 60
continuous_recording_fps=u32!60
;~7.5Mbps(0x780000 = 7,864,320), default is ~5Mbps, VBR(Variable Bitrate)
continuous_recording_video_bit_rate=u32!0x780000

add this in atmosphere/config/system_settings.ini. and it become 60fps. works on 0.19.5
wonder if there is any way to change recording resolution?

**Comment by exelix11** [comment]
That's pretty cool, i don't know about resolution but note that if you try changing that you'll have to edit sysdvr's code in several places.
The 720p resolution is hardcoded both as raw value and as PPS and SPS parameters ([here](https://github.com/exelix11/SysDVR/blob/master/Client/StreamInfo.cs) and [here](https://github.com/exelix11/SysDVR/blob/67a19a3c2ff18f2bb6c3c65ccfa83ebb5f870bfd/sysmodule/source/main.c#L167)), you'll have to capture the NALs the console emits when working at higher resolution and replace them.

I wonder, does 60 fps streaming affect performances in games or break game recording ? In theory it's using more gpu bandwidth and using the 30 seconds buffer faster.

**Comment by zhubibaba** [comment]
i got from this report:https://github.com/KazushiMe/Switch-OC-Suite

"[Game recording and SysDVR streaming @ 60fps with high video bitrate (Optional).

Video duration shown in album will be 2x than the actual value, but playback speed is not affected.
Recordings may be less than 30sec if higher bitrate is used.

It has noticeable performance impacts in demanding games.
For optimal streaming experience, SysDVR via USB interface is recommended]

**Comment by Dieal** [comment]
> system_settings.ini

Hi, in atmosphere/config/ i cannot find the system_settings.ini, do I have to add it manually?

**Comment by qrstuvv** [comment]
> > system_settings.ini
> 
> Hi, in atmosphere/config/ i cannot find the system_settings.ini, do I have to add it manually?

yes you do. what does it mean "add this in" though? im relatively new to switch modding and need a litle help

**Comment by Shailing** [comment]
> ;Game Recording FPS and Bitrate [am.debug] ;30 or 60 continuous_recording_fps=u32!60 ;~7.5Mbps(0x780000 = 7,864,320), default is ~5Mbps, VBR(Variable Bitrate) continuous_recording_video_bit_rate=u32!0x780000
> 
> add this in atmosphere/config/system_settings.ini. and it become 60fps. works on 0.19.5 wonder if there is any way to change recording resolution?

Should I add it after all the other lines of code?

**Comment by zhubibaba** [comment]
> > ;Game Recording FPS and Bitrate [am.debug] ;30 or 60 continuous_recording_fps=u32!60 ;~7.5Mbps(0x780000 = 7,864,320), default is ~5Mbps, VBR(Variable Bitrate) continuous_recording_video_bit_rate=u32!0x780000
> > add this in atmosphere/config/system_settings.ini. and it become 60fps. works on 0.19.5 wonder if there is any way to change recording resolution?
> 
> Should I add it after all the other lines of code?

yes

**Comment by parkerlreed** [comment]
Was SysDVR ever updated to account for this change or does it still need tweaked?

**Comment by exelix11** [comment]
Afaik it works but it's not officially supported since it breaks some os features and requires overclock

**Comment by Kupie** [comment]
> Afaik it works but it's not officially supported since it breaks some os features and requires overclock

Thanks exelix!

May I ask, what OS features does it break?

**Comment by exelix11** [comment]
Supposedly game recording with the capture button doesn't work well anymore

**Comment by Kupie** [comment]
> Supposedly game recording with the capture button doesn't work well anymore

Oh, interesting!

I've been using this 60fps mod + your sysDVR patches for years now, haven't ran into any issues... playing back the 60fps recordings using the album is kinda crap, and recordings are only ~15seconds but I find this worth it in games like Smash.

Ty so much for all the work, exelix! Many hype Smash moments have been captured thanks to your patches

**Comment by NickPlayzGITHUB** [comment]
Does this work in 16.1.0??? I tried it out and I'm still getting 30fps capture via USB

**Comment by christopher317** [comment]
> Does this work in 16.1.0??? I tried it out and I'm still getting 30fps capture via USB
> 
> Edit: I named the file wrong, but when I stream with USB I'm getting a lot of bitrate artifacts when I'm streaming via USB

you have to overclock your switch fairly significantly using a tool such as sysclk.
id recommend a cpu frequency of 1224mhz as a starting point.
gpu frequencies of 460mhz ( handheld ) and  816mhz ( docked ) appear to work well.

as for your first question, yes, it still works even in 17.0.0

**Comment by NickPlayzGITHUB** [comment]
> you have to overclock your switch fairly significantly using a tool such as sysclk.
> 
> as for your first question, yes, it still works even in 17.0.0, tho sysclk is buggy and much harder to setup.

damn that sucks. I got a new usb 3.0 cable and it seemed to lower the amount of glitches but they still pop of from time to time. but thanks for the help

**Comment by exelix11** [comment]
Note for people using this with sysdvr 6.0, you will probably have to enable "uncap streaming framerare" in the settings to have smooth 60 fps. I did not try it though.

**Comment by ozcan305** [comment]
hi zhubibaba, i created the folder name ''system_settings.ini'' and i paste the code but still im getting 30fps i tried with 3 verison one is latest version and one is 5.4 rightnow im using 5.5.6 what should i do ?

**Comment by Cyclizar** [comment]
> Note for people using this with sysdvr 6.0, you will probably have to enable "uncap streaming framerare" in the settings to have smooth 60 fps. I did not try it though.

I don't see this in sysdvr settings, any chance you could elaborate? @exelix11
on 6.1.1 btw

**Comment by exelix11** [comment]
On the client app, it's in the advanced settings at the bottom of the settings page.

To avoid needlessly updating the screen the client is optimized for 30fps, don't remember the exact logic rn. It's to save battery on mobile devices. In advanced settings you can opt out of all  the special logic.

**Comment by sergiovaldez96** [comment]
I'm trying to copy and paste the code to the system_settings file, I click save and it wants me to save it somewhere other than the switch, cant even find the switch files when prompted to find a save location. Why does it do that? Arent I supposed to edit the same file and save it in the same location its in? Ive tried 6 times and im losing my mind. Guess I'll have to buy a stupid dock then

**Comment by Kupie** [comment]
> I'm trying to copy and paste the code to the system_settings file, I click save and it wants me to save it somewhere other than the switch, cant even find the switch files when prompted to find a save location. Why does it do that? Arent I supposed to edit the same file and save it in the same location its in? Ive tried 6 times and im losing my mind. Guess I'll have to buy a stupid dock then

Here's more info on the file:

https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/configurations.md#system_settingsini

If you're having further issues, I'd google how to modify files on an SD card and show file extensions/what file extensions are in general.

**Comment by zhubibaba** [comment]
> I'm trying to copy and paste the code to the system_settings file, I click save and it wants me to save it somewhere other than the switch, cant even find the switch files when prompted to find a save location. Why does it do that? Arent I supposed to edit the same file and save it in the same location its in? Ive tried 6 times and im losing my mind. Guess I'll have to buy a stupid dock then

Reboot to hekate and use usb tools to transfer, or use a sdcard reader.

![Image](https://github.com/user-attachments/assets/db95775b-c90f-443a-80d7-a38d7d33665d)
