### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by supersatoshi** [exelix11/SysDVR#148]
**Describe the bug**
when I start “Taiko no Tastujin” and turn to the song select menu of rhythm game, the video would stoped.
but if you turn back to game's main menu or finish a rhythm game, the video would be continued when you are not in song select menu or playing rhythm game.

**To Reproduce**
turn in the song select menu and play rhythm game.

**Expected behavior**
all ok

**Setup information**
 - PC Win10x64
 - Custom firmware name and version SXOS v 3.0.5 EMUNAND
 - SysDVR version 5.1

**Comment by exelix11** [comment]
Sounds like the game is preventing recording of that section, you can confirm that by long pressing the capture button on your console when sysdvr stops working, if you get an error it means the game blocked recording.
If that's the case is not a sysdvr bug.
I'm looking into a system-wide solution for this.

**Comment by supersatoshi** [comment]
> Sounds like the game is preventing recording of that section, you can confirm that by long pressing the capture button on your console when sysdvr stops working, if you get an error it means the game blocked recording.
> If that's the case is not a sysdvr bug.
> I'm looking into a system-wide solution for this.

I've tried your suggesion, it seems that you are right. The problem was caused by the game itself not  from sysDVR. That’s a shame.
sysDVR is the only passble way to record video when used touch screen

Hope you can solve the problem :)
It would be the first one to achieve the desired effect XD
