### ISSUE TITLE
[Help] Net framework 5.0 64 doesn't work but 32 does (and it complains)

### ISSUE THREAD

**Issue by Cyrexia** [exelix11/SysDVR#149]
the 64bit version wont work as it does not see it but the 32bit version it sees and complains that it doesn't come with the certain libs [image_2021-08-03_185056](https://user-images.githubusercontent.com/88383565/128062520-88f5cb40-d27b-4ce9-be1b-7c98e1476fc2.png

**Comment by exelix11** [comment]
Edit the PATH environment variable on your pc  (google how to do it) and remove the `C:\Program files (x86)\dotnet` line. You should also see the ``C:\Program files\dotnet`  line, that's the 64 bit version, keep it there.

**Comment by Cyrexia** [comment]
that worked but then this was thrown in my face 
![image](https://user-images.githubusercontent.com/88383565/128064562-97d3de6a-ccaf-4142-9801-d9ffee7ed4bb.png)

**Comment by Cyrexia** [comment]
nevermind it was usb problems
