### ISSUE TITLE
Warning: Couldn't write data to device

### ISSUE THREAD

**Issue by Minozen** [exelix11/SysDVR#15]
Hey there. Fantastic program but USB isn't working. MPV or VLC via TCP won't work. I just get the error listed above. I have installed the driver as listed and I do have USB mode enabled.

**Comment by Minozen** [comment]
![aaaaa](https://user-images.githubusercontent.com/24974845/70394392-092f5400-19f5-11ea-859d-cc04c6fce8de.png)

**Comment by exelix11** [comment]
does normal `mpv` streaming work ? What is the command you're using to launch mpv ? 
Vlc is known to have issues because frame timestamps are not implemented yet

**Comment by Minozen** [comment]
Cheers for the quick response; MPV does not work.

**Comment by Minozen** [comment]
I am just USBStreamGUI and streaming to MPV, MPV in general works fine.

**Comment by exelix11** [comment]
Mh... then it sounds like it's some driver issue, could you try installing from the previous version of zadig ? An user on discord had a similar issue and solved like that.
Also try with a different usb cable.
If none of these work enable logging and post the log of the first few attempts, (it's usually long you may want to save it to a file and then upload somewhere like pastebin).

**Comment by Minozen** [comment]
@exelix11 Hey, tried a fresh cable and an older version of zadig. No luck. Here's the pastebin. https://pastebin.com/eHjK0u8K

**Comment by exelix11** [comment]
Mh... logs seem alright, looks like the console is not answering back. Are you in a game that supports video recording ? You can test by long-pressing the screenshot button.
For it to work you have to be in a game, applets like the home menu, album and so on are not supported.

**Comment by Minozen** [comment]
Yep, that worked. A lot of thanks to you for writing this program. Closing issue.
