### ISSUE TITLE
Cmd window closes after starting SysDVR

### ISSUE THREAD

**Issue by MolhodeSoja** [exelix11/SysDVR#155]
**Describe the bug**
For some reason when I start SysDVR the cmd "Initializes" then closes immediately

**To Reproduce**
Executing the SysDVR command line in cmd

**Expected behavior**
The video should start :/

**Setup information**
 - PC Os: Windows 10
 - Console firmware : 13.0
 - Custom firmware name and version : Atmosphere 1.1.1
 - SysDVR version : 5.1

**Additional context**
If I use the Client GUI it starts the video but with blank screen, so I tried to use the normal client with ip and port.

**Comment by exelix11** [comment]
Given that the GUI launches fine i just assume you're using a wrong command line or double clicking the exe. 
Run `SysDVR-client --help` in the cmd to see the command line usage.

About the white screen it usually means that you're not running a game or the game is not supported, to check if it is supported try if you can long press the capture button to record a video.
If it's not you can try using dvr-patches.
