### ISSUE TITLE
Error when install WinUSB on Zadig

### ISSUE THREAD

**Issue by WIGASTY** [exelix11/SysDVR#158]
i've got error notification when install driver :
"The driver installation failed."

i try to manually install on folder C:\Users\ username \usb_driver
then i've got notification :
"a certificate chain processed but terminated in a root which is not trusted by the trust provider"

sorry for my bad english

**Setup information**
 - PC Os: Win 11
 - Console firmware [13.1.0]
 - Custom firmware name and version [atmosphere 1.2.1]
 - SysDVR version [USB]

**Comment by exelix11** [comment]
This seems to be an issue with zadig, enable advanced mode and check the logs for specific error messages, you should search that in their [issue tracker](https://github.com/pbatard/libwdi/issues)

> i try to manually install on folder C:\Users\ username \usb_driver

I don't know about the manual installation processs so i can't help you with that.

**Comment by rubbean** [comment]
You can disable driver signitures on windows 11 by shift clicking restart and booting into advanced boot settings, go to start up options and press 7 for diable driver signitures, this also fixes tegraRCMgui
