### ISSUE TITLE
Not working with latest firmware (9.1.0)

### ISSUE THREAD

**Issue by paprika714** [exelix11/SysDVR#16]
I tried to use it on my switch with cfw on 9.1.0 but looks like it doesn't work.
The console gets stuck at boot logo (when Nintendo logo shows up) and you can't do anything else.
The console gets like bricked. I had to insert the micro SD to my computer and remove the files i copied before (yes, i have modified the folder inside atmosphere to "contents").

If I get the files on my other sd which has the firmware 9.0.1, everything boots up normally but the usb ID its not the correct one (still shows up 2000 instead of 3006, even after installing drivers with Zadig).

**Comment by exelix11** [comment]
Just tested and can confirm it works as expected on my 9.1.0 console.
Does the 9.1.0 switch have other sysmodules ? If so it could be a memory issue. Also make sure to be using latest atmosphere (0.10.1) and hekate (5.1.1) versions as they free some extra memory for sysmodules.
About usb you're supposed to install the drivers only after the 3006 device shows up, by default SysDVR launches in network mode, you have to use the config homebrew to enable USB mode, please read carefully the guide.

**Comment by paprika714** [comment]
Thank you really much for the answer, I solved the problem.
Actually I did have hekate 5.1.0 and didn't notice that a new versione came out in the last hours so I updated it and looks like that the console doesn't get stuck while booting anymore.

I also solved the issue with the usb ID, i had to switch in the configuration. Sorry I didn't read it properly.

Again, thank you so much.

**Comment by hunkh** [comment]
la identificación del usb no es la correcta (aún aparece 2000 en lugar de 3006, incluso después de instalar los controladores con Zadig).como resolver este problema
