### ISSUE TITLE
[Help] What Cable Should I get to remove lag

### ISSUE THREAD

**Issue by Brandon6565** [exelix11/SysDVR#160]
[To submit a request fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]
[Note that you can also ask for help on the discord server]

**Where do you get stuck ?**
[None, just lag]

**What's the error message you get ?**
[Lag]

**Setup information**
 - PC OS: [Windows 10 x64]
 - Console firmware [Latest]
 - Custom firmware name and version [Latest]
 - SysDVR version [USB]

**Additional context**
just need a cord that removes lag but can also keep the console charged when plugged in with the average 480 mbps cord the game lags and stutters and pauses, and the consoles battery drains, what recommended cord should I get to remove the problems that make gaming harder.

**Comment by zhubibaba** [comment]
blue
