### ISSUE TITLE
installed winusb on sysdvr audio to try usb did no work so tried to use wireless but now audio is not streaming

### ISSUE THREAD

**Issue by legofan123456** [exelix11/SysDVR#164]
i tried to install the drivers for a usb stream but i installed the audio one and then the other one dissapeared so i tried to use wireless mode and now there is no sound. would lik some help on how to uninstall this problem. tried to uninstall sysdvr, didn't work
thanks

**Comment by exelix11** [comment]
Try again the usb method, in some cases the second device may disappear cause behind it's a single physical device, unplugging and plugging back in the console should fix it. If zadig says the driver is installed streaming should work.

About network mode the usb driver is not related, probably it only connected to the video stream, it happens sometimes. Just try to connect again until it works.

You can uninstall the driver from device manager but it's probably not what you need.

**Comment by legofan123456** [comment]
Thanks sorry for asking again but how do I uninstall winusb from device manager and which device is it? Can't seem to find the right one
Thanks

**Comment by exelix11** [comment]
To uninstall it shows up in the device manager when you connect it, you can double click and uninstall from there.

About the other driver i think it automatically installed to both so if you try streaming again it should work, otherwise enable show hidden devices in zadig.
