### ISSUE TITLE
[Feature request] (better?) check for running sysmodule when launching homebrew

### ISSUE THREAD

**Issue by monstrosities** [exelix11/SysDVR#165]
Hello. I'm not sure exactly how it works currently but would you consider implementing an improved check to the config homebrew to see if the sysmodule is running? 

I'm using a sysmodule manager to run SysDVR when needed but from time to time I forget that I haven't the sysmodule and launch the homebrew, this puts the system into a locked state and even exiting with the home button causes some kind of further freeze followed by anything up to a full atmosphere crash depending on how you launched the homebrew, either by album or overriding game for example.

If it's possible to improve the check there and exit gracefully if the sysmodule isn't running that would be really nice. Thank you for the great tool!

**Comment by exelix11** [comment]
Iirc the last time i looked up how to do this it was supported only by atmoshpere so that's why i didn't implement it.
I don't know if in the meantime things changed but other cfws are not as relevant anymore so i might as well add it, will consider it for the next update.

**Comment by exelix11** [comment]
Turns out there's an hacky way that works to do this, i implemented it in [latest release](https://github.com/exelix11/SysDVR/releases/latest)

**Comment by HookedBehemoth** [comment]
Please just use the atmosphere extension. This is a horrible horrible hack and all the other CFWs are dead anyway.
