### ISSUE TITLE
[Help] Mac Terminal Error

### ISSUE THREAD

**Issue by ChrisMiliW** [exelix11/SysDVR#167]
**Where do you get stuck ?**
Stuck on setting up client MacOs Setup 4th step. I've checked the troubleshooting but I don't see an answer.

**What's the error message you get ?**
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-SysDVR-Client.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Setup information**
 - PC OS: MacOS
 - Console firmware: 13.2.1
 - Custom firmware name and version: Atmosphere 1.2.6
 - SysDVR version: 5.2

**Additional context**
The Error pops up after using the command: dotnet SysDVR-Client.dll --help

I've also already done the steps before 4.

**Comment by exelix11** [comment]
The terminal is opened in the wrong folder.

You're supposed to open the terminal in the folder where you extracted the sysdvr client zip, that is where the command can find the SysDVR-Client.dll file.

**Comment by ChrisMiliW** [comment]
Thanks

**Comment by exelix11** [comment]
post the exact error you get and the command you're trying to run.

**Comment by ChrisMiliW** [comment]
<img width="570" alt="Screen Shot 2022-02-04 at 6 40 59 PM" src="https://user-images.githubusercontent.com/83226288/152617477-400849b4-bb02-4ed2-b580-6272ae906bbc.png">

When trying to start using the USB command 'SysDVR-Client usb'

**Comment by exelix11** [comment]
On mac you have to type dotnet before every command, the right command is `dotnet SysDVR-Client.dll usb`
