### ISSUE TITLE
[Feature request] Ability to change window title

### ISSUE THREAD

**Issue by jakerman999** [exelix11/SysDVR#170]
**Is your feature request related to a problem? Please describe.**
I've been streaming my switch over discord (By manually adding SysDVR-Client  as a streamable game) and it's been working beautifully, but the title is always "SysDVR-Client [PID ####]"

**Describe the solution you'd like**
A command line option to override or add a string to the window title would allow me to have a more descriptive title for my streams.

**Describe alternatives you've considered**
Something dynamically fed from the console itself updating with the title that's being played would be awesome and smooth, but perhaps seems excessive?  Options while inside the player might also be interesting (E.g. context menu, system tray icon, etc.), but I don't know if that might impact the lightweight nature

**Additional context**
Is the process ID needed for casual usage?  Seems that might be better relegated to a debug setting, but I might be unaware of some context

**Comment by exelix11** [comment]
The PID is needed to differentiate multiple sysdvr instances, some people stream with obs multiple consoles at the same time and if they had the same title it would cause issues.

Anyway there have been several request for configurable window title so I guess I'll add it as a command line option.

No eta for next release though.

**Comment by exelix11** [comment]
This is now implemented in release 5.3
