### ISSUE TITLE
I want to capture 60fps with sysdvr.

### ISSUE THREAD

**Issue by sersutdubivsuhfdas** [exelix11/SysDVR#171]
I know there is a way to get to 60fps, but I don't know how.
Help me.

**Comment by exelix11** [comment]
60fps is not supported in sysdvr.
I have heard it's possible but I never tried it nor I'm interested in researching that.

**Comment by exelix11** [comment]
See #147

**Comment by sersutdubivsuhfdas** [comment]
Isn't it possible by changing some files? For example, an unofficial patch.

**Comment by sersutdubivsuhfdas** [comment]
https://www.youtube.com/watch?v=W1KKqzwkE4U
https://www.youtube.com/watch?v=Q7VgmTOdJys

The stats for these videos are 1280x720 @ 60, which is 60fps and 1280x720, so it's hard to imagine using a capture board, and I don't think there's any reason to lie in the title.

**Comment by exelix11** [comment]
Yes check out the link I just posted, that person claims it works.
I was just warning you that I did not try it so it may be broken by now.

**Comment by exelix11** [comment]
There's more info in #147 , that's all I have

**Comment by zhubibaba** [comment]
still works
