### ISSUE TITLE
how do i setup tcp bridging, i don't know how to setup my switch with it because i don't know which zip file and how to open the menu[Help]

### ISSUE THREAD

**Issue by hackNcode** [exelix11/SysDVR#172]
how :(

**Comment by ToxiClay** [comment]
I seriously don't know what you mean by "how."

Read the wiki; it tells you exactly what you need to do.

1. https://github.com/exelix11/SysDVR/wiki/Setting-up-SysDVR
2. https://github.com/exelix11/SysDVR/wiki/SysDVR-Client-setup
3. https://github.com/exelix11/SysDVR/wiki/Network-TCP-Bridge-mode

If you can't read and understand these directions, how exactly were you able to make an issue on the Github page?
