### ISSUE TITLE
HOS 13.2.1 support

### ISSUE THREAD

**Issue by doggie015** [exelix11/SysDVR#173]
I have tried using sysDVR on HOS 13.2.1/Atmosphère 1.2.6 and it doesn't seem to be streaming properly. It loads up just fine on the switch side, but attempting to stream via TCP bridge fails with connection refused, and USB streaming just hangs.

**Comment by exelix11** [comment]
Seems to be working just fine on latest firmware, I believe it's a problem on your end. Follow the guide carefully and if it still doesn't work maybe your configuration is messed up and you need to set up your sd from scratch.

**Comment by doggie015** [comment]
I had the wrong IP address on my config file. I had it down as 192.168.1.6 but the switch address has changed to 192.168.1.5 (DHCP, Y U do dis?). It works fine now.
