### ISSUE TITLE
[Feature request] 14.0.0 Support

### ISSUE THREAD

**Issue by hackNcode** [exelix11/SysDVR#174]
I Can't Use SysDVR On 14.0.0, It Never Displays The Gameplay

Add Some Patch For 14.0.0 Support Both For The Switch And PC

Maybe Make Some .pchtxt Patch Or Something, IDK.

**Comment by dic1911** [comment]
It's probably just dvr-patches need to be updated, SysDVR itself works just fine for me with Animal Crossing and RingFit Adventure.

**Comment by hackNcode** [comment]
> It's probably just dvr-patches need to be updated, SysDVR itself works just fine for me with Animal Crossing and RingFit Adventure.

Um, I Guess, Because I Can Take Pics In BOTW But Not Videos With DVR Patches

**Comment by dogty** [comment]
> > It's probably just dvr-patches need to be updated, SysDVR itself works just fine for me with Animal Crossing and RingFit Adventure.
> 
> Um, I Guess, Because I Can Take Pics In BOTW But Not Videos With DVR Patches

If you compile the project with the libnx that has the PR from scires with the 14.0.0 update it does work. I'm able to stream BOTW without a problem

**Comment by dic1911** [comment]
> > > It's probably just dvr-patches need to be updated, SysDVR itself works just fine for me with Animal Crossing and RingFit Adventure.
> > 
> > 
> > Um, I Guess, Because I Can Take Pics In BOTW But Not Videos With DVR Patches
> 
> If you compile the project with the libnx that has the PR from scires with the 14.0.0 update it does work. I'm able to stream BOTW without a problem

mind share your binaries?

**Comment by dogty** [comment]
Sure! No additional code was added I only rebuilt it from the PR branch
Give me an update and tell me if it works on your end.
[SysDVR_dogty.zip](https://github.com/exelix11/SysDVR/files/8393211/SysDVR_dogty.zip)

**Comment by dogty** [comment]
Well I used your last release and couldn't make it work in tcp bridge mode, only in usb

**Comment by dic1911** [comment]
> Sure! No additional code was added I only rebuilt it from the PR branch Give me an update and tell me if it works on your end. [SysDVR_dogty.zip](https://github.com/exelix11/SysDVR/files/8393211/SysDVR_dogty.zip)

Oops, sorry I didn't make it clear that I was actually asking for dvrpatches

**Comment by exelix11** [comment]
> Well I used your last release and couldn't make it work in tcp bridge mode, only in usb and was able to make it work with the compiled version

I tried running latest sysdvr release over tcpbridge and it worked fine, i think it was a fluke on your end cause doesn't seem to need recompiling.
Note that sysdvr every 10 seconds or so resets the socket because of a libnx bug with sleep mode, if you try to connect while that is happening connection will fail, trying again will work though.

I'm going to close this since sysdvr seems to work and i'm updating dvrpatches later today
