### ISSUE TITLE
[Feature request] Capture TriPlayer audio

### ISSUE THREAD

**Issue by falcorr** [exelix11/SysDVR#175]
**Is your feature request related to a problem? Please describe.**
Music playing and heard via TriPlayer on the console isn't captured by SysDVR.

**Describe the solution you'd like**
TriPlayer audio to be captured, or an option to do so. 

**Describe alternatives you've considered**
Feeling sad.

**Comment by exelix11** [comment]
SysDVR uses the system recording feature, if streaming doesn't work it's a problem of the application and not something i can address in SysDVR.

Now, i don't know how does TriPlayer work, If i remember correctly missing audio in grc recordings is a problem with homebrew built with old libnx versions, if you download a recent build of TriPlayer or compile it yourself with latest libnx it could work.

If that still doesn't work probably grc doesn't support recording whatever it does and there's nothing i can do about it.
