### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by cetub333** [exelix11/SysDVR#176]
![image](https://user-images.githubusercontent.com/40271601/163683928-0895f2ae-bbb5-4f80-89bd-76d3c9b95aaa.png)

I put all the drivers, and when everything is ready, it always gives me a blank screen. I was never able to get the app to work for me.

**Comment by cetub333** [comment]
![image](https://user-images.githubusercontent.com/40271601/163684000-d74f3d46-fd0f-4a69-b06f-82599cb2dddb.png)

**Comment by cetub333** [comment]
![image](https://user-images.githubusercontent.com/40271601/163684009-9aee67a4-3769-4978-999c-bea05f8eaa9f.png)

**Comment by cetub333** [comment]
![image](https://user-images.githubusercontent.com/40271601/163684035-433ed94a-392d-4cfd-8c91-8c16eefddbc4.png)
![image](https://user-images.githubusercontent.com/40271601/163684042-3dfdad3f-d935-4c61-b0c3-fd48c39c3988.png)

**Comment by cetub333** [comment]
I have already tried all the versions, patches and help, but still nothing.

**Comment by cetub333** [comment]
Configuration information

PC OS: [Windows 10 x64]
Console Firmware [14.1.0]
Custom firmware version and name [Atmosphere 1.3.1]
SysDVR Version [SysDVR 5.2]

**Comment by cetub333** [comment]
With some games it works for me, but for example with "Super Smash Bros. Ultimate" it doesn't.

**Comment by exelix11** [comment]
Not an issue. If some games work it means it's setup correctly.
Not all games can be streamed and when that's the case you get a white screen.

You can try [dvr-patches](https://github.com/exelix11/dvr-patches/) for smash bros, it fixes most not supported games except a few problematic ones but you need a compatible firmware.
