### ISSUE TITLE
SysDVR Client macOS DLL missing

### ISSUE THREAD

**Issue by Devnol** [exelix11/SysDVR#179]
**Where do you get stuck ?**
Running SysDVR Client on MacOS 

**What's the error message you get ?**
```
 dotnet SysDVR-Client.dll usb
SysDVR-Client - 5.2 by exelix
https://github.com/exelix11/SysDVR

System.DllNotFoundException: Unable to load shared library 'avcodec.58.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libavcodec.58.dylib, 0x0001): tried: 'libavcodec.58.dylib' (no such file), '/usr/local/lib/libavcodec.58.dylib' (no such file), '/usr/lib/libavcodec.58.dylib' (no such file), '/Users/pakou/Documents/Games/Switch/SwitchHaxx/SysDVR-Client/libavcodec.58.dylib' (no such file)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at FFmpeg.AutoGen.Native.NativeLibraryLoader.MapMac(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at FFmpeg.AutoGen.ffmpeg.avcodec_find_decoder(AVCodecID id)
   at SysDVR.Client.Player.Player.InitDecoder(Boolean hwAcc)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality, Boolean startFullScreen)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)
   ```

**Setup information**
 - PC OS: macOS

**Additional context**
It used to work before, now it suddenly stopped working. 
Installed Dotnet runtimes are:
```
Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
(only installed SDK is 3.1.10)

**Comment by exelix11** [comment]
The dotnet SDK is only for building apps you don't need it, runtime 6 is what you need.

Your problem is that you're supposed to install ffmpeg shared libs (called avcodec) with brew as explained in the guide.
Note that if you're on M1 mac you must use rosetta or the build from https://github.com/exelix11/SysDVR/issues/166 for the time being until i push it to release (this weekend probably)

**Comment by Devnol** [comment]
I am on an intel mac, I have ffmpeg installed. The problem is that it used to work before so I'm really confused

**Comment by Devnol** [comment]
Ok, I have figured out the problem. FFmpeg was updated and libavcodec was too, so sysdvr is looking for libavcodec.58.dylib while only 59 exists:
```
~/Downloads/SysDVR-Client$ ls /usr/local/lib/libavcodec.
libavcodec.59.18.100.dylib@  libavcodec.59.dylib@         libavcodec.a@                libavcodec.dylib@
```
There's a generic libavcodec.dylib which also points to ffmpeg:
```
![image](https://user-images.githubusercontent.com/58105634/166497492-fb34421e-90a9-4671-9663-f083d2f88cb7.png)
So a permanent solution here would probably be to build nx-dvr without specifying the version of libavcodec but I am not certain if that is even possible or how it affects the rest of the platforms.

**Comment by exelix11** [comment]
Yeah i don't know either cause the ffmpeg bindings i use are third party, i guess you just need to install version 58 or if you like living on the dangerous side symlink 59 to 58 and it should work.

**Comment by Devnol** [comment]
I installed ffmpeg@4 and it came with the right version, running `ln -s /usr/local/Cellar/ffmpeg@4/4.4.2/lib/libavcodec.58.dylib /usr/local/lib/` worked but I had to do the same with libavutil 56 as well.

**Comment by td0** [comment]
> I installed ffmpeg@4 and it came with the right version, running `ln -s /usr/local/Cellar/ffmpeg@4/4.4.2/lib/libavcodec.58.dylib /usr/local/lib/` worked but I had to do the same with libavutil 56 as well. The other solution is to just uninstall ffmpeg 5 altogether and stick with 4, which is probably easiest if you're not using ffmpeg for something else so you might wanna add that to your wiki (brew install ffmpeg@4 instead of just ffmpeg)

this solves the same problem for me. but then when all those dependencies error was gone, I got this error:
`Initialized SDL with metal renderer
dotnet(4805,0x10277c580) malloc: *** error for object 0x200000000: pointer being freed was not allocated
dotnet(4805,0x10277c580) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    4805 abort      dotnet SysDVR-Client.dll usb`

**Comment by td0** [comment]
sorry, how do I download the CI builds? Tried to look at this PR -> #188 but can't find the button to get the build from

**Comment by exelix11** [comment]
[Direct link](https://github.com/exelix11/SysDVR/suites/6799783625/artifacts/261114555) for latest artifact

**Comment by Devnol** [comment]
CI build artifacts are only visible to members of a repo, that link should work though.

**Comment by exelix11** [comment]
Afaik if you open the actions tab you should be able to see them as long as you're logged in

**Comment by Devnol** [comment]
oh yeah you're right, I was looking at the PR, not the CI run lol

**Comment by exelix11** [comment]
Since you're on M1 make sure you're using native arm dotnet and installed the native arm libraries, if you mix x64 rosetta libs with native ones it won't work.

If you're sure you have all arm libs try changing the DYLD_LIBRARY_PATH to point to them before running the dotnet command

**Comment by td0** [comment]
Now with [this build](https://github.com/exelix11/SysDVR/suites/6799783625/artifacts/261114555), I got this error:
```
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under ': The specified module could not be found.
```

I noticed that the latest ffmpeg from brew give me these:
```
➜ ll /opt/homebrew/Cellar/ffmpeg/5.0.1_2/lib                                                                            21:35
➜ ll /opt/homebrew/Cellar/ffmpeg/5.0.1_2/lib                                                                            21:35
total 78416
drwxr-xr-x  35 -  admin   1.1K Jun 10 21:35 ./
drwxr-xr-x  15 -  admin   480B Jun 10 21:35 ../
-rw-r--r--   1 -  admin   9.4M Jun 10 21:35 libavcodec.59.18.100.dylib
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavcodec.59.dylib@ -> libavcodec.59.18.100.dylib
-r--r--r--   1 -  admin    13M Apr  4 21:40 libavcodec.a
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavcodec.dylib@ -> libavcodec.59.18.100.dylib
-rw-r--r--   1 -  admin   202K Jun 10 21:35 libavdevice.59.4.100.dylib
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavdevice.59.dylib@ -> libavdevice.59.4.100.dylib
-r--r--r--   1 -  admin    91K Apr  4 21:40 libavdevice.a
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavdevice.dylib@ -> libavdevice.59.4.100.dylib
-rw-r--r--   1 -  admin   2.8M Jun 10 21:35 libavfilter.8.24.100.dylib
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavfilter.8.dylib@ -> libavfilter.8.24.100.dylib
-r--r--r--   1 -  admin   4.6M Apr  4 21:40 libavfilter.a
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libavfilter.dylib@ -> libavfilter.8.24.100.dylib
-r--r--r--   1 -  admin   2.1M Jun 10 21:35 libavformat.59.16.100.dylib
lrwxr-xr-x   1 -  admin    27B Apr  4 21:40 libavformat.59.dylib@ -> libavformat.59.16.100.dylib
-r--r--r--   1 -  admin   3.7M Apr  4 21:40 libavformat.a
lrwxr-xr-x   1 -  admin    27B Apr  4 21:40 libavformat.dylib@ -> libavformat.59.16.100.dylib
-r--r--r--   1 -  admin   478K Jun 10 21:35 libavutil.57.17.100.dylib
lrwxr-xr-x   1 -  admin    25B Apr  4 21:40 libavutil.57.dylib@ -> libavutil.57.17.100.dylib
-r--r--r--   1 -  admin   644K Apr  4 21:40 libavutil.a
lrwxr-xr-x   1 -  admin    25B Apr  4 21:40 libavutil.dylib@ -> libavutil.57.17.100.dylib
-rw-r--r--   1 -  admin    84K Jun 10 21:35 libpostproc.56.3.100.dylib
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libpostproc.56.dylib@ -> libpostproc.56.3.100.dylib
-r--r--r--   1 -  admin    31K Apr  4 21:40 libpostproc.a
lrwxr-xr-x   1 -  admin    26B Apr  4 21:40 libpostproc.dylib@ -> libpostproc.56.3.100.dylib
-r--r--r--   1 -  admin   119K Jun 10 21:35 libswresample.4.3.100.dylib
lrwxr-xr-x   1 -  admin    27B Apr  4 21:40 libswresample.4.dylib@ -> libswresample.4.3.100.dylib
-r--r--r--   1 -  admin   112K Apr  4 21:40 libswresample.a
lrwxr-xr-x   1 -  admin    27B Apr  4 21:40 libswresample.dylib@ -> libswresample.4.3.100.dylib
-r--r--r--   1 -  admin   492K Jun 10 21:35 libswscale.6.4.100.dylib
lrwxr-xr-x   1 -  admin    24B Apr  4 21:40 libswscale.6.dylib@ -> libswscale.6.4.100.dylib
-r--r--r--   1 -  admin   717K Apr  4 21:40 libswscale.a
lrwxr-xr-x   1 -  admin    24B Apr  4 21:40 libswscale.dylib@ -> libswscale.6.4.100.dylib
drwxr-xr-x  10 -  admin   320B Jun 10 21:35 pkgconfig/```

while the SysDVR was looking `avcodec.59 ` without specifying the directory. Now symlinking the libavcodec.59.18.100.dylib to /usr/local/lib/avcodec.59.dylib doesn't work anymore

**Comment by exelix11** [comment]
The name should be `/usr/local/lib/libavcodec.59.dylib`, that's how the string is formatted on macos by the  [ffmpeg bindings](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/master/FFmpeg.AutoGen/Native/LibraryLoader.cs#L30)

**Comment by exelix11** [comment]
You can also add the whole folder `/opt/homebrew/Cellar/ffmpeg/5.0.1_2/lib` to your dyld loader path

**Comment by td0** [comment]
@exelix11 it works now with #188 build.
- installed all the latest dependencies from brew (reinstalled the latest ffmpeg)
- set `export DYLD_LIBRARY_PATH=/usr/local/lib` in .zshrc
- symlinked (ffmpeg, sdl2, libusb)/lib/* files to /usr/local/lib
- disable macos SIP (I don't know if this help, but I did it just in case)

I have the SysDVR client window now, it works but so slow. the frame is updated every 3secs or so.
