### ISSUE TITLE
usb error

### ISSUE THREAD

**Issue by xczsonn** [exelix11/SysDVR#18]
libusb: error [enumerate_hcd_root_hub] program assertion failed - HCD 'PCI\VEN_1B21&DEV_2142&SUBSYS_7B581462&REV_00\4&1961E893&0&00E4' child not found
Device not found, did you configure the drivers properly ?

what is this?
i already installed driver.

**Comment by exelix11** [comment]
By default SysDVR boots to network mode, did you use the config app to set it to USB mode ?
When you installed the driver did you check that the device ID was correct ?
Also check if the "Nintendo switch" device is being detected in the device manager, if it's not it could also be a bad usb wire.

**Comment by xczsonn** [comment]
1. i changed
2. Correct.
3. detect 'nintendo seitch 'on zardig

**Comment by exelix11** [comment]
Everything seems fine, not sure about what could be the problem here.
Windows version ?
Anyway other than zadig check in the windows' device manager and check the id there as well just to be sure it's being detected by windows too.

**Comment by exelix11** [comment]
Closing this issue as inactive for a long time.
