### ISSUE TITLE
[Bug] SysDVR crashes on startup on linux

### ISSUE THREAD

**Issue by Parnassius** [exelix11/SysDVR#180]
**Describe the bug**
SysDVR 5.3 crashes on startup on linux

**To Reproduce**
Run `dotnet SysDVR-Client.dll bridge 192.168.x.y` or `dotnet SysDVR-Client.dll usb` (the output is the same):
```
SysDVR-Client - 5.3 by exelix
https://github.com/exelix11/SysDVR 

System.BadImageFormatException: Could not load file or assembly 'SysDVR.Client.Native, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'SysDVR.Client.Native, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null'
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)
```

**Expected behavior**
The builtin player shows up and the stream starts

**Setup information**
 - PC Os: openSUSE Tumbleweed
 - Console firmware 14.0.0
 - Custom firmware name and version Atmosphere 1.3.2
 - SysDVR version 5.3 full

**Additional context**
```
> dotnet --list-runtimes
Microsoft.NETCore.App 6.0.4 [/opt/dotnet/dotnet-runtime-6.0.4-linux-x64/shared/Microsoft.NETCore.App]
```

**Comment by exelix11** [comment]
It seems the .net 6 build system now copies that dll file in the root directory and not where linux expects it so it breaks, weird seems to work fine on windows and mac, will investigate it.

**Comment by exelix11** [comment]
I think that if you replace `lib/netstandard2.1/SysDVR.Client.Native.dll` with just `SysDVR.Client.Native.dll` in SysDVR-Client.deps.json it should work

**Comment by Parnassius** [comment]
I've just redownloaded the 7z file from the releases to start anew (I already tried to move some some files around and to fiddle with the .deps.json file), and this time the player seems to be starting correctly. I'll update the sysmodule on the console and then close this issue if everything is indeed working fine.

**Comment by Parnassius** [comment]
Well, everything seems to be working fine now, I'm not sure what happened before

Thanks and sorry for the noise
