### ISSUE TITLE
[Bug] 5.3 SysDVR USB-Only Crashing Console

### ISSUE THREAD

**Issue by 16BitWonder** [exelix11/SysDVR#181]
**Describe the bug**
On a clean install of Atmosphere v1.3.2 with HOS 13.2.1, the console will crash and reboot within 30 seconds using the 5.3 SysDVR USB-Only release binary.

**To Reproduce**
- Make a fresh installation of Atmosphere v1.3.2 on HOS 13.2.1
- Install the 5.3 SysDVR USB-Only release binary
- Boot the console either via Hekate's FSS0 option or Atmosphere's Fusee.
- Console will then crash and reboot within 30 seconds

**Expected behavior**
Expected behavior is that the console does not crash within 30 seconds when this sysmodule is installed.

**Setup information**
 - PC OS: Windows 10 x64
 - Console Firmware: 13.2.1
 - Custom Firmware: Atmosphere 1.3.2
 - SysDVR Version: 5.3 USB-Only

**Additional context**
Something of particular note is that the standard 5.3 SysDVR binary is not crashing the console.
It is _only_ the 5.3 USB-Only binary that is crashing my system.
Also these crashes are occurring without attempting to establish connection to the PC client; Simply having the sysmodule installed and not connected to my PC is eventually resulting in a crash.

I've attached the generated crash report.
[crash_report.zip](https://github.com/exelix11/SysDVR/files/8643681/crash_report.zip)

**Comment by exelix11** [comment]
Yeah it seems i forgot to update the usb mode only code after doing some changes for last update, can you try this build from actions: https://github.com/exelix11/SysDVR/actions/runs/2285944470

**Comment by 16BitWonder** [comment]
That new build works like a charm w/o crashing.
Thank you for looking into the issue 👍
