### ISSUE TITLE
SysDVR usb device not found on Arch Linux

### ISSUE THREAD

**Issue by Anti-Apple4life** [exelix11/SysDVR#182]
I have tried to run SysDVR on Arch Linux and was not able to use USB streaming. I can confirm that the device is setup and the USB drivers are installed. Is there anything I am doing wrong

```
lsusb | grep Nintendo
Bus 001 Device 020: ID reacted:redacted Nintendo Co., Ltd SysDVR (Nintendo Switch)
```
NOTE: I redacted the USB ID because I am just a paranoid person sometimes.
```
sudo find / -name libusb-1.0.so      
/usr/lib/libusb-1.0.so
```
```
pacman -Q | grep libusb
libusb 1.0.26-1
libusb-compat 0.1.7-1
libusbmuxd 2.0.2-1
```

**Comment by exelix11** [comment]
Do you get an error when you try to stream or simply nothing shows up?

**Comment by Anti-Apple4life** [comment]
I get this error when I run `dotnet DLL usb`

Sent from my Android phone
________________________________

**Comment by exelix11** [comment]
That's not even launching the client, you're supposed to run `dotnet SysDVR-client.dll usb`

**Comment by Anti-Apple4life** [comment]
DLL is a placeholder

**Comment by exelix11** [comment]
There are multiple dll files so you should have been specific, besides you only said streaming doesn't work without telling what error you're getting.
If I had to guess you probably need to make an udev rule to allow sysdvr to access the console usb device without root.

**Comment by Anti-Apple4life** [comment]
I will test that out, thank you

**Comment by Anti-Apple4life** [comment]
![image](https://user-images.githubusercontent.com/59315931/168496057-2dd5f942-f4ec-4a11-a196-c0bf5aa52bab.png)

**Comment by Anti-Apple4life** [comment]
I also used `print-stats` and got the error `Invalid source`

**Comment by exelix11** [comment]
Invalid source means it failed to parse the command line.
If you run verbatim `dotnet SysDVR-client.dll usb` does it work ?

**Comment by Polyfish0** [comment]
> dotnet SysDVR-client.dll usb

Well because the old reporter didn't answer, and I have the same problem, I will answer.
Nope, it did not work.

**Comment by giopalma** [comment]
Sorry if I open the issue. I have the same issue in Arch. TCP mode works fine but not USB.
```
lsusb | grep Nintendo
Bus 001 Device 035: ID 057e:3006 Nintendo Co., Ltd SysDVR (Nintendo Switch)
```

```
sudo find / -name libusb-1.0.so
sudo find / -name libusb-1.0.so
```

```
pacman -Q | grep libusb
libusb 1.0.26-2
libusbmuxd 2.0.2-1
```

```
dotnet SysDVR-Client.dll usb

SysDVR-Client - SysDVR 5.4 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
ERROR: SysDVR usb device not found.
Make sure that SysDVR is running in usb mode on your console and that you installed the correct driver.
```

**Comment by giopalma** [comment]
With root I have this error
```
Initializing video player with h264 codec.
System.Exception: Assertion failed: -1 ALSA: Couldn't open audio device: Host is down
   at SysDVR.Client.Player.Exten.Assert(Int32 code, Func`1 MessageFun)
   at SysDVR.Client.Player.Player.InitSDLAudio(AudioStreamTarget target)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
```

**Comment by exelix11** [comment]
Yes this is an usual linux issue: without root you can't access usb devices but with root the audio server won't work. You need to change the usb permissions to work without root, this is usually done with an udev rule, google how to do it.

**Comment by giopalma** [comment]
Issue resolved
I followed this
https://wiki.archlinux.org/title/udev#Allowing_regular_users_to_use_devices
