### ISSUE TITLE
[Bug] [Need confirm] SysDVR make hbmenu black screen.

### ISSUE THREAD

**Issue by zyazhb** [exelix11/SysDVR#183]
**Describe the bug**
Meet black screen, after i start any game ,then open hbmeneu.

**To Reproduce**
1.open any game .
2.open hbmenu.
3.hbmenu is black screen (BUT when i push home button for a while, the overlay works well.)
4.the only way to get rid of this is force reboot.

**Expected behavior**
hbmenu start normally.

**Setup information**
 - 14.1.1
 - Atmosphere 13.2
 - SysDVR 5.3
 
**Additional context**
After I stop autoboot for sysdvr, the blackscreen never comes.
This behaviour is much easier to reproduce after use sysdvr client.

**Comment by exelix11** [comment]
Do you have other sysmodules alongside sysdvr? Multiple at the same time could cause the system to run out of memory and have this behavior.

**Comment by zyazhb** [comment]
> Do you have other sysmodules alongside sysdvr? Multiple at the same time could cause the system to run out of memory and have this behavior.

TNX for information, I have ldn_mitm and saltynx installed. But after disable these autoboot , still meet this issue with probability, is there a possible memory leak?

**Comment by exelix11** [comment]
sysmodules can't leak system memory cause their max heap size is statically defined, in case of a memory leak it would just fatal.
I don't know why you encounter this behavior but it's definitely not normal. Can you try just sysdvr without other sysmodules ? Also do you use dvr-patches ?

**Comment by zyazhb** [comment]
Even when only use SysDVR, still meet this issue. I have uninstalled sysdvr now, maybe have a try after a while. Very tnx for info, i'm going to close this issue.
