### ISSUE TITLE
[Bug] error:Wrong version of .NET

### ISSUE THREAD

**Issue by Black-water-side** [exelix11/SysDVR#184]
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'SysDVR-Client' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [2.2.300] from [*******/global.json] was not found.
      Install the [2.2.300] .NET SDK or update [*******global.json] with an installed .NET SDK:
        6.0.300 [/usr/local/share/dotnet/sdk]

**Comment by exelix11** [comment]
What OS ? What command are you running ? Post the output of  `dotnet --info`

**Comment by Black-water-side** [comment]
Sorry, I forgot to mention the system model, and it took me a long time to reply, it's MacOS(M1).

**Comment by Black-water-side** [comment]
> 什么操作系统？您正在运行什么命令？发布输出`dotnet --info`

use 'donet'

**Comment by exelix11** [comment]
I don't understand that last message. I think you have an old version of dotnet installed, download latest from microsoft https://dotnet.microsoft.com/en-us/download

**Comment by Black-water-side** [comment]
> 我不明白最后一条信息。我认为您安装了旧版本的dotnet，请从微软下载最新版本 https://dotnet.microsoft.com/en-us/download

OK
