### ISSUE TITLE
SDL2 Error

### ISSUE THREAD

**Issue by MilGreat2010** [exelix11/SysDVR#185]
I installed and followed the guide, but it all still says this: 
`System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/milanwiesenekker/Downloads/net6/libSDL2' (no such file)
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at SysDVR.Client.Player.Player..ctor(PlayerManager owner, Boolean hwAcc, String codecName, String scaleQuality)
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.InnerMain(String[] args)
   at SysDVR.Client.Program.Main(String[] args)`
   Can anyone help, I am on an Apple Silicon.

**Comment by MilGreat2010** [comment]
> install brew and use it to install SDL2 and ffmpeg

I did, but i copied some dylib files and it is working, not? it just throws a segmentation error now

**Comment by MilGreat2010** [comment]
<img width="548" alt="Schermafbeelding 2022-05-16 om 17 49 47" src="https://user-images.githubusercontent.com/57262078/168633029-245e43af-ea5c-499e-8e5f-0ee76d2cde25.png">

**Comment by exelix11** [comment]
That is a development build, you're not supposed to use it. Download a release build from the releases page https://github.com/exelix11/SysDVR/releases/tag/v5.3

**Comment by MilGreat2010** [comment]
> try `brew install libusb`

well nope, it said it was already installed, and i did `brew reinstall libusb` and it didnt work, same problem
I'm on M1 btw

**Comment by exelix11** [comment]
M1 should be supported see #166 but as i don't have one i can't guide you through installing every dependency, maybe installing `libusb-compat` from the other thread helps ?

**Comment by MilGreat2010** [comment]
> M1 should be supported see #166 but as i don't have one i can't guide you through installing every dependency, maybe installing `libusb-compat` from the other thread helps ?

Well i reinstalled that one, same problem

**Comment by MilGreat2010** [comment]
also i used this dev build when you said not to use https://github.com/exelix11/SysDVR/files/8547686/net6.0.zip

**Comment by MilGreat2010** [comment]
IT WORKEDDDD

**Comment by MilGreat2010** [comment]
idk what i did, but it works

**Comment by MilGreat2010** [comment]
https://drive.google.com/file/d/10NJKCC8yVc7wU65kwEI4C94KbJxDDr9g/view?usp=sharing

**Comment by MilGreat2010** [comment]
this worked for me, so i hope it works for anyone else
