### ISSUE TITLE
Erro: Failed to connect to SysDVR, is the module set up properly?

### ISSUE THREAD

**Issue by rao403** [exelix11/SysDVR#19]
Since I've started trying to get this program to work, I've been getting this error. I renamed the titles folder to contents before copying to the root, I deleted all other boot2 flags so that SysDVR is the only module that loads, I've waited for over a minute before checking the settings app. Unless I'm missing something, I'm out of ideas. Please help!

**Comment by exelix11** [comment]
For newer atmosphere (>= 0.10) now you have to rename the `titles` folder in the release to `contents`, deleting stuff already there is bad, download a clean copy of atmosphere.

**Comment by rao403** [comment]
I just reinstalled atmosphere, now it loads fine. Thanks for the help!
