### ISSUE TITLE
LibUsbDotNet.LibUsb.UsbException: Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by KeparYTbcc** [exelix11/SysDVR#190]
![image](https://user-images.githubusercontent.com/67996155/176325284-77ed0d8c-ff69-44d4-817f-2bda4973929b.png)

**Comment by exelix11** [comment]
Possibly wrong driver installed ? If you used an old sysdvr version you may have installed libusb but now I moved to winusb and that can happen.
just reinstall following the [guide](https://github.com/exelix11/SysDVR/wiki/USB-Driver)
