### ISSUE TITLE
Warning: Couldn't communicate with the console (Timeout). Try entering a game, unplugging your console or restarting SysDVR.

### ISSUE THREAD

**Issue by TXPH** [exelix11/SysDVR#191]
AMS IS 1.3.2
Switch Firmware is 14.1.1

**Comment by exelix11** [comment]
SysDVR  only works while a game is running. 
Some games are not compatible, you can try using [dvr-patches](https://github.com/exelix11/dvr-patches/) to force them which works on most but not all games.

**Comment by TXPH** [comment]
But I picked a few games and they all failed
