### ISSUE TITLE
Client cant find .NET 6 even if reinstalled

### ISSUE THREAD

**Issue by skarton94** [exelix11/SysDVR#197]
Reinstalled .NET 6 core, runtime and SDK. Also lastest VS. Restarted PC
Run as admin, and as windows 8 compat mode too
And cmd still shows this

![image](https://user-images.githubusercontent.com/19968302/185914607-813da3a5-f376-4995-8dd5-b2a14182019e.png)

**Comment by skarton94** [comment]
fixed it like so
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

but now i encounter white screen when trying TCP
![image](https://user-images.githubusercontent.com/19968302/185919318-40007de5-5407-4dc2-a758-c8db3967eeae.png)

**Comment by exelix11** [comment]
The solution you found is indeed the correct one.

About TCP that means either the ip address you typed is wrong or sysdvr is not in tcp mode on your console.

**Comment by skarton94** [comment]
ip was fine. turns out if pc is over cable, console must too. but it worked with both on wifi
thanks for the response
hope feedback helps

**Comment by exelix11** [comment]
I think it just means your router assigns different ips when you use lan vs wifi, but glad it works.
