### ISSUE TITLE
Games that don't typically allow video capture work...?

### ISSUE THREAD

**Issue by qrstuvv** [exelix11/SysDVR#198]
**Describe the bug**
So I use atmosphere cfw, and I'm not sure if this is very known (sorry if it is and this is redundant) but atmosphere removes that lock on video capture and sysdvr is now working on my switch and pc with Smash Bros. Ultimate

**To Reproduce**
I'm not sure what the key part that makes it happen is but i'm fairly certain that it's atmosphere making it happen, but just to be thorough, I use TegraRCMGUI 2.6 to load hekate ctcaer 5.7.2 onto my switch and i am on sys mmc

**Expected behavior**
I guess I expected it to not work, but with the knowledge that atmosphere removes that lock i tried and it works

**Setup information**
 - PC Os: Windows 11 x64
 - Console firmware 14.1.2
 - Custom firmware name and version Atmosphere 1.3.2
 - SysDVR version 5.3.1 Usb-Only

**Additional context**
Not really a problem at all, but I wanted to show some light on this

https://user-images.githubusercontent.com/107291750/186771915-0d5e9129-e453-49c8-a446-7ef35757db80.mov

**Comment by exelix11** [comment]
Pretty sure that's just [dvr-patches](https://github.com/exelix11/dvr-patches/), still developed by me.
It's not included in sysdvr cause it breaks a few games like the witcher iirc, if you don't remember downloading it you probably got it with some unofficial cfw pack.
