### ISSUE TITLE
Error with USB GUI

### ISSUE THREAD

**Issue by neelr** [exelix11/SysDVR#20]
The error is
```
Unhandled exception. System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at UsbStream.StdInTarget..ctor(String path, String args)
   at UsbStream.Program.<Main>g__ParseTargetArgs|3_0(Int32 baseIndex, IOutTarget& t, <>c__DisplayClass3_0& )
   at UsbStream.Program.Main(String[] args)
```

I have zadig drivers installed and followed the instructions. I also ran in admin mode and it didnt work. This is x64 Windows 10

**Comment by Ajaxklipp** [comment]
I had the same issue you have to export as batch then edit to the mvp location add .com at the end

**Comment by hax4dazy** [comment]
make sure you've got a .exe and a .com file in there named both mpv

**Comment by Danker1990** [comment]
Can you explain how you export as i have this very same error.

**Comment by neelr** [comment]
Just use USBGUI and select the configuration, then select `export` and it should download a `.bat ` file. After that all you need to do is open it in Notepad and edit it to run mpv.com not mpv (There is no mpv file). Then run the .bat file

**Comment by Danker1990** [comment]
Thanks neelr. You should get someone to put that in the FAQ section of the readme. Wasn't made as clear.

**Comment by exelix11** [comment]
Interesting, if you don't specify the extension windows usually selects the com file automatically, guess doesn't work for everyone (?) will add this to the common issues and fix in the next update, will leave the issue open till then.

**Comment by exelix11** [comment]
SysDVR V3 is out now and fixes this issue.
