### ISSUE TITLE
[Feature request] Update Client GUI to a 'modern' .net version

### ISSUE THREAD

**Issue by DacoTaco** [exelix11/SysDVR#200]
The client GUI uses the old .net project layout and target .net 4.5.1 which has been deprecated ages ago. 

i suggest you at least convert the project file to a sdk project file so things like nuget packages aren't saved in the source directory, but in the user directory (so there are no duplicates on the hard drive and all the other advantages).
this would also remove the weird nuget package build that needs to be moved manually ( which i have no idea why that is done?)

on top of that, i recommend updating to at least .net core 3.1 (which is LTS)..

it shouldn't be a lot of work normally, provided the code isn't super special.

**Comment by exelix11** [comment]
I use old dotnet on purpose cause it's already installed on windows. Less technical users get a proper message about installing modern .Net when opening the gui.

Will consider moving the gui to modern dotnet once (if ever) ms starts bundling it on fresh windows installs.

Custom nuget packages are needed for the .net 6 project as nuget is the only way to get msbuild to copy native dll files and generate the dependency jsons that allow directly finding bundled native dlls in a platform agnostic way.

**Comment by DacoTaco** [comment]
windows 10 comes with *at least* 4.6, not 4.5.1. 
but i understand.

i would in that case suggest to port the .csproj to an SDK csproj (just like the rest of the project) and target 4.6.

also, it is not true about the nuget package thing. the project is shared in the same solution. you can link a project without having the rely on internal nuget packages and on build it will just copy the files to output (and intilisense will also know what the code is referring to). this is just how project dependencies work in .net/visual studio...

**Comment by exelix11** [comment]
> i would in that case suggest to port the .csproj to an SDK csproj (just like the rest of the project) and target 4.6.

Yeah i guess that's something i could do.

> EDIT: also, i just realized your idea is wrong. the Client uses .net6, its just the UI that uses .net 4. so anyone using the client needs .net 6 to be installed...

The GUI checks that the correct .NET version is installed for the client and propmts to open the download page if it's not the case. Which is what most windows users will need.

> also, it is not true about the nuget package thing. the project is shared in the same solution. you can link a project without having the rely on internal nuget packages and on build it will just copy the files to output (and intilisense will also know what the code is referring to). this is just how project dependencies work in .net/visual studio...

With native dependencies i mean stuff like SDL2.dll or libusb.dll, if i add those just as resources they will be copied but `[DllImport("SDL2")]` won't find them unless i specify the full path, which i don't want to do cause it's supposed to be cross platform.
When there are nuget packages that carry native dependencies somehow msbuild generates .deps.json files that the runtime uses to override the dll name and identify the right path depending on the current platform.
I tried really hard to find an alternative way and couldn't manage to do it, maybe things changed with the .net6 release but the current method still works so it's good enough for me.

**Comment by DacoTaco** [comment]
ok so, i made all the changes that i believe makes the code *a lot* better and does not alter any features what so ever, that includes changing the csproj to an sdk project type.

> The GUI checks that the correct .NET version is installed for the client and propmts to open the download page if it's not the case. Which is what most windows users will need.

verified. still, the version used is outdated. on a new win10 VM i had 4.6.2 at least. that said, there is a way to make a self contained .exe in .net that has the runtime parts that it needs included in it. i've never done it before, so i don't know the pros and cons of it, but you might want to look into it. 

>With native dependencies i mean stuff like SDL2.dll or libusb.dll, if i add those just as resources they will be copied but [DllImport("SDL2")] won't find them unless i specify the full path, which i don't want to do cause it's supposed to be cross platform.
When there are nuget packages that carry native dependencies somehow msbuild generates .deps.json files that the runtime uses to override the dll name and identify the right path depending on the current platform.
I tried really hard to find an alternative way and couldn't manage to do it, maybe things changed with the .net6 release but the current method still works so it's good enough for me.

this... has a lot to process. first off all, the nuget package was completely unnecessary. you could have made it part of the dll project so that any dependency that needed it would have copied them over. and even then, you didn't need to do the DllImport of SDL2 at all, there are nuget packages that do this for you, and include the dll's, and work just fine. 
that said, once i fixed that i didn't need the native project to begin with as it was just a wrapper around SDL2 and included the FFmpeg dll's that your bat copied manually. (i used a submodule that only got the binaries folder of FFmpeg.AutoGen's repo)
so i removed all the projects in the Libs directory, added the needed nuget packages to the client project, and added a folder for the ffmpeg & that driver tool and kabang, everything worked fine, even on a fresh install windows 10.

you made it overcomplex and were patching bad code with bad patches, once you redo it like i did you start to notice it can be done so much easier/better/portable

**Comment by exelix11** [comment]
> there is a way to make a self contained .exe in .net starting with .net core that has the runtime parts that it needs included in it. i've never done it before, so i don't know the pros and cons of it, but you might want to look into it.

There is but it basically bundles the whole runtime with the exe making a 80MB+ package, later they added assembly trimming which supposedly mitigates this but i did not try it.  Also the release would be specific to the OS you build it for.

> you made it overcomplex and were patching bad code with bad patches, once you redo it like i did you start to notice it can be done so much easier/better/portable

I swear at some point it made sense, When i started this more than 2 years ago SysDvr-Client.deps.json needed to contain the dll paths of ffmpeg for dotnet to find them, it stopped being relevant just recently when i added several workarounds to address all the macos issues, I did not realize this and didn't bother to check.
So it's fine now, what i'm trying to say is that i'm not crazy: If you build your fork even with dlls from CI and compare that file with one from release you'll see they're not there,

Anyway go ahead and open a PR to the `refactor` branch i just created , there are a few things to address mostly the paths in the CI build script and some deprecation warnings from newer ffmpeg but i can handle that on my own, Also will have to ask someone on macos to test just to be safe.

**Comment by DacoTaco** [comment]
ye, the macos bit i can't test (unless i can create a VM with macos installed). 
as for the dll's, i assume at one point you had to do it (though it could've been done by a copy command in the csproj), as i needed to do with the ffmpeg dll's (because ffmpeg.autogen does not include the libraries...)

**Comment by exelix11** [comment]
Finally got around to release the changes, thanks for the help.
