### ISSUE TITLE
DevilutionX support

### ISSUE THREAD

**Issue by DarrenWarrenV** [exelix11/SysDVR#204]
Is there any way to add support for DevilutionX (Diablo)?

**Comment by exelix11** [comment]
That seems to be homebrew. You can stream homebrew by launching them using title takeover by pressing R while launching a compatible game.

**Comment by DarrenWarrenV** [comment]
That's actually true, it works like that! Thing is that I made a forwarder and it doesn't work this way unfortunately. Anyway, thank you!

**Comment by exelix11** [comment]
Nsp forwarders cause several issues and are generally not supported by the community, they should be avoided.
