### ISSUE TITLE
[Bug] Switch stream very laggy and glitchy

### ISSUE THREAD

**Issue by monadosorin** [exelix11/SysDVR#205]
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**
[When trying to stream, the video comes up but it's extremely laggy and extremely glitchy as well. I've never had this issue on my old laptop, ever since i switched to my new one, i could never get it working. all of my devices except my laptop are the same so i presume my system and or laptop is the problem. i'm using usb streaming, my internet is not fast enough for network streaming. Also the serial number that shows up on the cmd window isn't the correct serial number as well]
**To Reproduce**
[This happen each time i try to stream]

**Expected behavior**
[I'm completely lost on what to do, i've tried everything and countless troubleshooting]

**Setup information**
 - PC Os: [Windows 11 x64]
 - Console firmware [e.g. 14.1.2]
 - Custom firmware name and version [e.g. Atmosphere 1.3.2]
 - SysDVR version [5.2]

**Additional context**
[Initializing video player with h264 codec.
Connecting to the console with serial xaw00000000000...
Starting stream, close the player window to stop.
Press F11 for full screen, esc to quit.

[Video] Len: 7492 Bytes - ts: 16466579033
[Audio] Len: 8192 Bytes - ts: 16466615331
Initialized SDL with direct3d renderer
Warning: winusb error Timeout while reading header
Warning: winusb error Timeout while reading header
[Video] Len: 7220 Bytes - ts: 16468812346
[Audio] Len: 8192 Bytes - ts: 16468855331
Warning: winusb error Timeout while reading header
Warning: winusb error Timeout while reading header
[Video] Len: 6651 Bytes - ts: 16471045700
[Audio] Len: 8192 Bytes - ts: 16471095331
Warning: winusb error Timeout while reading header
Warning: winusb error Timeout while reading header
[Video] Len: 7633 Bytes - ts: 16473279043
[Audio] Len: 8192 Bytes - ts: 16473335331
Warning: winusb error Timeout while reading header
Warning: winusb error Timeout while reading header
[Video] Len: 6269 Bytes - ts: 16475512370
[Audio] Len: 8192 Bytes - ts: 16475575331
Warning: winusb error Timeout while reading header
Warning: winusb error Timeout while reading header]

**Comment by exelix11** [comment]
You have an old sysdvr version on your console, at some point i changed the protocol to improve performances and when you mix versions this happens.

Update sysdvr on your console and reboot, also ensure you have latest sysdvr client on your pc

**Comment by monadosorin** [comment]
Alright it works now, i swear i always updated the client and the console version at the same time but oh well thank you so much for your help
