### ISSUE TITLE
[Feature request]  Screen off like dock mode

### ISSUE THREAD

**Issue by aftil** [exelix11/SysDVR#209]
Can we turn off the nintendo switch screen like in dock mode when using the sysdvr with usb?
I think it can save battery power. Thank you for the great apps

**Comment by diguifi** [comment]
I'm not very much into how SysDVR works, but if I had to guess, I would say it just consumes video data from the console, but doesn't actually inputs anything to it. What this would mean is that, there's no way SysDVR could control screen status whatsoever.  
_(I might be completely wrong tho, just tipping my 5 cents to the issue)_

**Comment by DarrenWarrenV** [comment]
You can use https://github.com/averne/Fizeau for that. Turn everything down and set it as your first sysmodule in Tesla. You will have to remember how many button presses there are, but it works flawlessly.
