### ISSUE TITLE
usb --rtsp mode broken

### ISSUE THREAD

**Issue by BaJIeHTuHbI4** [exelix11/SysDVR#211]
**Describe the bug**
When I try to use this mode video stutter every 2 seconds

Tried on Wind 10 and Linux (Ubuntu/Manjaro) with any player (mpv, mplayer, vlc) with any parameters (--profile=low-latency --no-cache --cache-secs=0 --demuxer-readahead-secs=0 --cache-pause=no --untimed)

But! 
usb mode with internal player  working without troubles (software decoding)
usb --mpv mpv.com working without troubles (and without sound)
usb --file write file without stutters
rtsp and brige over wi-fi working without troubles (and with latency)

**To Reproduce**
run with usb --rtsp
open url in any player

**Expected behavior**
Playing without stutters

**Setup information**
 - Windows 10 x64 / Ubuntu 22.10 / Manjaro latest
 - Console Switch Lite
 - Console firmware 15.0.1
 - Custom firmware name and version  Atmosphere 1.4.0
 - SysDVR version 5.3.1/5.3.0/56b0b5f build

**Additional context**
Also tried different cables and usb ports (and PC)

**Comment by exelix11** [comment]
Can confirm this behavior, will look into it.
Any clue when it started happening ?

**Comment by exelix11** [comment]
Should be fixed in the CI builds for https://github.com/exelix11/SysDVR/pull/212 can you confirm ?
I'm planning to make a release tomorrow.

**Comment by BaJIeHTuHbI4** [comment]
Yes, now its fixed. No stutters. 
But very big latency, much more then rtsp from switch over Wi-Fi.


Also driver installer broken in Windows
![image](https://user-images.githubusercontent.com/12709108/208289816-613fa013-d3ec-476f-939d-a5bc01bc10e2.png)
Same version showed in command line (5.3.1)
![image](https://user-images.githubusercontent.com/12709108/208289830-1547fa3c-e920-4288-9a8a-d654aefd1d9a.png)

**Comment by exelix11** [comment]
Good catch, fixed.

**Comment by exelix11** [comment]
Release is now up
