### ISSUE TITLE
Tony Hawk's Pro Skater 1+2

### ISSUE THREAD

**Issue by DarrenWarrenV** [exelix11/SysDVR#214]
Game doesn't work with SysDVR at all, there's no video/sound. Are there some things that I can try out?

**Comment by exelix11** [comment]
Some games are expected to not work, there's a separate project to fix them. You can give it a try: https://github.com/exelix11/dvr-patches

If still doesn't work open an issue there, I'll mark it as help wanted and you can hope someone tries to add support for it.
