### ISSUE TITLE
[Help]MAC上咋整啊，没法玩啊

### ISSUE THREAD

**Issue by tangyuxian** [exelix11/SysDVR#217]
咋整啊，现在执行就报下面的错误，愁死我了
`tangyuxian@bogon SysDVR-Client % dotnet SysDVR-Client.dll usb
Couldn't find a library to symlink: libusb-1.0 (libusb-1.0.dylib). You might need to install it with brew.
SysDVR-Client - SysDVR 5.4 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /usr/local/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
tangyuxian@bogon SysDVR-Client % 
`
可是我libusb已经装了啊，怎么就这个错误啊，咋整啊，我现在都愁上火了，能不能给MAC做个客户端啊

**Comment by exelix11** [comment]
There are multiple errors, first off if you haven't already install ffmpeg `brew install ffmpeg` then launch sysdvr but add `--libdir $(brew --prefix)/lib/` at the end of the command and see if it works.

If it doesn't work answer the following 

M1 or intel mac ?
Can you post the output of `brew --prefix` ?

Search for libusb and avcodec dylib files in the brew install folder, do you find them ?

**Comment by tangyuxian** [comment]
`tangyuxian@bogon SysDVR-Client % brew --prefix
/opt/homebrew
tangyuxian@bogon SysDVR-Client % `
输出后是这样的。。
我的是M2的macbook，大佬救救我，哭了 T-T

**Comment by tangyuxian** [comment]
这么执行对吗 brew install ffmpeg--libdir /opt/homebrew/lib/
brew install libusb --libdir /opt/homebrew/lib/

**Comment by exelix11** [comment]
Use only `brew install ffmpeg` without libdir, libdir is a sysdvr option

**Comment by tangyuxian** [comment]
```
tangyuxian@bogon SysDVR-Client % brew install ffmpeg
Warning: ffmpeg 5.1.2_3 is already installed and up-to-date.
To reinstall 5.1.2_3, run:
  brew reinstall ffmpeg
tangyuxian@bogon SysDVR-Client % 
```
是这样式儿的的嘛，这个代表装好了对吧

**Comment by exelix11** [comment]
Yes, it is installed.

Try the same for `brew install libusb` and `brew install SDL2`

After that you have to find where brew installed them, for example what is thr output if you run `brew --prefix libusb`

Unfortunately I don't use MacOS so can't help much, the problem is that sysdvr can't find the library files.

The first step for us is to find them ourselves so we can link them manually.

**Comment by tangyuxian** [comment]
tangyuxian@bogon SysDVR-Client % brew --prefix libusb
/opt/homebrew/opt/libusb
tangyuxian@bogon SysDVR-Client % brew --prefix SDL2  
/opt/homebrew/opt/SDL2
tangyuxian@bogon SysDVR-Client % 
应该都已经装好了，但是路径不对是嘛

**Comment by exelix11** [comment]
The path seems correct.

Wait i have a question, did you install native arm dotnet or the intel version ? If you run dotnet with rosetta it will not work.

**Comment by tangyuxian** [comment]
.net默认是x64，气哭了，重新安装了arm的.net，可是，可是
tangyuxian@bogon ~ % donet
zsh: command not found: donet
tangyuxian@bogon ~ % 
没有了，这回它找不到.net了，但是我在/usr/local/share/dotnet/dotnet看到它了，咋回事啊

**Comment by exelix11** [comment]
You typed donet, the command is `dotnet`

**Comment by tangyuxian** [comment]
啊这。。。。尴尬了。。。。
Initializing video player with h264 codec.
ERROR: SysDVR usb device not found.
Make sure that SysDVR is running in usb mode on your console and that you installed the correct driver.
MAC上真是一步一个坎啊，这咋了这，我把switch插在macbook上，结果发现给macbook充电了，这。。。

**Comment by tangyuxian** [comment]
switch插在window11上没有问题，可以USB游玩。但是插在macOS上就不行了。所以switch游戏机上的配置应该没问题，可是macbook应该配置的没啥问题了吧

**Comment by exelix11** [comment]
Are you using an usb c to c cable ?
That is known to cause problems, if you use an usb A to C with the A side to the Mac should work.

**Comment by tangyuxian** [comment]
还有这事儿？艾玛，我刚刚赶紧把转接口拿出来，成了，谢谢大佬，爱你么么哒😘解决啦

**Comment by exelix11** [comment]
👍
