### ISSUE TITLE
Streaming wont launch due to fatal error

### ISSUE THREAD

**Issue by CommicKick69ing** [exelix11/SysDVR#22]
<img width="737" alt="Capture" src="https://user-images.githubusercontent.com/40266764/72198055-9f8cd600-33f6-11ea-96f9-ea49a6d3bf02.PNG">

**Comment by exelix11** [comment]
Looks like you didn't install net core 3.
Get latest .net core runtime from here: https://dotnet.microsoft.com/download

**Comment by CommicKick69ing** [comment]
I did but I will donwload it again

**Comment by CommicKick69ing** [comment]
A new error
<img width="733" alt="Capture2" src="https://user-images.githubusercontent.com/40266764/72211208-5049b280-3495-11ea-9741-18e20caf7083.PNG">

**Comment by exelix11** [comment]
Seems that it can't launch mpv, access denied could mean a lot of stuff, if you just double click on mpv does it work? Also if you're using GUI check if this helps https://github.com/exelix11/SysDVR/issues/20 
guess you could also try launching as admin but I often recommend against that

**Comment by CommicKick69ing** [comment]
Yes mpv works. And whats GUI check?

**Comment by exelix11** [comment]
Meant if you're using UsbStreamGUI try if the solution explained [here](https://github.com/exelix11/SysDVR/issues/20#issuecomment-571844303) helps

**Comment by CommicKick69ing** [comment]
Another nother error
<img width="735" alt="Capture23" src="https://user-images.githubusercontent.com/40266764/72222104-2e047300-352f-11ea-94de-37383d77a586.PNG">

**Comment by exelix11** [comment]
Did you install the usb driver and properly setup sysdvr ? There's a problem with usb but the screenshot doesn't give a lot of info.
Make sure to be running a game compatible with remote capture.
Note that other sysmodules and homebrews that use usb such as nxmtp could cause issues.

**Comment by CommicKick69ing** [comment]
Yes. And I dont think there is a problem with the usb since I use it to inject payloads to my switch. And what games are compadtible. And I dont use nxmtp

**Comment by exelix11** [comment]
> And I dont think there is a problem with the usb since 
SysDVR uses a different custom driver, you should have followed the zadig first setup guide.
A game is compatible if you can longpress the capture button to record a video.
Be sure to be already running a game when you start streaming

**Comment by CommicKick69ing** [comment]
I did the zadig. I will start the game before streaming

**Comment by CommicKick69ing** [comment]
I it works now I just followed your suggestion opening the game before streaming
