### ISSUE TITLE
White Screen when using TCP docked

### ISSUE THREAD

**Issue by oxyinthedark** [exelix11/SysDVR#220]
Bug Description
When trying to use the TCP Bridge method while the Switch is docked, the GUI player will show a white screen

To Reproduce
Use the TCP Bridge method of SysDVR while your Switch is docked

Expected behavior
The player will display the game, as it does when using handheld TCP 

 - PC Os: [Windows 11 x64]
 - Console firmware [15.0.0]
 - Custom firmware name and version [Atmosphere 1.4.1]
 - SysDVR version [5.4]

Additional context
Have been trying to troubleshoot this, doing the exact same things to no avail. It simply just shows a white screen when using SysDVR while docked

**Comment by exelix11** [comment]
This makes little sense since there's no different handling of docked/handled in sysdvr.
Does it happen with every game ? are you using dvr-patches ? Do you have a lan adapter connected to the dock or sysmodules that mess with internet connectivity ?

**Comment by oxyinthedark** [comment]
> 

I've been trying to play Botw (dvr patches installed) No LAN adaptor connect, but do have an 8BitDo BT controller dongle. Not sure about the Sysmodules

**Comment by exelix11** [comment]
Can you try rebooting the console and then with different games ? botw should be supported even without patches
