### ISSUE TITLE
[Feature request] Native quick-save feature

### ISSUE THREAD

**Issue by inbartlett** [exelix11/SysDVR#223]
While the switch offers a quick-save feature for videos using the capture button, these videos are only saved on the switch and one has to extract them from the sd card.

I'd like to see the client have a keybind or something for saving footage to some local file, similar to the native feature. 

At the least, I'd like to have a file made for the entire session so that I could find the section myself. I understand trying to write to a file while streaming would cause some delay, so I reckon that it could be done on cleanup for a full VOD. For the quick-save, I think the user would just have to accept that some lag will be present upon generating one.

**Comment by exelix11** [comment]
This is not a feature i'm particulairly interested in.
My main goal with this project is getting a low latency stream and given the way the code is structured i don't see an immediate way of implementing it.
In the end all kinds of recording and processing operations are better when done by specialized software: by capturing the screen with OBS it will use your GPU to encode the video and likely produce smaller files than when saved directly from switch/sysdvr.

**Comment by OniriCorpe** [comment]
@inbartlett maybe you should be interested by this: [sys-screenuploader](https://github.com/bakatrouble/sys-screenuploader)
it uploads the screenshots and videos to a telegram or discord channel of your choice
