### ISSUE TITLE
[streaming stops working]

### ISSUE THREAD

**Issue by NikosApikos** [exelix11/SysDVR#226]
I was using the older version and worked great in USB mode with 60 fps. I updated both client and switch app and now for some reason in mid game the client stops streaming and I need to relaunch it.

**Comment by Nazgile94** [comment]
+1
Same 
16.0.1 latest Atmos
Switch OLED

**Comment by exelix11** [comment]
Does the same happen without 60fps ? Do you get any specific error ?

**Comment by exelix11** [comment]
Try 30 fps and let me know if that happens, helps to pinpoint the root cause.

**Comment by Nazgile94** [comment]
30fps Wireless with Client botw freeze (Sound Still works)

**Comment by exelix11** [comment]
Your seems to be a different issue since it's over network, do you get any errors on the pc ?

**Comment by exelix11** [comment]
This is now fixed in latest release

**Comment by Nazgile94** [comment]
Works !!! Ty for this fix :)
