### ISSUE TITLE
[Bug] rstp stream not working over the internet (open port)

### ISSUE THREAD

**Issue by ANTONIOPSD** [exelix11/SysDVR#227]
**Describe the bug**
rtsp stream does not work over the internet

**To Reproduce**
Download any rtsp player like VLC, open the rtsp stream with your public IP and the open port from a non local address like data connection 3g/4g/5g etc

**Expected behavior**
VLC should be able to open te stream over the internet with the correct forwarded port

**Setup information**
 - Os: Android 12
 - Console firmware: 16.0.1
 - Custom firmware name and version: Atmosphere 1.5.2
 - SysDVR version: 5.5

**Additional context**
Nothing.

**Comment by exelix11** [comment]
Let me start by saying that exposing stuff over the internet is generally a bad idea and you should consider using a VPN such as wireguard or zerotier (NOT the commercial youtube ad VPN kind)

Are you talking about the rtsp stream provided by sysdvr on the console itself or the one from sysdvr-client ?

standalone sysdvr should just work since it listens on 0.0.0.0 by default.
For sysdvr-client you need to add the `--rtsp-any-addr` option to the command line, this will enable accepting connections from any network interface.

Consider that rtsp is composed of multiple connections, once the client and the server agreed on a streaming mode they may switch over UDP and this may not work over the internet due to NAT and firewalls.
Rtsp also supports in-band tcp streaming and that should work, however sysdvr does not implement a full rtsp compliant server so it may fail to negotiate the protocol. There's a lot that could go wrong and you'll have to do some debugging on your end.

**Comment by ANTONIOPSD** [comment]
Don't worry, I work as a sys admin, I just wanted to share my switch screen with a friend that has low IT knowledge so the only way of viewing it is by using a simple rtsp video player on his android phone.

My switch has a static local IP so it never changes on the local network and of course  the video streaming works without problem buth with a 2 seconds lag, but it's ok. I  opened the 6666 TCP port on my router for my switch IP and it can be reached over the internet but the streaming fails to open.
I tested the connection with one of the FTP server homebrews and they work over internet with no problem.

Port forwarding works, so it must be something else.

**Comment by ANTONIOPSD** [comment]
Something to do with this?:

![Screenshot_20230419_234246_Chrome](https://user-images.githubusercontent.com/1978099/233206905-b096dd87-db0c-44ae-94a5-c4ae39daa2fa.jpg)

**Comment by exelix11** [comment]
Iirc udp ports are random and chosen by the client.

I'd say start by trying to stream to a pc, android makes any kind of debugging ten times as hard.

Use mpv as a client and try --rtsp-transport=tcp to force tcp over the internet, maybe it works.

If that doesn't i fear you'll have to fire up wireshark. On sysdvr side there's nothing blocking over the internet connections aside potential rtsp negotiation bugs, but I'm not reading the spec again.

**Comment by exelix11** [comment]
> Something to do with this?:
> 
> ![Screenshot_20230419_234246_Chrome](https://user-images.githubusercontent.com/1978099/233206905-b096dd87-db0c-44ae-94a5-c4ae39daa2fa.jpg)
> 
> 

This is sysdvr client, I think you meant you're streaming from the console itself, in that case all the code is in the C sysmodule and you don't need sysdvr-client at all.
Either way that flag is set by the command line arg I'm mentioned in the first reply

**Comment by ANTONIOPSD** [comment]
> > Something to do with this?:
> > ![Screenshot_20230419_234246_Chrome](https://user-images.githubusercontent.com/1978099/233206905-b096dd87-db0c-44ae-94a5-c4ae39daa2fa.jpg)
> 
> This is sysdvr client, I think you meant you're streaming from the console itself, in that case all the code is in the C sysmodule and you don't need sysdvr-client at all. Either way that flag is set by the command line arg I'm mentioned in the first reply

Ohh true true I just didn't see the "Client" folder and only read the "server" word in the file name😅

I'm going to test it from VLC in one of the computer in my workplace

**Comment by exelix11** [comment]
A follow up on this, with the usual premise this is a very bad idea and you should avoid doing it.

Streaming over the internet seems to be working for me with the following setup: 
- My home connection is a normal residential connection with a dedicated IPv4 (open nat or whatever you call it)
- I forwareded port 6666 of my switch in the router
- I installed [mpv for android](https://play.google.com/store/apps/details?id=is.xyz.mpv) on my phone, the phone is connected to the internet over 4g which is behind CG-NAT
- Clicking "open url" and typing `rtsp://public ip address:6666/` starts streaming as expected

I also tested vlc on a pc and seemed to work altough the stream was lagging. At this point i believe it's an issue on your end either with port forwarding or your ISP nats you preventing to accept connections. I'm closing this.
