### ISSUE TITLE
MPV won't open on wireless

### ISSUE THREAD

**Issue by N3V3RDIE1** [exelix11/SysDVR#23]
I did everything and still can't get mpv to open once ran in cmd I load into a game and nothing happings (On PC)

**Comment by exelix11** [comment]
Could you provide some more info ? Is the game compatible ? Usb or wifi ? if usb did you install the driver ? Do you get some error ?
Have you tried reading the other closed issues ? Other people had similar issues, you may find a solution there.

**Comment by N3V3RDIE1** [comment]
Yes I tried to record the game for 30 secs and it worked, Wifi, no error that I could see it says mpv tcp://192.168.1.137:5000 --no-correct-pts --fps=30 and then closes after a couple of mins

**Comment by exelix11** [comment]
SysDVR doesn't stream on port 5000, it's 6666 for video and 6667 for audio

**Comment by N3V3RDIE1** [comment]
that what port on nintendo switch says is they anyway to change it

**Comment by N3V3RDIE1** [comment]
got it working thanks
