### ISSUE TITLE
[Help] with Macbook 16inch 2021

### ISSUE THREAD

**Issue by nguyentungvna** [exelix11/SysDVR#230]
[To submit a request fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]
[Note that you can also ask for help on the discord server]

**Where do you get stuck ?**
[when i'm using command dotnet /Users/admin/Downloads/SysDVR-Client\ 3/SysDVR-Client.dll  usb  ]

**What's the error message you get ?**
[Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
]

**Setup information**
 - PC OS: [MacOs Ventura 13.3.1]
 - Console firmware [16.0.2]
 - Custom firmware name and version [ Atmosphere ]
 - SysDVR version [5.5]

**Additional context**

**Comment by exelix11** [comment]
Arn or Intel model ?
Post the full message you see on the terminal.

**Comment by nguyentungvna** [comment]
I'm using ARM version

admin@tung-coi84 ~ % dotnet /Users/admin/Downloads/SysDVR-Client\ 3/SysDVR-Client.dll  usb
You're using the intel version of dotnet on an arm mac, this is not supported and will likely not work.
Delete intel dotnet and install the native arm64 one.
SysDVR-Client - SysDVR 5.5.5 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/
If you're using an arm based mac make sure you're using native arm dotnet and not the intel one.

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)

**Comment by exelix11** [comment]
> You're using the intel version of dotnet on an arm mac, this is not supported and will likely not work.
> Delete intel dotnet and install the native arm64 one.

The problem is written there, uninstall dotnet and install the native arm version from Microsoft's site

**Comment by nguyentungvna** [comment]
Even i deleted dotnet in /usr/local/share and install ARM64 on Microsoft website . Message still unchanged :(

**Comment by exelix11** [comment]
I can't provide assistance with mac os, as long as you see that message it means sysdvr is running inside rosetta and that is not supported.

Properly uninstall dotnet or just as a workaround fix your path environment variable to point to the native one.

**Comment by nguyentungvna** [comment]
Thanks alot for your help

**Comment by blueCommunity** [comment]
I also met this problem in my m1 macbook air, could you solve it?

**Comment by blueCommunity** [comment]
> I also met this problem in my m1 macbook air, could you solve it?

and I can ensure my dotnet is run in arm environment 


/usr/local/share/dotnet/dotnet: Mach-O 64-bit executable arm64

**Comment by c01dc0ffee** [comment]
Run `whereis libavcodec.so.59` and post the result. Should be like `libavcodec.so: /opt/homebrew/lib/libavcodec.so.59`

**Comment by blueCommunity** [comment]
> whereis libavcodec.so.59

libavcodec.so.59:
it's not exist

**Comment by c01dc0ffee** [comment]
Try what I wrote here: https://gist.github.com/c01dc0ffee/8acbd11bbd4b5c18ba4c5de288deb423

**Comment by exelix11** [comment]
An update on this: there's a bug in architecture detection and will cause the message to be shown when it's not needed, will fix it later today.
For the time being read the troubleshooting steps in the previous message

**Comment by exelix11** [comment]
I updated the release build with the CI build from [here](https://github.com/exelix11/SysDVR/actions/runs/4893651048) this should fix the message being wrongly shown.

**Comment by nguyentungvna** [comment]
> Try what I wrote here: https://gist.github.com/c01dc0ffee/8acbd11bbd4b5c18ba4c5de288deb423

admin@tung-coi84 ~ % find /opt/homebrew -name "libavcodec.*.dylib"
/opt/homebrew/lib/libavcodec.60.3.100.dylib
/opt/homebrew/lib/libavcodec.60.dylib
/opt/homebrew/Cellar/ffmpeg/6.0/lib/libavcodec.60.3.100.dylib
/opt/homebrew/Cellar/ffmpeg/6.0/lib/libavcodec.60.dylib
/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.37.100.dylib
/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.dylib

Hello there . Could you please show me what should i do next

**Comment by c01dc0ffee** [comment]
You need to add `/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib` to your PATH environment variable. Follow the link in the next step of the guide. Edit `~/.zshrc` instead of `~/.bash_profile`
