### ISSUE TITLE
[Help] with Macbook with M1 (ARM64)

### ISSUE THREAD

**Issue by Alecfut07** [exelix11/SysDVR#232]
[To submit a request fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]
[Note that you can also ask for help on the discord server]

**Where do you get stuck ?**
[when i'm using command dotnet SysDVR-Client.dll usb ]

**What's the error message you get ?**
[Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)]

**Setup information**
 - PC OS: [MacBook Pro (16-inch, 2021)]
 - Console firmware [16.0.2]
 - Custom firmware name and version [Atmosphere 1.5.2]
 - SysDVR version [5.5]

**Additional context**
Using dotnet --info: 
-  .NET SKD: 7.0.203
- OS Name: Mac OS X
- OS Version: 12.6
- OS Platform: Darwin
- Architecture: arm64
- .NET SDKs installed: 7.0.203 [/usr/local/share/dotnet/sdk]

List of what I installed with brew:
- SDL2 version 2.26.5
- libusb version 1.0.26
- ffmpeg version 5.1.3

And I tried to put some export PATHs from .zshrc file:
- export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.37.100.dylib:$PATH"
- export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.dylib:$PATH"

**Comment by c01dc0ffee** [comment]
`export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib`

**Comment by Alecfut07** [comment]
> export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib:$PATH"

I put it and in the .zshrc file and refresh terminal, but it didn't work  :(

**Comment by c01dc0ffee** [comment]
Possibly related: https://stackoverflow.com/a/15882090
If that doesn't fix it, try `source ~/.zshrc` before running SysDVR.
If that doesn't work, try `export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib:$PATH"` before running SysDVR.

**Comment by Alecfut07** [comment]
> Possibly related: https://stackoverflow.com/a/15882090 If that doesn't fix it, try `source ~/.zshrc` before running SysDVR. If that doesn't work, try `export PATH="/opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib:$PATH"` before running SysDVR.

I've tried with those possibles solutions, but none of them, didn't work :(

**Comment by Alecfut07** [comment]
The solution for me, I need to run this commands:
- cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.37.100.dylib /opt/homebrew/lib

- cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.dylib /opt/homebrew/lib

- cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavutil.57.dylib /opt/homebrew/lib

- dotnet SysDVR-Client.dll USB

Thx to XeroShi, gigglypuff, Bizzy

**Comment by FrankJakob36** [comment]
when I try to run those commands I get this message cp: /usr/local/lib/John/.CFUserTextEncoding: Permission denied

**Comment by c01dc0ffee** [comment]
@FrankJakob36 `sudo cp` or copy them using the file explorer
