### ISSUE TITLE
No audio playback and video glitches when the window is resized on MacOS

### ISSUE THREAD

**Issue by c01dc0ffee** [exelix11/SysDVR#234]
**Describe the bug**
MacOS users with libSDL2 version 2.26.5 report no audio playback and visual glitches if they resize the player window.

**To Reproduce**
Set up a SysDVR stream on MacOS. All streaming modes and players appear to be affected.

**Expected behavior**
Game audio should playback as normal and the stream window should be resized without encountering visual artifacts at the frame borders.

**Setup information**
 - PC Os: MacOS, processor architecture independent
 - Console firmware: N/A
 - Custom firmware name and version: N/A
 - SysDVR version: N/A

**Additional context**
One user reported success with using [an unofficial build of mpv](https://github.com/jnozsc/mpv-nightly-build), presumably because it ships with `libSDL2-2.0.0.dylib`. Downgrading libSDL2 might fix this, but it's unclear if this is something that can be fixed in SysDVR. I can't find anything related to this in [the SDL issue tracker](https://github.com/libsdl-org/SDL/issues).

**Comment by exelix11** [comment]
I'd rather keep this open so it shows up on searches since discord messages tend to get lost

**Comment by kvn1351** [comment]
> There have been a few reports about htis on discord so it's somewheat known, my stance on this is:
> 
> * We don't know how many users are actually affected nor the total macos usersbase so it's hard to know the impact of this
> * We don't know if this is sysdvr-specific or an SDL bug
> * Since i don't have a mac (and i'm not getting one for this lol) the limited number of users make it hard to debug the issue
> 
> There is essentially nothing i can do about it since on other platforms it seems to work just fine. If someone affected by this wants to test they could try older versions of sysdvr to see if the problem persists, based on the result of that i can think of the next steps.
> 
> > One user reported success with using [an unofficial build of mpv](https://github.com/jnozsc/mpv-nightly-build), p
> 
> mpv and external video players are unrelated from sysdvr, i'll only be addressing issues related to the builtin player of sysdvr and possible encoding quirks. If stock mpv doesn't work on macos it's out of scope for me.

If you want I could prepare a VM (vmware, qemu or virtualbox) for you running macOS and all libs/deps so you'd just have to spin it up. That would save you lots of time.

I've tried with libSDL2-2.0.0 but that didn't do the trick either :/

**Comment by exelix11** [comment]
The notification reminded me, we have a fix for this now but it's coming with the next major update which will still take some time.

In the meantime I'll try to backport the fix to the current release

**Comment by kvn1351** [comment]
> The notification reminded me, we have a fix for this now but it's coming with the next major update which will still take some time.
> 
> In the meantime I'll try to backport the fix to the current release

Oh, that's great :)

Thanks a lot
