### ISSUE TITLE
SysDVR-Client crashes when streaming on Discord Canary

### ISSUE THREAD

**Issue by c01dc0ffee** [exelix11/SysDVR#235]
**Describe the bug**
I try to stream SysDVR-Client with Discord and SysDVR crashes instantly.

**To Reproduce**
Stream the SysDVR-Client stream window with Discord canary.

**Expected behavior**
The program runs normally

**Setup information**
 - PC Os: N/A
 - Console firmware: N/A
 - Custom firmware name and version: N/A
 - SysDVR version: N/A

**Additional context**
The crash results from an unspecified problem with Discord Canary. Most likely a change Discord has made with injected module. Switching to Discord Stable fixes the issue.

**Comment by exelix11** [comment]
I'd like if anyone affected by this could try https://github.com/exelix11/SysDVR/pull/236
It blocks dll injections from third party programs,. I have two concerns:
- May trigger some antiviruses cause its doing fancy memory stuff
- May break third party game-y thing integrations like nvidia geforce which i don't use so can't test

If discord fixes this i'll just discard the PR

**Comment by exelix11** [comment]
Update on the AV thing: from virustotal i see just two vendors flagging both [current release](https://www.virustotal.com/gui/file/2a0fc80044102e038b671ac361cb40cb3bf7299d0a485880f981875f42163a0f) and anti-injection [CI build](https://www.virustotal.com/gui/file/a5ebf30972afcb901451c3a302ee7786c4c02469be8f8df3d7afe523a316d9a6) so it did not get worse and it's fine (aside from those two crappy vendors)

**Comment by exelix11** [comment]
Thanks for letting me know, however it's on discord for crashing SDL2 applications for seemingly no reason. If this crash makes it into stable I'll just release an update with anti dll injection as I don't expect average users to figure this out.
