### ISSUE TITLE
[Feature request] Screen off when capturing/mirroring

### ISSUE THREAD

**Issue by kevsestrella** [exelix11/SysDVR#238]
**Is your feature request related to a problem? Please describe.**
Screen problem especially on lites where vertical or horizontal lines appear. This problem is not directly related to Sysdvr and is probably related to heat and usage, but the feature might help delay it and I think makes sense for Sysdvr when we're mirroring our display to larger screens, much like when you dock non lite models.

**Describe the solution you'd like**
A toggle option in homebrew app that activates/deactivates the screen off feature when mirroring. Also, when activated, screen turns back on when mirroring stops(either when media player app like mpv or built-in is closed or when user is at homescreen or joycon selection screen)

**Describe alternatives you've considered**
A standalone app might have been good for this to support use cases beyond sysdvr but I haven't found any. DBI installer have this feature for their app when installing games, probably to help delay screen burn.

**Comment by exelix11** [comment]
This has been requested several time, in practice i don't know of any OS API that allow to do this. I just did a quick search for screen on libnx and nothing relevant turned up, it he OS doesn't allow this there's nothing i can do about it.

Going with workaround routes one could make a tesla overlay that completely fills the screen with a dark image and set the brightness to minimum but i don't think it will have any particular effect on LCD models.

So unless someone figures out some undocumented API i don't think this will be possible in a clean way.

**Comment by kevsestrella** [comment]
Thanks for giving time and also for mentioning your research route on this topic. Since that is the case, I will close this now.
