### ISSUE TITLE
SafeHandle cannot be null.

### ISSUE THREAD

**Issue by mio-19** [exelix11/SysDVR#239]
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**

Getting `SafeHandle cannot be null.` error when running SysDVR in usb mode

**To Reproduce**

log:

```
dotnet SysDVR-Client.dll usb
SysDVR-Client - SysDVR 5.5.6 by exelix
https://github.com/exelix11/SysDVR 

Initializing video player with h264 codec.
Connecting to the console with serial xaw00000000000...
Starting stream, close the player window to stop.
Press F11 for full screen, esc to quit.

Initialized SDL with opengl renderer
USB warning: Couldn't communicate with the console (Timeout). Try entering a compatible game, unplugging your console or restarting it.
USB warning: Couldn't communicate with the console (NoDevice). Resetting the connection...
USB warning: Couldn't communicate with the console (SafeHandle cannot be null. (Parameter 'pHandle')). Resetting the connection...
```

**Expected behavior**

**Setup information**
 - PC Os: [e.g. Windows 10 x64] Debian sid arm64
 - Console firmware [e.g. 10.0.0]16.0.3
 - Custom firmware name and version [e.g. Atmosphere 0.12.0] Atmosphere 1.5.3
 - SysDVR version [e.g. 3.0 Usb-Only] 5.5.6

**Additional context**

**Comment by mio-19** [comment]
Oh. It means that the game is incompatible

**Comment by exelix11** [comment]
It shouldn't, this could be an actual bug

**Comment by exelix11** [comment]
I checked: it depends on libusb, on windows it means it could not connect to the console. In practice it's not an issue since it will just attemp to reconnect automatically once a compatible game is launched. 

Also you can use [dvr-patches](https://github.com/exelix11/dvr-patches) to stream incompatible games.
