### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shakyevan444** [exelix11/SysDVR#241]
**Describe the bug**
i get:

➜  SysDVR-Client(1) dotnet SysDVR-Client.dll bridge 192.168.1.20 --rtsp-port 9090
Couldn't find a library to symlink: libusb-1.0 (libusb-1.0.dylib). You might need to install it with brew.
SysDVR-Client - SysDVR 5.5.6 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/
If you're using an arm based mac make sure you're using native arm dotnet and not the intel one.

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
➜  SysDVR-Client(1) 

**To Reproduce**
i ran dotnet SysDVR-Client.dll bridge 192.168.1.20 --rtsp-port 9090

**Expected behavior**
Unsure tbh

**Setup information**
 - PC Os: macos
 - Console firmware NA
 - Custom firmware name and version NA
 - SysDVR version Newest at time of post

**Additional context**
on ARM m1 2020 mbp

**Comment by exelix11** [comment]
The error means you don't have ffmpeg libraries installed which are needed to use the built-in video player, the guide should explain how to fix this.

Why are you using `--rtsp-port 9090` ? Do you mean to stream over rtsp instead ?

**Comment by shakyevan444** [comment]
1: i did install ffmpeg

2: oops

**Comment by exelix11** [comment]
Unfortunately mac os is tricky to get working due to brew/third party libraries weirdness.

There is a second link in the guide with more troubleshooting steps specific to mac os but that's the best guidance i can give since I don't use the os myself.

**Comment by shakyevan444** [comment]
using usb it has 

Couldn't find a library to symlink: libusb-1.0 (libusb-1.0.dylib). You might need to install it with brew.

even when i have used brew install libusb

**Comment by exelix11** [comment]
Same as ffmpeg, possibly brew is not configured correctly on your end. Since you have an arm mac mace sure you are using the arm version of brew and not the intel one.

**Comment by crc-32** [comment]
Once you know you're on the arm version of brew, try `brew link --overwrite libusb`

**Comment by shakyevan444** [comment]
➜  SysDVR-Client(1)  brew link --overwrite libusb
Warning: Already linked: /usr/local/Cellar/libusb/1.0.26
To relink, run:
  brew unlink libusb && brew link libusb
➜  SysDVR-Client(1)

**Comment by shakyevan444** [comment]
➜  SysDVR-Client(1) dotnet SysDVR-Client.dll usb
Couldn't find a library to symlink: libusb-1.0 (libusb-1.0.dylib). You might need to install it with brew.
SysDVR-Client - SysDVR 5.5.6 by exelix
https://github.com/exelix11/SysDVR 

There was an error loading a dynamic library. Make sure you installed all the dependencies and that you have the correct version of the libraries.
If all libraries are properly installed ensure their path is set in your dynamic loader environment variable (PATH on Windows, LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on MacOS)

In case of problems specific to ffmpeg or libavcodec you can override the loader path by adding to the command line --libdir <library path> where <library path> is the folder containing the dyamic libraries of ffmpeg (or symlinks to them).
For example on MacOS you can try --libdir $(brew --prefix)/lib/
If you're using an arm based mac make sure you're using native arm dotnet and not the intel one.

Full error message:
System.DllNotFoundException: Unable to load DLL 'avcodec.59 under /opt/homebrew/lib/': The specified module could not be found.
   at FFmpeg.AutoGen.ffmpeg.LoadLibrary(String libraryName, Boolean throwException)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_0(String libraryName)
   at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__7_18()
   at FFmpeg.AutoGen.ffmpeg.av_packet_alloc()
   at SysDVR.Client.Player.H264StreamTarget..ctor()
   at SysDVR.Client.Player.PlayerManager..ctor(Boolean HasVideo, Boolean HasAudio, Boolean hwAcc, String codecName, String quality)
   at SysDVR.Client.Program.HandleStreamingCommands()
   at SysDVR.Client.Program.ProgramMain()
   at SysDVR.Client.Program.Main(String[] args)
➜  SysDVR-Client(1)

**Comment by crc-32** [comment]
looking at the full error, ensure `brew install ffmpeg@5` has been run then run `ln -s /opt/homebrew/opt/ffmpeg@5/lib /opt/homebrew/lib/`, and then use it with `--libdir $(brew --prefix)/lib/` option again

**Comment by shakyevan444** [comment]
ohhh ill try

**Comment by shakyevan444** [comment]
➜  SysDVR-Client(1) ln -s /opt/homebrew/opt/ffmpeg@5/lib /opt/homebrew/lib/ 
ln: /opt/homebrew/lib/: No such file or directory
➜  SysDVR-Client(1) ln -s /opt/homebrew/opt/ffmpeg@5/lib /opt/homebrew/lib/ --libdir $(brew --prefix)/lib/
ln: /usr/local/lib//lib: File exists
ln: /usr/local/lib//lib: File exists
ln: /usr/local/lib//--libdir: File exists
➜  SysDVR-Client(1)

**Comment by shakyevan444** [comment]
using wineskin and tcp works
