### ISSUE TITLE
Usb driver not available for Windows on arm

### ISSUE THREAD

**Issue by fansID512** [exelix11/SysDVR#242]
**Where do you get stuck ?**
Install the USB driver

**What's the error message you get ?**
When installing the driver, it prompts that the third-party INF does not contain digital signature information.

**Setup information**
- PC operating system: Windows11 arm64
- Console firmware: 5.5.6 (other versions also have this problem)

**Additional context**
The device is Mi Pad 5 with win11 installed. When using the sysdvr client, the wireless mode is not affected, but the usb wired mode cannot be used, because the usb driver installed in this client failed to install (the picture attachment has been submitted), It is said that the third-party INF does not contain digital signature information. It may be because the system has turned on the test mode, but this test mode cannot be turned off. If it is turned off, it will not be able to boot. Is there any good way to solve the problem of usb driver installation failure?

Error screenshot：
(https://github.com/exelix11/SysDVR/assets/103017881/b26e45bc-fc7b-4886-9add-6f29976b40a2)

**Comment by exelix11** [comment]
Try installing manually from https://developer.android.com/studio/run/win-usb does the same happen ?

**Comment by fansID512** [comment]
An error will also be reported, it is the same error. Arm64 cannot install this driver. Can I install an x64 driver? This arm64 version of Win11 can be translated into x64 applications. So theoretically, installing a normal x64 driver can run normally, without the need to specifically install arm64, as it cannot be installed either.

(https://github.com/exelix11/SysDVR/assets/103017881/5b6d895d-8244-4ba6-b21a-40ed4226038b)

**Comment by exelix11** [comment]
Oh i missed the part where you're running windows on arm.
This is quite the problem as it seems google does not distribute their driver for arm64. 
Drivers are special parts of the system and you can't install the x64 one.

Your only option could be installing a generic WinUsb driver with zadig but there's a catch: https://github.com/pbatard/libwdi/issues/289 it seems you will need to disable some security settings since drivers from zadig are unsigned.

For the time being i'd advice to just stick to network streaming.

**Comment by fansID512** [comment]
Okay, but just like another person's message, can we open up a software that can also use USB transmission on Android devices? This tablet is dual system and can use both Android and Windows systems. The reason for wanting USB is that it is relatively stable and smooth. Of course,network streaming media is also very cool to use.

**Comment by exelix11** [comment]
I don't do android dev so it's not something i can implement right now.
I did look into the possibility of porting the existing client but native code on android is still overly complicated.

If android support ever comes I'll announce it in the relevant issue.

**Comment by fansID512** [comment]
Hello, I found the arm64 adb and fastboot driver in the relevant Windows of Android group today. After testing, it can connect to the phone and read data normally. The relevant driver accessories have been uploaded.

[adb和fastboot驱动arm64(带教程).zip](https://github.com/exelix11/SysDVR/files/11902127/adb.fastboot.arm64.zip)

Success picture
(https://github.com/exelix11/SysDVR/assets/103017881/35433226-2a6f-49df-b3bb-5312f6839873)

**Comment by exelix11** [comment]
Does it work with sysdvr ? I'm looking into the inf file and don't see the relevant vid and pid so this specific driver may not be compatible.
 sysdvr uses VID_18D1&PID_4EE0
