### ISSUE TITLE
[Wiki] SysDVR Client setup MacOS

### ISSUE THREAD

**Issue by rrr2rrr** [exelix11/SysDVR#244]
Please, fix this part in **SysDVR Client setup**:

> Install ffmpeg brew install ffmpeg@5.1.2
> This command should work fine most of the times, if you encounter issues you can try to install ffmpeg from source, first uninstall it brew uninstall ffmpeg then run brew install ffmpeg@5.1.2 --build-from-source

In macOS you can't install `ffmpeg@5.1.2`, only `ffmpeg@5`. 

Also, in **Troubleshooting SysDVR on Linux and MacOS**:

> From the directory given by the previous command, copy these files into /opt/homebrew/lib: libavcodec.59.dylib libavcodec.59.37.100.dylib libavutil.57.dylib libavutil.57.28.100.dylib

add an example (that will works in 99% cases)
```
cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.dylib /opt/homebrew/lib/libavcodec.59.dylib
cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.37.100.dylib /opt/homebrew/lib/libavcodec.59.37.100.dylib
cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavutil.57.dylib /opt/homebrew/lib/libavutil.57.dylib
cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavutil.57.28.100.dylib /opt/homebrew/lib/libavutil.57.28.100.dylib
```

**Comment by exelix11** [comment]
Thanks i updated the install part of the guide.

> cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.dylib /opt/homebrew/lib/libavcodec.59.dylib
< cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavcodec.59.37.100.dylib /opt/homebrew/lib/libavcodec.59.37.100.dylib
> cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavutil.57.dylib /opt/homebrew/lib/libavutil.57.dylib
> cp /opt/homebrew/Cellar/ffmpeg@5/5.1.3/lib/libavutil.57.28.100.dylib /opt/homebrew/lib/libavutil.57.28.100.dylib

About this i'm not sure since i've seen brew using different folders depending on arch (intel vs arm), this is probably architecture specific

**Comment by rrr2rrr** [comment]
but maybe it can be useful to add example of copy command, especially for libavutil. 
It's not obvious, that you should copy all 4 files, when `find /opt/homebrew -name "libavcodec.*.dylib"` shows only 2 of them. Therefore code example is good.

Lets place a better prompt
```
cd "$( dirname "$(find /opt/homebrew -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"
cp libavcodec.59.dylib libavcodec.59.37.100.dylib libavutil.57.dylib libavutil.57.28.100.dylib /opt/homebrew/lib/
```

first - change dir to place, where libavcodec placed, but only with ffmpeg in path
second - copy 4 files one row command

**Comment by rrr2rrr** [comment]
And this for Intel users

```
cd "$( dirname "$(find /opt/homebrew -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"
cp libavcodec.59.dylib libavcodec.59.37.100.dylib libavutil.57.dylib libavutil.57.28.100.dylib /opt/local/lib/
```

**Comment by exelix11** [comment]
The brew can also change across architectures, can you check if replacing `find /opt/homebrew ` with  `find $(brew --prefix)` still works ? That should ensure the path is always correct.

About the paths `/opt/local/lib/` and `/opt/homebrew/lib/` idk, i'm going to have to trust you on this one.

Also  it's probably better to use symlinks rather than copying the files.

**Comment by rrr2rrr** [comment]
```
cd "$( dirname "$(find $(brew --prefix) -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"
sudo ln -s libavcodec.59.dylib "$(find $(brew --prefix) | head -1)/lib"
sudo ln -s libavcodec.59.37.100.dylib "$(find $(brew --prefix) | head -1)/lib"
sudo ln -s libavutil.57.dylib "$(find $(brew --prefix) | head -1)/lib"
sudo ln -s libavutil.57.28.100.dylib "$(find $(brew --prefix) | head -1)/lib"
```

**Comment by rrr2rrr** [comment]
cd "$(find $(brew --prefix) | head -1)/lib"
ln -s "$( dirname "$(find .. -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"/libavcodec.59.dylib libavcodec.59.dylib
ln -s "$( dirname "$(find .. -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"/libavcodec.59.37.100.dylib libavcodec.59.37.100.dylib
ln -s "$( dirname "$(find .. -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"/libavutil.57.dylib libavutil.57.dylib
ln -s "$( dirname "$(find .. -name "libavcodec.*.dylib" | grep ffmpeg | head -n 1)" )"/libavutil.57.28.100.dylib libavutil.57.28.100.dylib
cd ~
