### ISSUE TITLE
[Bug] Invalid source on MacBook Pro M1 Pro

### ISSUE THREAD

**Issue by YoruIchka** [exelix11/SysDVR#245]
**Describe the bug**
Can't Launch getting " invalid source"

**Setup information**
 - MacBook Pro M1 PRO 14" on Ventura 13.4.1 
 - Nintendo switch is at 15.0.0
 - I have the latest 6. ARM64 Dotnet SDK

**Comment by exelix11** [comment]
It mens you entered the wrong command line, follow the guide.

**Comment by YoruIchka** [comment]
> It means you entered the wrong command line, follow the guide.

sorry to bother , but is There a macOS Guide ? I can only see the windows one .
I followed with a video

**Comment by exelix11** [comment]
The wiki covers all the supported systems, most of the steps are the same since the client is cross platform.
