### ISSUE TITLE
Zadig driver install Issue

### ISSUE THREAD

**Issue by juliusb93** [exelix11/SysDVR#25]
Hello !
Just wanted to try your solution but i have some issues installing the libus driver...
I manage to find my switch with the correct USB ID the first time then I installed the good driver.
Since them, Zadig can't manage to recognize my switch (only find a USB ID 057E 2000)
Do you have any solution about that?
I tried to search online but I didn't found anything.

For info, when i plug my switch it's still recognised by windows (Win 10 64bit) but Zadig put 0 devices found

Thanks by advance

**Comment by exelix11** [comment]
If you don't see the right USB ID it means sysdvr isn't running or is in network mode, use SysDVR-Settings to switch to USB

**Comment by juliusb93** [comment]
Hey !
Thanks for your quick reply, had an issue with the full SysDVR, so i tried the usb only version (corrupted atmosphere on boot). I was just about to reinstall it on my SD card.
If it don't work i'll try again the full version

**Comment by juliusb93** [comment]
Meh, now i have another issue when trying to use the full version : Failed to connext to sysDVR (already tried to delete everithing and retry, and cleaned my atmosphere folder as well)

**Comment by exelix11** [comment]
Sounds like the sysmodule is not running at all, did you rename the titles folder in the releases to contents ? it was changed in latest atmosphere

**Comment by juliusb93** [comment]
Finally i managed to make all working.
Had to reinstall my atmosphere (took the last release, had a previous one) Now everything is working fine ! Thanks for your help ! (still a noob with the switch "hack" haha)
![- - mpv](https://user-images.githubusercontent.com/60541578/73592643-b48fed00-44fc-11ea-920c-e4e613589f3e.jpg)

**Comment by exelix11** [comment]
👍
