### ISSUE TITLE
Updated, now won't stream [Help]

### ISSUE THREAD

**Issue by CreamAbras** [exelix11/SysDVR#250]
I correctly type in my IP address on tcp bridge mode, only to get an error after 5 attempts.

Terminating ReceiveFromDeviceThread for Audio due to System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)
Terminating ReceiveFromDeviceThread for Video due to System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at SysDVR.Client.Sources.TCPBridgeSource.WaitForConnection()
   at SysDVR.Client.StreamThread.DeviceThreadMain(CancellationToken token)

**Setup information**
 - PC OS WIndows 12 x64
 - Console firmware 15.0.1
 - Custom firmware name and version Atmosphere 1.4.0
 - SysDVR version 5.5.6

**Comment by exelix11** [comment]
Not a bug.

Make sure you:
1) have the same sysmodule and client versions
2) if you just updated sysdvr reboot the console
3) there is not firewall blocking lan connections (eg public wifi)

**Comment by CreamAbras** [comment]
I did all that and still get nothing

**Comment by SignorUpB** [comment]
I am also getting this error after updating to the latest atmosphere version and switch firmware,I think that all ovlsysmodules stopped working

**Comment by MemerOnYT** [comment]
The new update of atmosphere is still in pre-release. Expect it to be complete sometime this week. And or 17.0.0 broke Sysdvr (unlikely)

**Comment by MemerOnYT** [comment]
Nvm Im dumb, you need to update the DVR patches, should be somewhere on github
