### ISSUE TITLE
SysDVR-Client (5.5.5) crashes upon boot 

### ISSUE THREAD

**Issue by gitgudscrubb** [exelix11/SysDVR#252]
Windows 10. 
Running the client, i get the basic usage text screen. I press enter and the program closes out. 
Had it working great in the past.
Upgraded to 5.5.6, no change.

**Comment by exelix11** [comment]
post the error message you see in the console

**Comment by gitgudscrubb** [comment]
I think it was dvr-patches. I hard rebooted and solved the issue
