### ISSUE TITLE
[Help] rPi4-b works well with 1080p monitors using network. When plugged into a 4k TV, the resolution sets to 4k and the pi can't decode fast enough.

### ISSUE THREAD

**Issue by mrSilkie** [exelix11/SysDVR#254]
I've been able to work around this by plugging the pi 4 into a 1080p monitor and then moving it to the big screen once it's set up.

Realistically i'd like to force it to decode to 720p and offload the upscale to the TV. I've tried changing the resolution in my pi's config but it seems that SysDVR is is running it's own internal config, likely getting resolution from the monitor by default.

**Setup information**
 - Raspberry Pi 4 64b lite-OS
 - Current Release SysDVR

**Additional context**
Following the steps in the manual install

[Mnaual install](https://github.com/exelix11/SysDVR/wiki/SysDVR-Client-setup#mnaual-install)

    Download and install [.NET](https://dotnet.microsoft.com/download).
        You need .NET 6 or newer, mono and .NET core will not work
        Microsoft provides packages for the most common package managers and distros
    Install SDL2 sudo apt install libsdl2-dev
    Install ffmpeg sudo apt install ffmpeg
        You need ffmpeg 5.1.x
        In particular we need libavcodec59, this may not be available in your package manager, if that's the case you'll have to build ffmpeg from source
        Failing to install the exact version of ffmpeg will result in a module not found error when you launch SysDVR-Client
    You should be ready, open a terminal in the same folder where you extracted the zip and check if it works by running dotnet SysDVR-Client.dll --help

    Note that the guide uses SysDVR-Client to launch the client, since you are not on windows you will have to use dotnet SysDVR-Client.dll instead with the terminal opened in the same folder as the extracted zip

**Comment by exelix11** [comment]
SysDVR has a fixed resolution of 720p but SDL will create a renderer at the native resolution of the system and scale it up. Possibly the scaling process causes this performance issue, you can try launching sysdvr with the commandline option `--scale nearest` to reduce the overhead, see the [scale quality environment variable](https://wiki.libsdl.org/SDL2/SDL_HINT_RENDER_SCALE_QUALITY). If that doesn't work i'm not sure how would i fix it.
