### ISSUE TITLE
[Bug]  Error reading next packet: Warning: libusb error Timeout while reading header

### ISSUE THREAD

**Issue by TmusaR** [exelix11/SysDVR#257]
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**
When using the new sysdvr client on windows, with usb, I get the message "Error reading next packet: Warning: libusb error Timeout while reading header". Once this happens the client no longer recognises the device after exiting the app, or the switch game. Once I reboot my switch console, I am able to do this again, yet once I start a game and begin USB connection via the client, i see the error message again.

If a game is not open whilst I attempt to start a connection the same error is given. This did not occur before the update, but I cannot role back as the the 5.5.6 sysdvr tells me to update. 

This error occurred before installing the new usb driver with the new client, and continues to occur even with the new driver. 

**To Reproduce**
Connect via USB with the Windows Client while the switch is on.

**Expected behavior**
Switch screen should mirror to Windows Client

**Setup information**
 - PC Os: Windows 11 x64
 - Console firmware 16.1.0|AMS 1.6.0|E
 - SysDVR version 6.0

**Additional context**
The error occurs both with a manually downloaded version, and a HB App Store version. I previously had the 5.5.6 manually downloaded and used the HB App Store to update if that may affect anything.
I have since fully deleted all relative files and manually installed the new 6.0 version yet the error remains

**Comment by TmusaR** [comment]
Upon restarting console, with usb attached to pc. I launch the client on windows, attempt connection with usb and receive the previously mentioned error. 
I then decided to backout of the client and try again, whilst in game, i unplugged then plugged in the usb after the libusb error and see this


Error reading next packet: Warning: libusb error Timeout while reading header
libusb: error [winusbx_submit_bulk_transfer] ReadPipe/WritePipe failed: [22] The device does not recognize the command.
USB warning: Couldn't communicate with the console. Try entering a compatible game, unplugging your console or restarting it.
USB warning: Couldn't communicate with the console (libusb receive handshake failed, result: Timeout len: 0). Resetting the connection...
USB warning: Couldn't communicate with the console. Try entering a compatible game, unplugging your console or restarting it.
USB warning: Couldn't communicate with the console (libusb receive handshake failed, result: Timeout len: 0). Resetting the connection...
USB warning: Couldn't communicate with the console. Try entering a compatible game, unplugging your console or restarting it.

**Comment by TmusaR** [comment]
Embarrassingly, this was my user error.

I have fixed this issue, by updating my sysDVR patches, the games I attempted to stream were all incompatible.

**Comment by exelix11** [comment]
> but I cannot role back as the the 5.5.6 sysdvr tells me to update.

For reference, you have to reboot the console to completely downgrade sysdvr. Extract the 5.5.6 zip, replace all the files on the sd and reboot the console, then it should work. You will also need to use the 5.5.6 pc client.
