### ISSUE TITLE
[Help] My switch  is always in host mode and charging my computer

### ISSUE THREAD

**Issue by mio-19** [exelix11/SysDVR#258]
[To submit a request fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]
[Note that you can also ask for help on the discord server]

**Where do you get stuck ?**
Connect switch and make it running on the correct mode. I can't get SysDVR to recognize my device. I also can't get mtp mode of dbi working.
I tried flipping my typec-to-typec cable and switching two end sides. I tried use different usb-c ports on my computer and also android phone. Switch is always charging the connected device. I assumed that switch is stuck on the usb host mode.

**What's the error message you get ?**

**Setup information**
 - PC OS: Windows11
 - Console firmware [e.g. 10.0.0] 17.0.0
 - Custom firmware name and version [e.g. Atmosphere 0.12.0] AMS 1.6.2
 - SysDVR version [e.g. 3.0 Usb-Only]

**Additional context**

**Comment by exelix11** [comment]
This is a problem with the usb configuration on switch and doesn't depend on the specific homebrew you use.

The only sure-fire solution that i know of is to use an usb otg adapter on the computer side (so a C to A adapter) and then connect the console with a A to C cable where the C end is plugged in the switch.

Some combinations of PC hardware are capable of properly handling a C to C cable but I have found it to not be very reproducible.
