### ISSUE TITLE
Please add armv7a armebi for Android TV and older Tablets Smartphones 

### ISSUE THREAD

**Issue by Yoshi1981** [exelix11/SysDVR#259]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please add armv7a armebi for Android TV and older Tablets Smartphones

**Comment by Yoshi1981** [comment]
Only arm64 😭

**Comment by exelix11** [comment]
That is not possible currently due a limitation of dotnet AOT on android, the dotnet team doesn't seem interested in arm32 support following google's decision to drop it as well.

It may be possible to hack a dotnet runtime to run without aot on arm32-bionic but currently I'm not interested in working on it.
