### ISSUE TITLE
Visual C++ is a dependency

### ISSUE THREAD

**Issue by Archargelod** [exelix11/SysDVR#26]
OS: Windows 7 x64
I was trying to setup usb streaming following a guide but when I ran ".bat" it's returned an error: 
```
C:\UsbStream>UsbStream.exe video mpv "C:\mpv\mpv.com"
UsbStream - 2.0 by exelix
https://github.com/exelix11/SysDVR

Unhandled exception. System.DllNotFoundException: Unable to load DLL 'libusb-1.0
.dll' or one of its dependencies: Не найден указанный модуль(transl.- module not found). (0x8007007E)
   at LibUsbDotNet.NativeMethods.Init(IntPtr& ctx)
   at LibUsbDotNet.LibUsb.UsbContext..ctor()
   at UsbStream.Program.GetDevice(LogLevel level)
   at UsbStream.Program.Main(String[] args)
```
After installing "VC_redist for Visual Studio 2015, 2017 and 2019" from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) everything work like a charm.

**Comment by exelix11** [comment]
Good catch, it seems to be a LibUsb requirement, usually most people have these libs installed but on a recently installed copy of windows they will be missing, will add it to the readme.
