### ISSUE TITLE
[Feature request] Android screen rotation lock

### ISSUE THREAD

**Issue by PurifierUnit** [exelix11/SysDVR#262]
The Android version currently does not respect the device's screen orientation settings.  If I lock my phone into landscape mode, for instance, the SysDVR stream will still reorient itself to portrait mode if the phone is rotated.  Not sure this counts as a bug, _per se_, so putting it in as a feature request -- if the Android client could optionally honor my local orientation settings, that would be superb.  =)

**Comment by exelix11** [comment]
Can confirm. This seems to be an SDL issue from 2022 https://github.com/libsdl-org/SDL/issues/6090

Don't expect it will be fixed anytime soon, will look into android apis to figure out if there's a way to prevent it or else will have to add a in-app rotation lock feature.

**Comment by exelix11** [comment]
Nevermind, this was actually an easy fix, just had to tweak a parameter in SDL code. Will be part of next release, you can grab a CI build from https://github.com/exelix11/SysDVR/actions/runs/7577727013
