### ISSUE TITLE
[Help]无法安装驱动

### ISSUE THREAD

**Issue by 17712306936** [exelix11/SysDVR#265]
我想使用zading来安装视频和音频驱动，使用win11和USB3.2数据线，但是即使列出隐藏选项之后我也只能找到nintendo switch这一个驱动。
![QQ截图20240121212753](https://github.com/exelix11/SysDVR/assets/134472103/7f3ae871-298e-4f49-a702-6674aa4e16b5)
对于网络桥接，我使用了IP连接并遇到了以下报错：
![QQ截图20240121213412](https://github.com/exelix11/SysDVR/assets/134472103/0832739b-166b-4790-8ed1-6edc4cf5d6c0)

**Comment by exelix11** [comment]
I only do English support.

Do not use Zadig, it is only for old SysDVR.

Since version 6.0 you can use the "USB driver" button in the client.

See https://github.com/exelix11/SysDVR/wiki/USB-Driver#driver-setup-on-windows

**Comment by 17712306936** [comment]
> 我只做英语支持。
> 
> 不要使用 Zadig，它仅适用于旧的 SysDVR。
> 
> 从 6.0 版开始，您可以在客户端中使用“USB 驱动程序”按钮。
> 
> 查看 https://github.com/exelix11/SysDVR/wiki/USB-Driver#driver-setup-on-windows

非常感谢您的回复，我尝试了这一行为，然后我遇到了以下报错：
![QQ截图20240121215920](https://github.com/exelix11/SysDVR/assets/134472103/e8c73d28-c3aa-4b84-89cd-fd8d13c552bb)
请问我遗失了什么步骤吗？

**Comment by exelix11** [comment]
I think your console has a old SysDVR version. Download latest on your console then reboot and try again.

When you open driver settings, what status message do you see ? 
example:
![immagine](https://github.com/exelix11/SysDVR/assets/13405476/31efaad8-7a3c-48f3-8eb8-15da870ff6cf)

For me the highlighted text says the driver is already correctly installed

**Comment by 17712306936** [comment]
> 我认为您的控制台有一个旧的 SysDVR 版本。在主机上下载最新版本，然后重新启动并重试。
> 
> 当您打开驱动程序设置时，您会看到什么状态消息？ 例： ![immagine](https://private-user-images.githubusercontent.com/13405476/298388415-31efaad8-7a3c-48f3-8eb8-15da870ff6cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDY2NjksIm5iZiI6MTcwNTg0NjM2OSwicGF0aCI6Ii8xMzQwNTQ3Ni8yOTgzODg0MTUtMzFlZmFhZDgtN2EzYy00OGYzLThlYjgtMTVkYTg3MGZmNmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE0MTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMGQ3YzI3ZmFhZjBkMzU5MWQyYTVkNmY4YzE0YWE1ZDhhODY4OGY4OTA3MGU5MmU3NDg4MzNlYWY5ZWQ3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zULlFGOBeSKhZtBBnTa-c8nBKOrPIs4TXfMzogdZdbY)
> 
> 对我来说，突出显示的文本表明驱动程序已经正确安装

非常感谢您的帮助！在重新安装所有文件之后我成功了！非常非常感谢您！我认为应该是版本没有更新的原因
