### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by gykpro** [exelix11/SysDVR#266]
**Is your feature request related to a problem? Please describe.**
My scenario is a bit different. I'm not seeking an recording/video out put from switch games. I mainly do emulations on Switch lite with Linux installed. I have been seeking a way to occasionally output video to external monitor. I think SysDVR is the closest solution I can find.

**Describe the solution you'd like**
I would like a software that can start screen recording on Linux and send the signal via USB. I don't think it's SysDVR's scope since it's a different scenario on different OS, the only shared part is the Switch hardware.

**Describe alternatives you've considered**
Maybe you can shed some light on how the "send video via USB" part is done? Maybe I can seek solutions with a Linux screen recording and start from there.

**Additional context**
I came across SysDVR via this video: https://www.youtube.com/watch?v=MKwsfdkRhE4

**Comment by exelix11** [comment]
So you are trying to stream from linux running on switch to an external monitor ?
That is outside the scope of SysDVR since it's a custom sysmodule for the native switch OS and uses its special clip recording APIs, as things stand it will not work on linux. You should look into normal PC screen casting solutions like parsec.

**Comment by gykpro** [comment]
> So you are trying to stream from linux running on switch to an external monitor ? That is outside the scope of SysDVR since it's a custom sysmodule for the native switch OS and uses its special clip recording APIs, as things stand it will not work on linux. You should look into normal PC screen casting solutions like parsec.

Fully understandable. My problem regarding these casting solutions is, they are network based. I adore the idea and your implementation of transferring signal via USB, would you share a bit how can I transfer captured signal to usb?

**Comment by exelix11** [comment]
There is no magic sauce, it is just USB bulk transfers using the native usb API on switch and libusb on the receiving end. I think implementing it in existing casting solutions will not be easy nor makes much sense. Either way the protocol is documented [here](https://github.com/exelix11/SysDVR/blob/master/protocol.md).

I think your best bet is to use a LAN adapter and stream over wired network.
