### ISSUE TITLE
[Help] unable to detected the sysDVR device ID and my switch show me couldn't connect to sysDVR

### ISSUE THREAD

**Issue by ZeroT002** [exelix11/SysDVR#269]
![{E566BE68-012B-41e2-9ED1-6885BDE42AD9}](https://github.com/exelix11/SysDVR/assets/158285890/813f74c7-d524-41f2-9c4d-abb13a2c9aea)
![847AE18C02DEA9F1711045CAD36A9001](https://github.com/exelix11/SysDVR/assets/158285890/3c4598d8-35f6-4970-aba8-ccfbc1c0a178)
![image](https://github.com/exelix11/SysDVR/assets/158285890/97db4c66-a368-4fe1-8edc-95c67f7dbff0)

I almost try everything. like reboot the switch , reinstall the driver and change cable to USB-A to C . it won't work.
can you help me to solve my problem?
如能相助,感激不尽!

**Comment by exelix11** [comment]
Second picture indicates that the sysmodule is not installed on the console. Copy the files again, then reboot the console.

**Comment by ZeroT002** [comment]
First thank you for responding to my question. I have followed your instructions (re-copy the file and reboot the console ).
![2024013120193600](https://github.com/exelix11/SysDVR/assets/158285890/2525aa10-eead-41b3-8126-7ede9644b393)
I'm still getting the same error as before
![{A65A8A4A-6357-4239-B229-D520664FA454}](https://github.com/exelix11/SysDVR/assets/158285890/e1798894-0bba-453d-a084-b9e82d465113)

**Comment by ZeroT002** [comment]
I have check the file one by one. It is completely complete

**Comment by ZeroT002** [comment]
> Second picture indicates that the sysmodule is not installed on the console. Copy the files again, then reboot the console.

I have check the file one by one. It is completely complete T_T

**Comment by exelix11** [comment]
That is the wrong folder, you have to extract the zip to the root of the sd card. The `atmosphere` folder of the zip must merge with the `atmosphere` folder you already have on your sd card.

**Comment by ZeroT002** [comment]
> That is the wrong folder, you have to extract the zip to the root of the sd card. The folder of the zip must merge with the folder you already have on your sd card.`atmosphere``atmosphere`

oh! I get it. But unfortunately, it still has the same error as before X_X sorry about this.

**Comment by ZeroT002** [comment]
It seems to have only changed the icon position.

**Comment by exelix11** [comment]
check if the file `\atmosphere\contents\00FF0000A53BB665\exefs.nsp` exists on your sd card. If it does you extracted everything correctly and only need to reboot the console.

**Comment by ZeroT002** [comment]
> check if the file `\atmosphere\contents\00FF0000A53BB665\exefs.nsp` exists on your sd card. If it does you extracted everything correctly and only need to reboot the console.

oh, It gives an error on the first start, but succeeds the second time! thank you, console side is totally working right now. But there are still problems on the PC side.

**Comment by exelix11** [comment]
Now that the sysmodule is working you need to set the mode and enter a compatible game before streaming.
Follow the guide https://github.com/exelix11/SysDVR/wiki

**Comment by ZeroT002** [comment]
> Now that the sysmodule is working you need to set the mode and enter a compatible game before streaming. Follow the guide https://github.com/exelix11/SysDVR/wiki

really thank you at first! I can use TCP now, but I have one more question. In a network environment, it looks a little bit lag. How can I fix this driver issue? to use USB mode. If this question is too draining on you, I won't ask about this question.

**Comment by exelix11** [comment]
For USB you need a USB C to A cable (USB C to C cables don't work). Set the console to USB mode from sysdvr settings and connect to the PC, then install the driver and it should work.

**Comment by ZeroT002** [comment]
> 对于 USB，您需要一根 USB C 转 A 电缆（USB C 转 C 电缆不起作用）。从 sysdvr 设置将控制台设置为 USB 模式并连接到 PC，然后安装驱动程序，它应该可以工作。

I'm guess stuck in install usb driver now
![image](https://github.com/exelix11/SysDVR/assets/158285890/ffceace6-1616-4594-ad02-19e23a1b33aa)
It told me that the installation was a success.
I'm using a USB C to A cable
And set usb mode

**Comment by ZeroT002** [comment]
![image](https://github.com/exelix11/SysDVR/assets/158285890/83257808-892d-4cc9-be43-f4a15cc32fd6)

**Comment by ZeroT002** [comment]
![2024013120553000](https://github.com/exelix11/SysDVR/assets/158285890/2415dc3c-fc45-4677-8525-6de7fd5056d0)
![IMG_4154](https://github.com/exelix11/SysDVR/assets/158285890/0f6077d1-4dd5-4dcf-a940-2f2cb2ba98f8)

**Comment by ZeroT002** [comment]
It's available when re-plugin, which is kind of funny.
All in all, thank you very much for your help.
I wish you all the best in the future!
你是我的英雄,朋友!(泪目)

> Click save and enter a compatible game, then plug in the console and it should work.

**Comment by 22c222** [comment]
i found this \atmosphere\contents\00FF0000A53BB665\exefs.nsp
but my console is still like the second picture

**Comment by rehza97** [comment]
hello i'm having same problem i followed all the steps and even have the files on my switch lite 
\atmosphere\contents\00FF0000A53BB665\exefs.nsp

but still having same problem

**Comment by exelix11** [comment]
@raz1209 and @rehza97 You two opened an issue with the same issue in a short timespan, are you following some guide that is not the wiki ?

Anyway the "could not connect with sysdvr" error means that the settings app can't communicate with the sysmodule. This means the sysmodule is not running.

First of all ensure that you copied the files correctly, see the previous messages in this thread for examples of common errors.
Then, if you have any third-party overlays that manage sysmodules make sure that sysdvr is set to enabled.
Finally, reboot your console. After boot wait about 30 seconds before opening the sysdvr settings homebrew.

If none of this works it means you might have some weird setup with your atmosphere configuration, you either figure it out or reinstall atmosphere from scratch.

@rehza97 you in particular mentioned in #342 that you switched to the usb-only build. Note that the usb-only build does not work with the settings app and will always be enabled, to check if it works you must connect it to a PC and check if it shows up as a device.

**Comment by Kazura-Collins** [comment]
I have the same problem (second original screenshot);

![Image](https://github.com/user-attachments/assets/b43975c9-3061-454e-9a11-4da09a2a6d70)
(I copied the config and nro too of course)

I do not have any third-party sysmodules manager, I think, and I've rebooted the console multiple times. I don't see anything strange on my atmosphere folder, maybe the Smash Ultimate Mods? (

![Image](https://github.com/user-attachments/assets/c13194d3-0221-4537-854c-2d14b41d8ffe)
