### ISSUE TITLE
[Feature request] OSX and Volume Control

### ISSUE THREAD

**Issue by Goldenkrew3000** [exelix11/SysDVR#270]
**Is your feature request related to a problem? Please describe.**
SysDVR seems to have no way of controlling its own volume. This is fine on Windows as windows has a built in audio mixer, but OSX does not. This leads to SysDVR playing at the max system volume, which is an issue if you also want to have another program playing music / a video, since SysDVR is too loud.

**Describe the solution you'd like**
There is already a keybind system in place for screenshots, recording, etc. So maybe add in 2 keys for Volume up and down control.

**Describe alternatives you've considered**
I have tried using a 3rd party program for OSX called BackgroundMusic (Seems to be the only free OSX audio mixer) to control the volume of SysDVR, but BackgroundMusic crashes if I try to adjust the volume of SysDVR.

**Comment by exelix11** [comment]
Will look into it

**Comment by exelix11** [comment]
Implemented with bc8f5d50d4dac5de0659eccc40c7dba10137f20b and will be part of the next release
