### ISSUE TITLE
[Feature request] lower Android required version

### ISSUE THREAD

**Issue by eroldru** [exelix11/SysDVR#272]
Lovely work with the Android Client, but it would be great if lower versions were also supported.
This is relevant for Android streaming devices like e.g. the FireTV Sticks. The older versions are stuck at Android 9, which is a real shame, since these would be great for this use case.

According to [this comment](https://github.com/exelix11/SysDVR/issues/122#issuecomment-1738933786) from exelix11, a newer version should come out eventually when the mentioned bug will be fixed. Any plans to continue, or has this already been dropped?

Thank you for the great work.

**Comment by exelix11** [comment]
I do plan to look into that for the next update but I didn't have much free time lately so no ETA yet.

**Comment by eroldru** [comment]
Greatly appreciated, thank you :)

**Comment by eroldru** [comment]
Hi, I just read in this thread that 32-Bit is also not possible. You probably have no plans to do this, right? I mean, it will probably be a lot of work and I understand.
If no plans are there, you could close this issue, since I would believe they are more or less linked.

Thanks for your work :)

**Comment by eroldru** [comment]
Great, thank you for the clarification.

**Comment by exelix11** [comment]
It seems the dotnet team backported the fix for this issue to 8.0.2 or 8.0.3, meaning any new build of sysdvr-client should work on older android versions now. You can try a build i just triggered from CI here https://github.com/exelix11/SysDVR/actions/runs/8308940319

**Comment by eroldru** [comment]
Hey there, sorry it took me so long. I had completely forgotten about this. Also more important, I was missing an older ARM64 device. This is the used chipset https://datasheets.globalspec.com/ds/qualcomm/snapdragon-616/88263f61-777b-4dc0-b81b-4f73c98d2ee4
The device is currently using Android 5.1.1 and has no possibility to update.

Trying to run the APK file results in error parsing the package, so I guess it has a higher minimum requirement.

Seems I am not able to test this package, sorry.

**Comment by eroldru** [comment]
I see, I will try to find another device and test. Thank you

**Comment by pystorage** [comment]
> It seems the dotnet team backported the fix for this issue to 8.0.2 or 8.0.3, meaning any new build of sysdvr-client should work on older android versions now. You can try a build i just triggered from CI here https://github.com/exelix11/SysDVR/actions/runs/8308940319

Xiaomi Mi Stick (Android 9 x64) does not work!

**Comment by eroldru** [comment]
> Xiaomi Mi TV Stick (Android 9 x64) does not work!
while the CPU is indeed 64-bit, I do believe the OS is only 32-bit, but I cannot find any information, since it is not the most popular device sadly. I have the same issue with my Amazon Stick which also has Android 9, but just 32-bit version.

**Comment by exelix11** [comment]
The fix for android 8 support is now released.
32-Bit Android is not planned due to dotnet limitations.
