### ISSUE TITLE
1080p@60fps and MEMC supported

### ISSUE THREAD

**Issue by zjmsjla** [exelix11/SysDVR#273]
All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps.
Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.

**Comment by exelix11** [comment]
You can stream at 60 fps with this https://github.com/exelix11/SysDVR/issues/147
1080p support is not possible.

I have no clue what MEMC is about but i guess some kind frame interpolation and i'm not interested in implementing it.

**Comment by zhubibaba** [comment]
> All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps. Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.

you can try older version of sysdvr, like v5.5.6 and stream it to mpv. i tried before but it didnt work well for gaming. boosting to 60fps for 30fps games is super laggy（im using 4060） and upscaling is basically unnoticeable

**Comment by zjmsjla** [comment]
> > All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps. Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.
> 
> you can try older version of sysdvr, like v5.5.6 and stream it to mpv. i tried before but it didnt work well for gaming. boosting to 60fps for 30fps games is super laggy（im using 4060） and upscaling is basically unnoticeable

I have tried v5.5.6 and it seem to work well via usb on official client after edit the config file called system_settings.ini in atmosphere/config. I changed the FPS to 60, the bitrate to12Mbps, the key frame to 30. It can stream game stably with about 100ms delay in this case. I can not confirm the  exact latency but I experience and guess it. A video on youtube show that it can stream game in the case of 720p@60fps with 40ms delay. Maybe you can try this solution. 
Though the upscaling is basically unnoticeable, I still want to try it. But I don't know how to add an upscaling filter to official client. Only on official client can I stream game via usb which has the lowest latency. Otherwise, streaming game via wifi, the transport delay added after effect delay is unacceptable.

**Comment by zhubibaba** [comment]
lossless scaling and magpie, these two should help

**Comment by zhubibaba** [comment]
> > > All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps. Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.
> > 
> > 
> > you can try older version of sysdvr, like v5.5.6 and stream it to mpv. i tried before but it didnt work well for gaming. boosting to 60fps for 30fps games is super laggy（im using 4060） and upscaling is basically unnoticeable
> 
> I have tried v5.5.6 and it seem to work well via usb on official client after edit the config file called system_settings.ini in atmosphere/config. I changed the FPS to 60, the bitrate to12Mbps, the key frame to 30. It can stream game stably with about 100ms delay in this case. I can not confirm the exact latency but I experience and guess it. A video on youtube show that it can stream game in the case of 720p@60fps with 40ms delay. Maybe you can try this solution. Though the upscaling is basically unnoticeable, I still want to try it. But I don't know how to add an upscaling filter to official client. Only on official client can I stream game via usb which has the lowest latency. Otherwise, streaming game via wifi, the transport delay added after effect delay is unacceptable.

用lossless scaling 和 magpie, b站上有教程

**Comment by zhubibaba** [comment]
> > > All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps. Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.
> > 
> > 
> > you can try older version of sysdvr, like v5.5.6 and stream it to mpv. i tried before but it didnt work well for gaming. boosting to 60fps for 30fps games is super laggy（im using 4060） and upscaling is basically unnoticeable
> 
> I have tried v5.5.6 and it seem to work well via usb on official client after edit the config file called system_settings.ini in atmosphere/config. I changed the FPS to 60, the bitrate to12Mbps, the key frame to 30. It can stream game stably with about 100ms delay in this case. I can not confirm the exact latency but I experience and guess it. A video on youtube show that it can stream game in the case of 720p@60fps with 40ms delay. Maybe you can try this solution. Though the upscaling is basically unnoticeable, I still want to try it. But I don't know how to add an upscaling filter to official client. Only on official client can I stream game via usb which has the lowest latency. Otherwise, streaming game via wifi, the transport delay added after effect delay is unacceptable.

use losslessscaling, its perfect

**Comment by mr-zaak** [comment]
> > > > All NS which is able to run this app can boost cpu and gpu. So maybe NS can stream at 1080p@60fps through usb when boosted. Can you add this function in the future? It's ok to stream at 1080p@30fps or 720p@60fps. Another request is adding MEMC on client. I konw that it's possible to use MEMC by third part player, but streaming via wifi is unstable. If there is a MEMC function on official client, I can stream at 720p@30fps or 1080p@30fps through usb but have an experience at 720p@60fps or 1080p@60fps with MEMC.
> > > 
> > > 
> > > you can try older version of sysdvr, like v5.5.6 and stream it to mpv. i tried before but it didnt work well for gaming. boosting to 60fps for 30fps games is super laggy（im using 4060） and upscaling is basically unnoticeable
> > 
> > 
> > I have tried v5.5.6 and it seem to work well via usb on official client after edit the config file called system_settings.ini in atmosphere/config. I changed the FPS to 60, the bitrate to12Mbps, the key frame to 30. It can stream game stably with about 100ms delay in this case. I can not confirm the exact latency but I experience and guess it. A video on youtube show that it can stream game in the case of 720p@60fps with 40ms delay. Maybe you can try this solution. Though the upscaling is basically unnoticeable, I still want to try it. But I don't know how to add an upscaling filter to official client. Only on official client can I stream game via usb which has the lowest latency. Otherwise, streaming game via wifi, the transport delay added after effect delay is unacceptable.
> 
> use losslessscaling, its perfect

How did you implement lossless scaling with sysdvr?
