### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by occuItic** [exelix11/SysDVR#275]
**Is your feature request related to a problem? Please describe.**
when trying to stream to obs, it doesnt capture any sound from sysdvr at all

**Describe the solution you'd like**
an option to output sysdvr's sound to something else, like a virtual mic for example, so people can use that as audio capture in obs

**Describe alternatives you've considered**
i've tried everything i know to do and i can't figure out where sysdvr's sound is coming from in my sounds setting. i can hear the game perfectly fine, but when putting it in obs it will not record/stream the audio

**Comment by exelix11** [comment]
I don't think i ever had problems streaming audio. Regardless, if you use Windows 10 or newer you can change the output device for the client to a virtual microphone in the modern settings 
![img](https://github.com/exelix11/SysDVR/assets/13405476/56027551-a204-4191-bf85-d5060a7e5e9e)
Does this work ?
