### ISSUE TITLE
[Bug] Not working on 18.0.0 update

### ISSUE THREAD

**Issue by imod-commission** [exelix11/SysDVR#277]
**Describe the bug**
[SysDVR no longer works after 18.0.0 update. both network mode and USB mode does not show the device.]

**To Reproduce**
[Connect by either network mode or USB mode normally]

**Expected behavior**
[Switch should show up on device list]

**Setup information**
 - PC Os: [Windows 11 x64]
 - Console firmware [18.0.0]
 - Custom firmware name and version [Atmosphere 1.7.0]
 - SysDVR version [6.0]

**Comment by exelix11** [comment]
I have received reports that sysdvr does work on 18.0. Dvr-patches is broken as expected and i'm working on a fix, games that need that will not work.

If streaming does not work at all you probably accidentally deleted it while updating atmosphere.
