### ISSUE TITLE
[Feature request] Turn off switch display while streaming

### ISSUE THREAD

**Issue by 54keesh** [exelix11/SysDVR#278]
Really great work with the module, I am in love with the really low latency down to mili secs transmission over the network. Quite amused honestly. Just a feature that i thought If technically possible would be great and make sysdvr much more better than it already is.

**Describe the solution you'd like**
I am thinking if theres an option/toggle to switch of the display of the console while streaming over to another device. That would be great because we are streaming only to be able to view it there, then it will act as a mirror screen as well as a media streamer and It will save a lot of switch's battery as well. 

**For Context**
Just like how scrcpy works for android.

**Other alternatives**
For now I just turn the brightness of the switch to the bare minimum.

**Comment by exelix11** [comment]
This is already available in the beta builds on github actions and will be part of the next release.

Currently there is no on the fly switching, you set the screen mode when starting to stream in the client settings.

**Comment by 54keesh** [comment]
@exelix11 great, I am looking forward to that release then:)

**Comment by exelix11** [comment]
This is now released. You can enable this options in the client settings in advanced options.

**Comment by ofsandoval** [comment]
> This is now released. You can enable this option in the client settings in advanced options.

Could you be more specific about how to do this? Or where should I read how to do it? Sorry I'm a newbie at this stuff but I'm interested in this functionality.

**Comment by selloa** [comment]
Love this feature. Would it be possible to automatically turn off (aka turn the screen back on) when the program doesn't receive packets from the console. That way you could change games, handle error messages, etc on the console screen. Once the stream comes back the console screen could turn off again. Thank you for your work!
