### ISSUE TITLE
[Help] No video output once the 'Use hardware-accelerated FFMPEG decoder' option was enabled

### ISSUE THREAD

**Issue by TickToTock** [exelix11/SysDVR#279]
**Where do you get stuck ?**
I tried to enable 'Use hardware-accelerated FFMPEG decoder' feature in the settings. However, there's no video output afterwards.
I have FFMPEG installed on my PC(win10). 

**What's the error message you get ?**
Initializing video player with h264_qsv codec.
[h264_qsv @ 000001a280d36e80] Invalid pkt_timebase, passing timestamps as-is.
Using the h264_qsv hardware accelerated video decoder, in case of issues try to use the default one by disabling this option.

**Setup information**
 - PC OS: Windows 10 x64
 - Custom firmware name and version : Atmosphere 1.7.0
 - SysDVR version: 6.0 

**Additional context**
Everything was fine with the default settings. I connected the Switch to my desktop via WiFi. 
When connected via WiFi, the game display showed irregular color blocks and intermittent stuttering (only in Diablo II, other games were normal), but it was fine in USB mode. 
I tried enabling hardware-accelerated FFMPEG decoder to resolve the issue, but it was ineffective. 
My computer has a dedicated GPU (rtx2080ti) and does not have an integrated Intel GPU.
![01](https://github.com/exelix11/SysDVR/assets/77729821/4f674487-889f-4964-ad56-30b976ec95d8)
![02](https://github.com/exelix11/SysDVR/assets/77729821/a6506966-4081-407c-b896-6cc88646f9d7)
![03](https://github.com/exelix11/SysDVR/assets/77729821/3f4257ed-6a5f-4220-b59f-e3c266fb4be4)

**Comment by exelix11** [comment]
Hardware decoding is meant for single board computers like raspberry pi where the cpu may not be able to keep up, this is not your case. It's best if you disable that. 

Since you only get glitches when wireless streaming, try using ethernet or putting your console closer to your router.

**Comment by ugurkrl** [comment]
Same issue with QSV Supported intel gpu
