### ISSUE TITLE
[Bug] Installation of V6.0 on MacOS 

### ISSUE THREAD

**Issue by ireneAccept** [exelix11/SysDVR#280]
**Describe the bug**
Hi, I just downloaded the SysDVR-Client installation package for MacOS-arm 64, extracted, released and launched the SysDVR-Client file. But it shows: "The required instruction sets are not supported by the current CPU." I have no idea what I can do. QAQ.

**Setup information**
 - PC Os: MacOS M1 BigSur 11.7
 - SysDVR version 6.0

**Comment by exelix11** [comment]
I have received feedback from other mac users reporting that it works fine, however all of them are on MacOS 14.0 or newer.
It is possible that your mac os version is too old ?

**Comment by ireneAccept** [comment]
> I have received feedback from other mac users reporting that it works fine, however all of them are on MacOS 14.0 or newer. It is possible that your mac os version is too old ?

Thanks a lot, I will try to upgrade my masOs version ;)
