### ISSUE TITLE
[Bug] Game crash while using SysDVR on Switch console

### ISSUE THREAD

**Issue by Mika58Carca** [exelix11/SysDVR#282]
[**Bug description**
When installing SysDVR, everything went well until it was used.
Indeed, as soon as we put SysDVR into operation on the Switch console, it causes games to crash, such as The Witcher 3, where when the story of this game starts, it crashes then a message appears like "An error is occurred" each time and the game stops.
When I remove the SysDVR packaging from the atmosphere folder in "content", and restart the console, everything works again.

I wanted to inform you of this malfunction to be fixed as soon as possible, thanking you in advance.

**Configuration information**
    - PC operating system: MacOS Monterey Version 12.7.4
    - Console Firmware: 18.0.0
    - Custom firmware name and version: Atmosphere 1.7.0
    - SysDVR version: SysDVR-Client-MacOs-x64.zip (File used on MacOS) Version 6.0

**Comment by exelix11** [comment]
You probably have dvrpatches which is  known to crash with the Witcher 3. That is not supported.

**Comment by Mika58Carca** [comment]
Okay, how do you solve this problem then? Do you have a solution?

**Comment by exelix11** [comment]
Remove dvrpatches and it should work again.

**Comment by exelix11** [comment]
Yeah streaming the witcher 3 is not possible at the moment.

**Comment by Mika58Carca** [comment]
Okay thank you for your feedback hoping that one day it will work 😇
