### ISSUE TITLE
Как улучшить качество картинки и от чего оно зависит?[Help]

### ISSUE THREAD

**Issue by iNajime** [exelix11/SysDVR#284]
[To submit a request fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]
[Note that you can also ask for help on the discord server]

**Where do you get stuck ?**
[Which step of the guide ? Did you read the Troubleshooting section at the end ?]

**What's the error message you get ?**
[If you see a black window appearing and disappearing quickly and can't read the error you can launch the program in a command prompt manually so it won't disappear, [here's how](https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8)]

**Setup information**
 - PC OS: [e.g. Windows 10 x64]
 - Console firmware [e.g. 10.0.0]
 - Custom firmware name and version [e.g. Atmosphere 0.12.0]
 - SysDVR version [e.g. 3.0 Usb-Only]

**Additional context**

**Comment by exelix11** [comment]
Only english support.

Streaming resolution is 720p, as of now it can't be changed. Quality depends on wifi strength or the usb cable.
