### ISSUE TITLE
sysdvr 6.1 Display abnormal[Bug] 

### ISSUE THREAD

**Issue by junge121** [exelix11/SysDVR#285]
![IMG_20240506_195750](https://github.com/exelix11/SysDVR/assets/169056476/d54c7360-3bf9-409b-aeda-40fac2353156)
[To submit a bug report fill all the parts of the template, then remove all the text within square brackets "[ ]" ]
[Issues that don't follow the template will be closed]

**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
[Explain how to trigger the bug]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Setup information**
 - PC Os: [e.g. Windows 10 x64]
 - Console firmware [e.g. 10.0.0]
 - Custom firmware name and version [e.g. Atmosphere 0.12.0]
 - SysDVR version [e.g. 3.0 Usb-Only]

**Additional context**
[Add any other context about the problem here.]

**Comment by exelix11** [comment]
It's probably a bug in the translation support. What language is your console set to ? Try setting it to english.

**Comment by junge121** [comment]
That's right, my switch is set up in Chinese

**Comment by junge121** [comment]
Setting the Switch to English is normal

**Comment by junge121** [comment]
Pressing the R key to start also shows abnormal display

**Comment by exelix11** [comment]
This should be fixed in https://github.com/exelix11/SysDVR/actions/runs/9039159634 , i will make a release update soon.

**Comment by exelix11** [comment]
The fix is now released
