### ISSUE TITLE
Hogwarts Legacy doesn't work

### ISSUE THREAD

**Issue by Gabriel4567890** [exelix11/SysDVR#288]
I really wanted to play Hogwarts Legacy on the sysdvr but it doesn't work

**Comment by exelix11** [comment]
I saw the dvr-pathces issue https://github.com/exelix11/dvr-patches/issues/41 I assume that means even with dvr-patches it does not work. In that case the game may need a specific patch to add support but it's not something I do.

I will keep the other issue open in case someone wants to look into it.

**Comment by Gabriel4567890** [comment]
I haven't tested the patch, is there a tutorial showing how to use it?
