### ISSUE TITLE
[HELP]I found a bug.This prevents me from playing on my tablet. Please help me.!!!!!!!!!!!!

### ISSUE THREAD

**Issue by s12akm** [exelix11/SysDVR#289]
I connect the switch with my Android tablet with a data cable, and myAndroid tablet will restart.
This only happens with a usb connection.
My Android number is 13.
Switch is the latest system.
Using version 6.1.sysdvr
If there are some sentences that you can't understand, please forgive me. I translated all the above with a translator.

**Comment by exelix11** [comment]
That seems like an hardware issue on your device, not related to sysdvr.

**Comment by s12akm** [comment]
> That seems like an hardware issue on your device, not related to sysdvr.

Ok, I see, but why the screen will be displayed briefly through usb connection, only for two or three seconds? Is this also due to hardware problems? What configuration is required for a perfect usb link on an Android device? Excuse me.
Thank you for your answers.
