### ISSUE TITLE
Missing quotes on GUI mpv path

### ISSUE THREAD

**Issue by Craftyawesome** [exelix11/SysDVR#29]
When using the batch export on windows, stream via RTSP and tcp bridge will not work if the path to mpv has spaces. The mpv option correctly has quotes.

**Comment by exelix11** [comment]
Thanks for reporting, I fixed it and updated the release, download `SysDVR-Client.7z` again.
To make sure you're running the updated GUI on windows you can open properties and check the details tab, version should be `3.0.0.2` for the GUI.
Client and other releases haven't been changed.
