### ISSUE TITLE
[Feature request] RTSP/RTMP Streaming

### ISSUE THREAD

**Issue by kevsestre** [exelix11/SysDVR#294]
Thanks for your hardwork exelix, Ive recently used sysdvr and was delighted to see you've successfully implemented backlight off feature.

Would it be possible to add rtsp/rtmp streaming, I'm basing this request from an android app called USB Camera, this app has that but requires capture card. Here's an image of streaming settings of the app for reference.

![Screenshot_20240612-141841_Trebuchet](https://github.com/exelix11/SysDVR/assets/170945487/c9d9000a-4de2-49a9-a961-09b3e0ff95f9)

**Comment by exelix11** [comment]
Sysdvr already has rtsp. The feature is called "simple network mode" in the sysdvr settings homebrew.
