### ISSUE TITLE
Guide not clear.

### ISSUE THREAD

**Issue by DitDitGitHub** [exelix11/SysDVR#3]
I found this on reddit today, and I wanted to try it out. I have installed the sysmodule and the driver but I find that the guide from that point is very unclear. I don't know what to open USBSteam with, as opening it on it's own and with Admin gives me a fatal error. I am running Windows 10, latest update, Switch is on update 9.0.1 (I think it's compatible?). Thanks for all help

**Comment by NovaPhoenix** [comment]
Usbstream is a CLI app. You need to use it in a terminal as described in the README file. https://github.com/exelix11/SysDVR/blob/master/readme.md#streaming

**Comment by exelix11** [comment]
^ This. Also in case you don't have it, you need to install [.NET core 3](https://dotnet.microsoft.com/download) to be able to run it.
Carefully read the guide and it should work.
Closing as not an actual issue.
