### ISSUE TITLE
Terminating Video/Audio thread due to ExtendedSocketException

### ISSUE THREAD

**Issue by Tails573** [exelix11/SysDVR#30]
I've been trying to set this up for a while and ive been getting this error and i do not know how to fix it
![Annotation 2020-02-11 014901](https://user-images.githubusercontent.com/60872133/74226044-afefd500-4c70-11ea-9412-4e8eeadc9d64.png)

**Comment by exelix11** [comment]
This is weird what is your OS and .net version ? Apparently `ExtendedSocketException` is an internal .net exception and shouldn't be exposed to the end user, sounds like a bug in the runtime.
Can you try this [build](https://github.com/exelix11/SysDVR/files/4185929/Debug.zip) ? It should print more detailed information.

**Comment by exelix11** [comment]
I just realized I made a mistake and the zip i posted doesn't contain a full build, it doesn't contain the dll file which means it changes basically nothing.
[This is the correct build](https://github.com/exelix11/SysDVR/files/4242210/debug.zip)

**Comment by exelix11** [comment]
Thanks to help from other users i figured out that ExtendedSocketException just means some generic connection error, will make it print the proper message with the next update, will keep this issue opened till then.

**Comment by exelix11** [comment]
This was fixed with the [4.0 Release](https://github.com/exelix11/SysDVR/releases/latest)
