### ISSUE TITLE
[Feature request] Possibility for an 32bit android version?

### ISSUE THREAD

**Issue by CR-spe** [exelix11/SysDVR#305]
Thank you for developing this amazing tool. I have been using it for months and its working great without and issue. While the android client works great on my phone, I could not quite be able to install it on my google chromecast (which I now learned is on an 32bit android and that is also the case with most set-top-boxes nowadays). So it is possible for a 32 bit android compatible client? It'll be great to play my switch lite on tv.

**Comment by exelix11** [comment]
This is not supported because the platform sysdvr uses does not support android arm32 builds.

I've read that with dotnet 9 32bit builds may be supported so when that releases I'll look into the possibility of supporting 32bit android too.

As for now this is not possible
