### ISSUE TITLE
[Feature request] iOS / iPadOS .ipa client

### ISSUE THREAD

**Issue by oppalla** [exelix11/SysDVR#309]
@exelix11 , please, I really badly need a way to connect SysDVR with my iPad. I work and live onboard ships, and the only screen I have bigger than my switch in my cabin is my iPad. I can easily install any ipa on it due its having TrollStore installed.

If you cannot develop an ipa client for iOS, by any chance, is there any other app that may accept the connection from the switch?

With VLC it works beautifully but, the latency makes it impossible to play.

As suggested by @NsCrosu if it was possible to be recognised as a USB camera, after iOS 17 it would have native support on iPads and iPhones.

If you need any assistance to develop this questions, ill be 100% available for you.

Thank you so much

**Comment by exelix11** [comment]
See my reply in #299
