### ISSUE TITLE
[Feature request] Linux aarch64 build

### ISSUE THREAD

**Issue by demenik** [exelix11/SysDVR#311]
Are there any plans on adding a linux aarch64 build?

**Comment by exelix11** [comment]
Arm64 is supported, however i don't produce all in one builds cause the most popular board is the raspberry pi and to get good performances from that (up to pi 3 which is the one i have idk 4 and later) you need a custom ffmpeg build with omx decoders support.

To run on arm64 devices you install dependencies manually then download the dotnet build and run it via dotnet as explained in the guide.
