### ISSUE TITLE
SysDVR Error Messages

### ISSUE THREAD

**Issue by RumbleTumble87** [exelix11/SysDVR#312]
**SysDVR is installed, but will not display my Nintendo Switch on either Windows PC or Android phone**

A quick summary:
- I've followed the installation guide (with the help of some YT videos) to the letter
- The full version of SysDVR 6.1.1 is installed on my Switch, Windows 11 laptop, and Android phone

On Windows: when I attempt to connect via USB, I receive the following error messages:
- The very first time I attempt to connect to a Switch after starting SysDVR: "Error reading next packet: Warning: libusb error Timeout while reading header" (This error appears in red in the prompt window in the background)
- Then, on subsequent attempts (in the main SysDVR window in white):
- "USB warning: Couldn't communicate with console (libusb receive handshake failed, result: Timeout len: 0). Resetting the connection..."
- "USB warning: Couldn't communicate with the console. Try entering a compatible game, unplugging your console or restarting it."

On Android:
- The phone doesn't detect my Switch at all: "No USB devices found."
- I've tried multiple USB cables (Type-A and Type-C) with both my PC and phone

For further clarity, the drivers SysDVR asks you to install are installed. I've checked the installation on my PC as well, and SysDVR reports no issues. Any assistance would be greatly appreciated!

**Comment by exelix11** [comment]
What games did you try streaming ? Not all of then are compatible you may need dvr patches, you can install them from the sysdvr settings homebrew.

Also try streaming over wifi to rule out usb specific problems (eg you can't have two sysmodules using USB at the same time)

**Comment by RumbleTumble87** [comment]
Thanks for the reply! It turns out, I'm an idiot. I didn't realise the dvr patches were mandatory!

It works now, and I'm just trying to figure out how to get a decent framerate on the PC. Fantastic work!
