### ISSUE TITLE
[Help] sysdvr works with atmosphere 1.8.0 ?

### ISSUE THREAD

**Issue by Punknpc** [exelix11/SysDVR#314]
**Does sysdvr still work with the new atmosphere patch?**

When I try to get my screenshare, sometimes sysdvrclient finds my network and when I click it dosen't show anything he just waits for me to "get in to a game" I'm trying to share smash.

**Comment by exelix11** [comment]
I didn't have the time to port dvrpatches for 19.0 yet, it's coming eventually.

**Comment by Punknpc** [comment]
Thank you very much. I love sysdvr because I don't have a monitor with sound, so I used to stream / use music.
Take your time. Thanks for your work; very appreciated.

**Comment by exelix11** [comment]
There's a test version here https://github.com/exelix11/dvr-patches/issues/44 i'll push it to the repo so it gets into the auto update thing in a few days.

**Comment by exelix11** [comment]
19.0 patches are out. In the meantime 19.0.1 came out which requies new patches. I'm looking into that and expect to provide a fix in a few days.
