### ISSUE TITLE
is the background service always running?

### ISSUE THREAD

**Issue by tonyzzp** [exelix11/SysDVR#319]
does the background service always run when switch turn on?

I mean that, if i don't need it ,does sysdvr cost cpu/memory/network on the background?

**Comment by exelix11** [comment]
Yes it is always running, however if you are not streaming it doesn't do anything so there is no extra cpu or network usage.
It will still use up the sysmodule memory since that can't be freed which does not affect games but may cause issues if you have many sysmodules.

**Comment by exelix11** [comment]
Streaming means when a pc is connected.

You can set it off by default but it's functionally equivalent to a pc not being connected in other modes, the only difference is that in usb mode sysdvr watches for usb requests and in network mode it waits on a socket (so no CPU work) for a connection.
