### ISSUE TITLE
Can sxos be used ？

### ISSUE THREAD

**Issue by MRKS5260** [exelix11/SysDVR#32]
I am sxos and it will  prompt error:failed to connect to sysDVR,is the module set up properly?

**Comment by exelix11** [comment]
Yes, all CFWs should be compatible.
Download and extract the release somewhere on your pc, then rename the `atmosphere` folder to `sxos` and the `contents` folder inside of it to `titles`.
Now copy the `sxos` folder to the root of your sd and it should work.
Note that in case of other issues I only provide troubleshooting for atmosphere.
