### ISSUE TITLE
[Bug] Flatpak Build: SDL2 Removed from shared-modules

### ISSUE THREAD

**Issue by docquantum** [exelix11/SysDVR#320]
**Describe the bug**
SDL2 has been removed from the shared-modules repo used for the Linux flatpak build.

```
(flatpak-builder:4768): flatpak-builder-ERROR **: 22:02:38.552: Failed to load included manifest (/mnt/e/SysDVR/Client/Platform/Linux/shared-modules/SDL2/SDL2-no-libdecor.json): Failed to open file “/mnt/e/SysDVR/Client/Platform/Linux/shared-modules/SDL2/SDL2-no-libdecor.json”: No such file or directory
Trace/breakpoint trap
```

**To Reproduce**
Attempt to run `build-flatpak.sh` without changes to the script.

**Expected behavior**
The build script would be able to get past the install flatpak-builder install step.

**Setup information**
 - PC Os: Ubuntu 22.04.3 LTS on Windows 10 x86_64 via WSL2
 - Console firmware: N/A
 - Custom firmware name and version: N/A
 - SysDVR version: 72b9ba2b884f8a215fa8ee4fa3a274cce08a1c6a

**Additional context**
https://github.com/flathub/shared-modules/commit/e80df6027aa395c0a261ad1872a7c910f403a642

Quick fix is to lock the clone of `share-modules` to the last commit that had SDL2 (d88a9156b91eef64ecf1a313c868f1401c4bb39b)

```sh
if [ ! -d "shared-modules" ]; then
	git clone https://github.com/flathub/shared-modules.git
	cd shared-modules
	git checkout d88a9156b91eef64ecf1a313c868f1401c4bb39b
	cd ..
fi
```

The "proper" fix is to bump flatpak to 23.08+ as noted in the commit which removed the SDL2 folder.

If you'd like, I can look into making a pull request to fix this

**Comment by exelix11** [comment]
Ok i spent the last hour or so trying to figure this out. Flatpak is still an undocumented mess.
I added the workaround you described and it's currently building, hopefully it works.

If you want to do things the proper way, sure make a PR. I see that ffmpeg is also a runtime extension now so it would be great if we removed it as a build dpendency, using binaries would make the build process much faster.
