### ISSUE TITLE
[Bug] Bayonetta 3 Audio Drops During Battle

### ISSUE THREAD

**Issue by BleedWeed** [exelix11/SysDVR#326]
**Describe the bug**
Whenever I use sysdvr with Bayonetta 3, usually when it gets to a fight scene I've noticed it often will drop the audio until the fight is over. If I press start it'll give me the sfx for the menu but when I go back to the fight its quiet again and then when the fight is over and she breaks the barrier the sound comes back. 
**To Reproduce**
Play B3 up to a fight using sysdvr (same thing happens regardless if it's connected via usb or wifi)

**Expected behavior**
Scene will continue as normal until the fight is over and the barrier is broken, audio then returns.

**Setup information**
 - PC Os: Windows 10 x64
 - Console firmware 18.1.0
 - Custom firmware name and version [e.g. Atmosphere 0.12.0]
 - SysDVR version 6.1.1

**Additional context**
n/a

**Comment by exelix11** [comment]
This is probably the game removing the sound from streaming on purpose. You can use dvrpatches to workaround it.

**Comment by BleedWeed** [comment]
I had them enabled already, but I understand there are still some incompatibilities with some games

**Comment by exelix11** [comment]
The feature that games use to stop audio streaming should be supported though, i think the person who initially reported it was playing bayoneta too. Try to update the patches and reboot the console.

**Comment by exelix11** [comment]
Solution is to use dvrpatches, closing.
