### ISSUE TITLE
[Help] HOW TO CONTROL THE SWITCH WITH THE PC GAMEPAD?

### ISSUE THREAD

**Issue by mascotoide** [exelix11/SysDVR#329]
Hello everyone, how are you?

Is there a way to play on sysdvr and use the PC's own controls? I remember using it but I don't remember how to make it work. Can anyone help me?

Sorry for my English

**Comment by exelix11** [comment]
This is a streaming only sysmodule, you will need to install an additional mod for remote control such as https://github.com/olliz0r/sys-botbase

**Comment by joseph871107** [comment]
Hey there, I do also want to control switch remotely too. So I created one myself!

[Here](https://github.com/joseph871107/SysDVR) is my implementation combining amazing works of @exelix11 and [sys-botbase](https://github.com/olliz0r/sys-botbase) from @olliz0r.
[Usage documentation](https://github.com/joseph871107/SysDVR?tab=readme-ov-file#forked-features) is at the bottom of the readme.

Currently I built a windows version [here](https://github.com/joseph871107/SysDVR/actions/workflows/client-windows-x64.yml).
Feel free to check it out! Or build other archotecture yourself.
