### ISSUE TITLE
USB streaming is not available when docked

### ISSUE THREAD

**Issue by EmaxYuuki** [exelix11/SysDVR#36]
Is there going to be a fix for this in the future or is it at least planned?
What is the issue with USB streaming when docked?

**Comment by exelix11** [comment]
Switch OS doesn't support USB client mode while docked.

**Comment by EmaxYuuki** [comment]
will there ever be a workaround doe?

**Comment by exelix11** [comment]
Hard to say, how would you even connect it to a pc ? Idk if USB crossup wires would work and if windows does support it.
For max quality streaming while docked currently your best option is LAN with an USB adapter

**Comment by EmaxYuuki** [comment]
USB A to USB A works with tinfoil while docked so i guess id connect it just like that?

**Comment by exelix11** [comment]
Do you have any sources to back this claim ? From a quick google search it doesn't seem to be possible.
Also from [multiple sources](https://unix.stackexchange.com/questions/195765/is-usb-to-usb-data-transfer-between-two-linux-oses-possible) it seems that USB crossover is not even supported by most [OSes](https://unix.stackexchange.com/questions/239080/is-usb-3-0-to-usb-3-0-data-transfer-between-two-linux-oses-possible#comment692721_313569) and [usb chipsets](https://unix.stackexchange.com/questions/369597/how-to-setup-two-linux-hosts-connected-via-usb-3-0-crossover-cable-and-act-as-i#comment657114_369597).
I think you meant connecting to a USB hard drive but that's a totally different thing, as i said
> Switch OS doesn't support USB client mode while docked.

Connecting a usb drive is Host mode.

Either way tinfoil doesn't seem to be open source so i can't check.

**Comment by EmaxYuuki** [comment]
ill try it out in the morning and come back if it works, ive only heard that it works from other people never actually tried it myself
