### ISSUE TITLE
SysDVR ExtendedSocketException when streaming via RTSP

### ISSUE THREAD

**Issue by Asimm35818** [exelix11/SysDVR#37]
I've got the latest version of SysDVR and when I try to stream via RTSP it gives me an ExtendedSocketException

![image](https://user-images.githubusercontent.com/53124707/76003546-1e3a5700-5f00-11ea-8a04-944bbd857fe2.png)

These are the settings I used
![image](https://user-images.githubusercontent.com/53124707/76003608-34481780-5f00-11ea-919e-078303f5cb0f.png)

**Comment by exelix11** [comment]
Duplicate issue https://github.com/exelix11/SysDVR/issues/30
