### ISSUE TITLE
Error 2003-0008 on certain games with SXOS

### ISSUE THREAD

**Issue by exelix11** [exelix11/SysDVR#39]
Some users reported this issue when launching games and even adding a new wifi network when running sxos and SysDVR.
I'm not sure what is the cause nor how to fix it, as this doesn't happen on atmosphere i'm fairly confident that's sxos messing things up.
I opened this issue as a warning to other users and to gather more info about which games are affected and possibly workarounds.
Currently i don't plan on trying to fix this for multiple reasons, mainly i don't use sxos.

As stated in the readme I only support and test on atmosphere, SysDVR *does* work on other CFWs but your mileage may vary.

**Comment by Uzarel** [comment]
Currently running SysDVR fine on SX OS, but if I try to connect a Pro Controller and then launch a game, the console crashes

**Comment by DSchndr** [comment]
Could be because of the stealth mode because some games which want online connectivity crash the fw without sysdvr
I don't want a consoleban so i kinda want to keep it enabled :P

**Comment by exelix11** [comment]
Been like three years and sx is not relevant anymore, this can be closed.
