### ISSUE TITLE
MPV not launching with .bat in any mode.

### ISSUE THREAD

**Issue by CrumpThePenguin** [exelix11/SysDVR#43]
Saw another issue related to this but they closed it themselves without bothering to share what they fixed.

I had this working fine a few weeks ago but now it seems I've ruined something. When launching the .bat made from the GUI everything seems to connect fine but MPV doesn't launch. Upon running the .bat two cmd prompt windows open up, one of them is the SysDVR-Client.exe and the other is just a normal cmd prompt trying to open MPV, yet it never does. Below are the contents of my Launch_TCPBridge_RTSP_Both.bat

`start SysDVR-Client.exe bridge 192.168.1.133:6666 
"D:\Program Files\mpvplayer\mpv.com" rtsp://127.0.0.1:6666/`

I honestly would probably be fine just manually doing it but I can't figure out a way to just manually enter an IP into MPV. Pasting nor dragging a URL work. There doesn't seem to be any real reason for this to suddenly stop working either.

I recently downloaded some things like Docker which could be messing with my cmd prompt functions but I'm way too stupid to know if that's even possible. 

Edit: Trying to connect to rtsp://127.0.0.1:6666/ with VLC results in a bunch of data received messages in SysDVR-Client.exe but VLC never actually starts. Beginning to wonder if this is just me doing something dumb and MPV isn't starting because it's never able to actually connect.

**Comment by exelix11** [comment]
VLC doesn't work with the current sysdvr's rtsp implementation, all video players based on ffmpeg should work (mpv, ffplay, obs, probably others).

When the emply mpv windows appears, does sysdvr-client show connected or stays empty ?

To launch mpv manually you have to use the command prompt by typing `"D:\Program Files\mpvplayer\mpv.com" rtsp://127.0.0.1:6666/` (assuming the path you provided i correct). 
I _think_ you can also Win+R and type the command there.

**Comment by CrumpThePenguin** [comment]
Below is what both of the cmd prompts display. The cmd prompt attempting to launch mpvplayer seems to be working somewhat, because various hotkeys I assume are usually associated with mpvplayer are "working". For example, pressing S will show "Taking screenshot failed", pressing D will toggle "Deinterlace". Checking task manager it looks like mpvplayer.exe is indeed running, but a proper Window never seems to show up. I tried killing the task and manually launching mpv using the command line you gave me but it just does the same thing the .bat does with the hotkeys, including starting up mpvplayer.exe again in task manager.

![image](https://user-images.githubusercontent.com/24972809/77856121-a0920000-71ba-11ea-8a49-aa973e4bd144.png)


I've sat around for a few minutes before thinking that maybe it would eventually load but it seems that's not gonna work either. If I exit out of SysDVR while the mpvplayer CMD prompt is still open it displays this: 

![image](https://user-images.githubusercontent.com/24972809/77856242-7856d100-71bb-11ea-9f9c-a2cd2bb99095.png)

Not sure what I'm doing wrong at this point tbh. Could it be my Switch IP is wrong?

**Comment by CrumpThePenguin** [comment]
Wow. Seems I fixed it. Issue was that I had both my Switch IP and the port 6666 entered in the GUI when only the IP is needed. I changed that and suddenly it works. Doesn't really make sense since the contents of the .bats look the same but maybe I'm just stupid.

**Comment by exelix11** [comment]
FYI are you sure you were running a hame for the whole time ? Sysdvr and mpv were connected, it was just not receiving anything from switch, it could have been wrong ip address but it could also be that nothing is being recorded

**Comment by CrumpThePenguin** [comment]
Yeah I'm pretty sure. I was in the SysDVR app via homebrew menu by using
Animal Crossing as the injection. I never use applet mode and all of the
homebrew menu and apps usually work fine with SysDVR so that's what I've
been using to test. As soon as I got it working it popped up with SysDVR in
MPV so I'm not really sure what was going on.
