### ISSUE TITLE
Audio Not Working in OBS

### ISSUE THREAD

**Issue by TippyLion28** [exelix11/SysDVR#44]
I am streaming over 5GHz WiFi straight into OBS.
A few times I have managed to get audio to work, but now it refuses to work. When OBS picks up the RTSP stream, the audio briefly clips, then it goes silent. When the RTSP stream is closed, the audio plays briefly and the stream ends.

Audio works fine in mpv so I don't understand if this is an OBS issue or a SysDVR issue. Plz help. Willing to provide logs etc. if needed. Thanks :)

**Comment by exelix11** [comment]
Sounds more like a misconfiguration of OBS, does it have any reset config to default option ? 
Also i've used it rarely but iirc you can't hear audio in preview mode by design, if you try to record does the recorded file have audio ?

**Comment by TippyLion28** [comment]
By enabling monitor on the audio source, you can actually hear audio in preview mode. However, the audio meter isn't going up at all until I put my switch into sleep mode (thus ending the RTSP stream).
I'm sure it is not a configuration issue, as I haven't really touched the settings :/

**Comment by exelix11** [comment]
Any update on this? Just thought, could you have an outdated version of obs? Try downloading obs portable from portable apps that way you should have a clean configuration to try without having to change your current one

**Comment by TippyLion28** [comment]
Okay, I downloaded OBS from portableapps and made no configuration changes barring adding the media source and enabling audio monitoring. The exact same thing happens.

1. I disable and re-enable the media source which causes OBS to start recieving the stream from the switch. The audio clips briefly.
2. I let the stream continue for x amount of time
3. I put my switch into sleep mode, thus causing OBS to stop recieving stream data.
4. The video freezes briefly and some audio plays. Both the audio and video then stop.

Recorded the whole thing: https://streamable.com/l5nizv

**Comment by exelix11** [comment]
Will try the same setup in a bit in the meantime which streaming mode are you using ? Can you try a different one ? From the first message it looks direct rtsp, could you try tcp bridge?

**Comment by TippyLion28** [comment]
I am using direct RTSP from the Switch to OBS (Which in theory means less latency?)

**Comment by exelix11** [comment]
Just tried on obs and it works fine for me.
I actually noticed for the first time something: Today couldn't test with my usual wifi and had a much weaker one, at some points it did stop receiving audio like you're describing, it would resume every now and then though. Moving closer to the router fixed the issue. Could it be the same for you ?
> I am using direct RTSP from the Switch to OBS (Which in theory means less latency?)

Not necessarily, it depends on your connection and router, TCP bridge seems to perform better than direct RTSP sometimes, also it uses a different implementation of the RTSP server which may work better with certain players.

**Comment by TippyLion28** [comment]
So I've just tried the TCP bridge and it works so much better than direct RTSP. Audio works! And as far as I can see, there's less glitching etc! I think I'll be doing things this way from now on.

**Comment by exelix11** [comment]
Then connection quality was likely your issue, glad you solved

**Comment by duckyb** [comment]
Could you explain how to stream in TCP mode to OBS?

**Comment by exelix11** [comment]
Use TCP Bridge mode as explained in the guide, then use `rtsp://127.0.0.1:6666/` as media address in OBS

**Comment by duckyb** [comment]
But is it possible to use TCP mode with the usb connection? I only see how to do that with mpv, not with OBS

**Comment by exelix11** [comment]
Connecting via RTSP yes, tcp bridge mode is a different mode
