### ISSUE TITLE
MPV won't start

### ISSUE THREAD

**Issue by UneasyChicken** [exelix11/SysDVR#45]
Hello, I followed all the steps. When I press launch, I am only getting a blank terminal. I am trying to stream with the USB method

**Comment by exelix11** [comment]
This is useless. Please provide more information (eg is the driver installed correctly, do you get an error message, and so on)

**Comment by UneasyChicken** [comment]
For Switch :
its running on **9.1** with **atmosphere 0.10.5**
Airplane mode
on SysDVR is choose **Stream over USB**
I connect a USB to the computer

For Windows :
Installed drivers with **zadig**
Installed **.NET Core 3.1**
SysDVR-Client GUI settings 
![image](https://user-images.githubusercontent.com/63081752/78342922-bd577a80-75a2-11ea-97b2-c31e11d6f3e5.png)

After pressing launch I don't see any errors only the following 
![image](https://user-images.githubusercontent.com/63081752/78342995-de1fd000-75a2-11ea-9ac9-8e99624afa43.png)

**Comment by exelix11** [comment]
Launching should open two different terminals, one for the client and one for mpv, i assume the client is not working as mpv usually has the black terminal when it's not connecting. What happens if you just doulbe click Sysdvr-client.exe and then press enter to start the stream ?

**Comment by UneasyChicken** [comment]
When I double click it an icon appears for a millisecond in the taskbar but nothing happens.

**Comment by exelix11** [comment]
Weird, it should at least show an error. Try installing [ms vc++ libs](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) both x64 and x86

**Comment by UneasyChicken** [comment]
x86 was already installed, I installed and the x64 version. Nothing changed.

**Comment by exelix11** [comment]
If you open a cmd and run Sysdvr-client in it does it print anything ? what If you launch `dotnet --version` ?

**Comment by UneasyChicken** [comment]
Ok, so it seems that the wrong version was installed for the .NET Core it now opens the MPV player. But the stream is frozen it only displays the first scene and then it doesn't move. 
![image](https://user-images.githubusercontent.com/63081752/78346719-183fa080-75a8-11ea-8e5e-8e5572d448df.png)

**Comment by UneasyChicken** [comment]
Never mind it works fine it just has a 1 minute delay. Thank you for your help and your time.

**Comment by SwitchHElp** [comment]
Which .NET Core did you download? Could you please be specific in which one you downloaded?

**Comment by UneasyChicken** [comment]
By default it downloaded the x64 which didn't do for me. So I manually download the x86. I went for the SDK one.

**Comment by SwitchHElp** [comment]
Thank you very much

**Comment by exelix11** [comment]
FYI you just need the runtime, the sdk has extra features to develop apps
