### ISSUE TITLE
Terminating Video/Audio thread due to an exception

### ISSUE THREAD

**Issue by Migushthe2nd** [exelix11/SysDVR#46]
Errors in TCP Bridge (Relay network via RTSP)

![image](https://user-images.githubusercontent.com/22274715/78397201-236aee80-75f1-11ea-9287-51451edcbefe.png)
_No connection could be made because the target machine actively refused it_

**Comment by Migushthe2nd** [comment]
Hmm, you know what? You didn't see this...

**Comment by exelix11** [comment]
Could you translate the error message ? That's what you should try to solve.
For network modes common issues are:
- the wrong mode is selected in sysdvr settings
- your router actively prevents clients from communicating (eg a school network)
