### ISSUE TITLE
Can't get client to pop up

### ISSUE THREAD

**Issue by SwitchHElp** [exelix11/SysDVR#47]
When I go into SysDVR-ClientGUI.exe and set up everything then press launch the command prompt shows up for a sec then goes away. But leaves a cmd.exe window.

While if I go into SysDVR-Client.exe it just shows (What is shown below) but if I type in --help it closes out the windows.

SysDVR-Client - 3.0 by exelix
https://github.com/exelix11/SysDVR

Basic usage:
Simply launching this exectuable will show this message and launch the RTSP server via USB.
Use 'SysDVR-Client rtsp' to stream directly, add '--no-audio' or '--no-video' to disable one of the streams
To stream in TCP Bridge mode launch 'SysDVR-Client bridge <switch ip address>'
Command line options for the previous version are still available, you can view them with 'SysDVR-Client --help'
Press enter to continue.

**Comment by exelix11** [comment]
Sounds  pretty similar to issue #45 do the debugging steps explained there

**Comment by SwitchHElp** [comment]
I installed ms vc++ libs both x64 and x86 everything is the same but now when i try to open up SysDVR-Client.exe nothing pops up now.

When i try opening SysDVR-ClientGUI.exe then pressing launch it just opens a blank command prompt 

Lastly I unstalled my .net core and installed .net core runtime 3.1 x86 its still the same 

(Is there any way i can contact you better maybe via. social media or discord?)

**Comment by SwitchHElp** [comment]
Actually now after I rest my laptop and try to launch SysDVR-Client.exe I get this
![uhhhye](https://user-images.githubusercontent.com/63137247/78459908-5e146b80-7671-11ea-85e3-b69004e26bdb.png)

**Comment by exelix11** [comment]
Now it should be working.
Yes I'm on discord, you can find the invite link to my server at top of the readme of this repo

**Comment by exelix11** [comment]
Solved in DM, the issue seemed to be the .net runtime/vc++ libs, after the reboot  he mentioned SysDVR was working properly.
