### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by icxruus** [exelix11/SysDVR#49]
i dont know if i'm doing something wrong or i am missing something but i've read that there is support on MacOS but i'm unable to make the client work
is it because macOS is not supported or do i have to make a virtualbox of windows?

**Comment by exelix11** [comment]
Mac should be supported, do you get stuck at a specific step?

**Comment by icxruus** [comment]
i am not able to open the client

**Comment by exelix11** [comment]
That is very generic.
You're supposed to install net core runtime 3, then launch it from a terminal by doing `dotnet Sysdvr-client.dll`

**Comment by icxruus** [comment]
ok, thanks
i achieved to open it and i arrived here
<img width="852" alt="image" src="https://user-images.githubusercontent.com/60195088/79046136-5d4e7d00-7c0f-11ea-9269-152adaefbdbd.png">


I install the divers and mpv through homebrew but what i write
_mpv rtsp://127.0.0.1:6666/_
the terminal keeps stuck here
<img width="864" alt="image" src="https://user-images.githubusercontent.com/60195088/79046162-85d67700-7c0f-11ea-94a2-471a737f6907.png">

**Comment by exelix11** [comment]
you're not supposed to type there, after it tells you to connect if you press enter it will close.
You have to open another terminal and launch mpv from there.
