### ISSUE TITLE
Audio delay between audio and video (USB)

### ISSUE THREAD

**Issue by shakkar23** [exelix11/SysDVR#50]
Not sure if this is fixable, but ive tried everything, I pressed Q about 50 times now, waited 3 seconds, and checked if it synced up, used mpv.com and mpv.exe (they both work surprisingly, ive tried to sync up the audio in Streamlabs, nothing works, I was able to sync them up once, but it was just a bug where the video decided to delay a bit more than usual, and the audio synced up because of it. other than that one time, that I cannot replicate, there was never a time where it syncs up, and again, somehow Streamlabs audio manual sync doesnt work either.

**Comment by exelix11** [comment]
If it asks you to press Q you're using the old low-latency unsynced mode. If you want proper audio-video syncronization you have to use the RTSP mode. Now it's the default mode you can just double click sysdvr-client.exe and press enter, If you're using the GUI you can also select rtsp in the usb section.
