### ISSUE TITLE
i did everything step by step but mpv won't open

### ISSUE THREAD

**Issue by SuckRoot** [exelix11/SysDVR#51]
after launching batch file client wont open
![Capture](https://user-images.githubusercontent.com/63557353/79076554-f5716280-7cf2-11ea-946a-0409825cf39b.PNG)

**Comment by SuckRoot** [comment]
dotnet SysDVR-Client.dll video mpv "C:\switch\mpv.com"

i did this and it worked thanks

**Comment by exelix11** [comment]
Glad you solved on your own. 
FYI you're using the old streaming mode, you can use `dotnet Sysdvr-client.dll rtsp` to use the rtsp mode from USB
