### ISSUE TITLE
Very laggy when Network RTSP mode on Mpv android

### ISSUE THREAD

**Issue by CommicKick69ing** [exelix11/SysDVR#53]
Even though I have good internet speeds its very laggy when I Network RTSP mode on Mpv android. Is there any way to elimate the lag or use another app that works better?

**Comment by exelix11** [comment]
Not that I know of, unfortunately wifi has a lot of interference related problems especially on low-powered devices. For streaming between switch and a phone you need a good router and both of them have to be close to it, possibly via 5ghz wifi or lan

**Comment by CommicKick69ing** [comment]
I am doing it on a 5ghz network standig next to the router

**Comment by exelix11** [comment]
Unfortunately this is related to your setup and i can't really help you, you could try having a pc in the middle and streaming via tcpBridge.
