### ISSUE TITLE
Blank Screen after Launch!

### ISSUE THREAD

**Issue by LikeKev** [exelix11/SysDVR#54]
Hey, I have a BIG Problem!

I have done everything of the Setup Guide here on GitHub!
But if I start The Gui and select MPV and will start then the programm starts a black screen but the screen is blank! (and only one Window!)
Please Help ....

**Comment by exelix11** [comment]
Uhm it seems i totally missed this issue or did you ask on the discord server as well ? Either way with the release of [SysDVR 4.0](https://github.com/exelix11/SysDVR/releases/latest) also updated the the [troubleshooting section](https://github.com/exelix11/SysDVR#troubleshooting) of the guide, go check it out if you still have issues. If that still doesn't work for you ask on discord or open another issue.
