### ISSUE TITLE
[Bug] SysDVR does not set __nx_fs_num_sessions, and thus consumes more sessions than it needs.

### ISSUE THREAD

**Issue by SciresM** [exelix11/SysDVR#58]
**Describe the bug**
SysDVR does not set `__nx_fs_num_sessions`, and thus consumes more fs sessions than required.

**To Reproduce**
Observe the contents of `main.c`.

**Expected behavior**
SysDVR should set `__nx_fs_num_sessions` to 1, so that it does not unnecessarily consume an extra two FS sessions.

There are a fixed number of FS sessions available to the system; official applications use 3, certain system modules (NCM, settings) use 2, and all other sysmodules use 1.

When all FS sessions are consumed, the FS system module kills itself and the system crashes.

It's good practice to only consume the FS sessions you need, so that your system module can better co-exist with the rest of the OS.

**Setup information**
N/A

**Additional context**
N/A

**Comment by exelix11** [comment]
👍 Done, thanks for reporting.

Has this been causing problems ? Do you think it requires an hotfix or can it wait until the next release ? 

Either way i think it may be worth to add a note about this in the [sysmodule template](https://github.com/switchbrew/switch-examples/blob/master/templates/sysmodule/source/main.c) as for people not familiar with FS internals this doesn't seem to be documented anywhere.

**Comment by SciresM** [comment]
@exelix11 Issue was prompted by a user posting a crash report that I traced to the FS sysmodule killing itself due to out-of-sessions. Dunno, when's your next release targeted? The user in question wasn't using SysDVR, but it prompted me to start looking at common sysmodules to see if they were configuring fs correctly.

**Comment by exelix11** [comment]
> Dunno, when's your next release targeted? 
Don't have anything planned right now, guess i'll wait a one or two weeks to get more bug reports and then make a minor update
