### ISSUE TITLE
USB Device not found on mac

### ISSUE THREAD

**Issue by MarleyLua** [exelix11/SysDVR#59]
I'm on macOS Cataline, 10.15.4
and this occures when i press enter afet use dotnet sysdvr-client.dll and all the text that comes after it 
Unhandled exception. System.Exception: Device not found
   at SysDVRClient.UsbHelper.GetSysDVRDevice()
   at SysDVRClient.UsbHelper.GetForInterface(StreamKind iface)
   at SysDVRClient.UsbStreamingSourceBase..ctor(StreamKind kind)
   at SysDVRClient.UsbStreamingSourceLibUsb..ctor(StreamKind kind)
   at SysDVRClient.UsbHelper.MakeStreamingSource(StreamKind stream)
   at SysDVRClient.Program.Main(String[] args)
zsh: abort      dotnet /Users/marleylua/Downloads/SysDVR-Client-1/SysDVR-Client.dll

**Comment by exelix11** [comment]
Did you enable usb mode in sysdvr with the settings app ?

**Comment by MarleyLua** [comment]
I did

**Comment by exelix11** [comment]
Do you have any utility to check whether it's being detected ? On linux i'd use lsusb but not sure it's available on mac.  You should see a device called `SysDVR (Nintendo Switch)`

**Comment by MarleyLua** [comment]
Yup, i used "system_profiler SPUSBDataType" and is detecting  SysDVR (Nintendo Switch)

**Comment by exelix11** [comment]
Try running sysdvr-client as root. On my ubuntu VM i need that or else it doesn't work but it prints an error about permissions.

**Comment by MarleyLua** [comment]
I just tried and still says me the same thing;;;;

**Comment by exelix11** [comment]
Unfortunately can't help you, I've had confirmaton that previous versions work on mac, guess you can try 3.0 and check if that works but don't think it will as it seems it's not detecting the console at all.
Report back here if you manage to find a solution.

**Comment by MarleyLua** [comment]
Okey Thank you tho! i will try to fix it

**Comment by daitro** [comment]
@MarleyLua could you make it work?

**Comment by zurce** [comment]
hey @exelix11 , it might be related on how power is handled through mtp-server-nx. 

When using `mtp-server-nx` something that I see sometimes is that if using usb c to usb c, if my laptop has less battery than my switch, it will try to charge from my switch, to fix it, I open the mtp-server-nx nro, lock my switch and unlock it, then android device manager shows my switch. 

I did some testing with SysDVR USB mode and I'm seeing similar results, if I lock and unlock my switch , the `system_profiler SPUSBDataType` command in terminal will show 


```
   USB 3.1 Bus:

      Host Controller Driver: AppleIntelCNLUSBXHCI
      PCI Device ID: 0xa36d 
      PCI Revision ID: 0x0010 
      PCI Vendor ID: 0x8086 

        SysDVR (Nintendo Switch):

          Product ID: 0x3006
          Vendor ID: 0x057e  (Nintendo Co., Ltd.)
          Version: 1.00
          Serial Number:  https://github.com/exelix11/SysDVR 
          Speed: Up to 480 Mb/s
          Manufacturer: exelix
          Location ID: 0x14200000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0
```


and I'm able to start SysDVR-Client.dll usbmode, but the moment my switch connects , it switches to charging and my terminal shows the following log over and over.

```
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): no connection to an IOService (code = 0xe00002c0) 
```


on the other side, if I connect using a USB C dongle and a USB A to USB C , I'm able to get the SysDVR USB mode working, but with significant delay
