### ISSUE TITLE
Goldleaf do not work and cause black screen while sysDVR is running

### ISSUE THREAD

**Issue by ELY3M** [exelix11/SysDVR#6]
I have to choose this sysmodule and using goldleaf :(  
if need to use Goldleaf, I would have to delete sysDVR sysmodule and reboot my switch via reboot to payload.  I also told about it in XorTroll's server and told how to fix the issue on their github.

**Comment by exelix11** [comment]
Unfortunately it seems only one homebrew can use the usb service at the same time.
In theory it's possible to have multiple but when one exits will close the usb handle causing all connections to reset, thus breaking other processes as well.
Next version will include an homebrew that allows switching modes without having to reboot.
There's already an issue open for this https://github.com/exelix11/SysDVR/issues/5 so i'm closing this one
