### ISSUE TITLE
'Terminating Video Thread due to' bug

### ISSUE THREAD

**Issue by StrawberryMahjong** [exelix11/SysDVR#62]
**Describe the bug**
```
Terminating Video thread due to System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::ffff:192.168.0.16]:9911
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at SysDVRClient.Exten.ConnectAsync(TcpClient tcpClient, String host, Int32 port, CancellationToken cancellationToken)
   at SysDVRClient.TCPBridgeSource.WaitForConnection()
   at SysDVRClient.StreamingThread.ThreadMain()
```

**To Reproduce**
I have no clue man, I just had a compatible game open, launched it with the GUI so I can use it over WiFi, and that happened before I could even connect.

**Expected behavior**
For it to launch and connect properly.

**Setup information**
 - PC OS: Windows 10 x64
 - Console firmware: 9.2.0 (Can't update cause my switch is banned.)
 - Custom firmware name and version: Atmosphere 0.12.0
 - SysDVR version: 4.0

**Comment by exelix11** [comment]
Uhm the `ExtendedSocketException` message should not show anymore, either way the error description is clear `No connection could be made because the target machine actively refused it` it means one or more of the following:
- SysDVR isn't running on your console, you can check by opening the settings app
- SysDVR is not in the right mode (TCP bridge in your case)
- 192.168.0.16 is not the right IP
- Your router is blocking communication between clients, common in public hotspots

**Comment by StrawberryMahjong** [comment]
I've made sure that SysDVR is running on my console, and that it's in the right mode. The IP _should_ be right as I took it directly from the WiFi settings on the Switch. As for the router, I'm not 100% sure on that, as it could just be the awful WiFi adapter in my PC, it's so bad it can't even download a 200 MB zip file without failing like 4 times. I'm gonna try using my phone with WiFi Tethering to see if that works.

**Comment by exelix11** [comment]
If you do `ping 192.168.0.16 ` in a cmd does the console answer ? You can also try disabling windows firewall but i'm not sure that's the issue here.

**Comment by StrawberryMahjong** [comment]
Still same error.
FTPD works, and so did the ping.
`Pinging 192.168.0.16 with 32 bytes of data:
Reply from 192.168.0.16: bytes=32 time=37ms TTL=63
Reply from 192.168.0.16: bytes=32 time=38ms TTL=63
Reply from 192.168.0.16: bytes=32 time=59ms TTL=63
Reply from 192.168.0.16: bytes=32 time=4ms TTL=63

Ping statistics for 192.168.0.16:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 4ms, Maximum = 59ms, Average = 34ms`
I tried disabling my antivirus but it didn't do a thing. I'll try windows firewall just in case.

**Comment by StrawberryMahjong** [comment]
Disabling Windows Firewall did nothing either. This is really strange.

**Comment by exelix11** [comment]
if ftp woks the router isn't an issue and likely the firewall isn't either.
Only thing i can think of is that your sysdvr version is different than the client one, you need both to be 4.0. Each version of the sysmodule is compatible only with its client.

**Comment by StrawberryMahjong** [comment]
That shouldn't be the case as I downloaded the client files and the SysDVR files in the same minute but I'll try replacing the files.

**Comment by StrawberryMahjong** [comment]
Nothing. Absolutely nothing.
New cilent didn't work, new SysDVR didn't work... Still the same error.

**Comment by exelix11** [comment]
Note that if you replaced the sysmodule on console via ftp you have to reboot for the changes to take effect

**Comment by StrawberryMahjong** [comment]
I didn't use FTP, I plugged the SD Card into my PC.

**Comment by exelix11** [comment]
Then I don't know what could be the issue here.

Confirm you're running the right version by launching sysdvr settings, you should see v4 on the top, same with the client. 

If you have time to experiment, could you try direct rtsp mode? It's just an idea to test communication between pc and sysdvr

Guess if you manage to find a fix post it here.

**Comment by StrawberryMahjong** [comment]
Confirmed it's v4, and I've been using RTSP this whole time, probably should've mentioned that haha.
I'll try it on TCP Bridge mode just in case, if that doesn't work then I have not a single clue on what I should do.

**Comment by StrawberryMahjong** [comment]
TCP Bridge mode works, so that's a bit weird.

**Comment by exelix11** [comment]
Uhm... The error you mentioned in the first post is for tcp bridge, I think you're mixing up the modes.
Direct rtsp doesn't need the client to work. Please read carefully the guide.

**Comment by StrawberryMahjong** [comment]
Wait what

**Comment by StrawberryMahjong** [comment]
OOOOOOOH MY GOD I'M SO STUPID LOL.
Thank you so much for the help anyway, carry on with the great work!
