### ISSUE TITLE
Can’t pass through mic audio

### ISSUE THREAD

**Issue by dewuxx** [exelix11/SysDVR#65]
I notice that there is a delay, which is expected, and I want to record or stream but my audio is not in sync with my switch audio or gameplay, and I was wondering if there was a way to make my mic work for this application so it’s all in sync.

**Comment by dewuxx** [comment]
Actually I found on OBS if I set it to record 2 audio tracks and have 1 track be my game and the second be my mic that’s connected to my pc I can just line my audio up with the delay sense they are 2 different tracks.

**Comment by exelix11** [comment]
This is a configuration issue with obs, not related to sysdvr, and yes I think that's the only way of doing that.
