### ISSUE TITLE
[Help] Got error when launching: "Unhandled exception. System.Net.Sockets.SocketException (10013)"

### ISSUE THREAD

**Issue by ZawyNesio** [exelix11/SysDVR#67]
After all, please forgive my English.

**Where do you get stuck ?**
When i execute the GUI.exe the cmd prompted window say the following: 
![imagen](https://user-images.githubusercontent.com/68130994/87208133-4fbe9700-c2d3-11ea-8328-19f75db45873.png)
I tried to run the program as admin, with firewall and antivirus turned off and got the same error.
**Note that this happens as well as via  WIFI not only on USB**

**Setup information**
 - Windows 10 release 1909
 - emmNand with 10.0.4
 - Atmosphere 0.13.0
 - SysDVR 4.0.1

**Additional context**
The drivers to run over USB are correctly installed
![imagen](https://user-images.githubusercontent.com/68130994/87208611-c14b1500-c2d4-11ea-8c3d-81be1951f79b.png)

Microsoft Core 3.1.5 is installed and updated

**Comment by exelix11** [comment]
I think sysdvr fails to create a socket on it's default port 6666. This can be because another program is using it or a firewall prevents it.
You can check which programs are using which port with `netstat - bn` in an admin command prompt.
You can also change sysdvr port by adding `--rtsp-port port_number` at the end of the sysdvr-client command, this option is not available in the gui.

**Comment by ZawyNesio** [comment]
hi, first thanks for your answer. 
Now returning to this topic, y already tried to turn off the firmware and antivirus also, but nothing changes. The port is not in use by another process or aplication and when y run the noGUI SysDVR after pressing "Enter to continue" it gives me the same error and the windows close itself.
**Antivirus y Firewall are down**
![imagen](https://user-images.githubusercontent.com/68130994/87227206-12075000-c35f-11ea-98cd-54d94af6e550.png)

**Getting the same error and window close**
![imagen](https://user-images.githubusercontent.com/68130994/87227202-01ef7080-c35f-11ea-9264-ff66b01daf42.png)

**List of connected TCP/IP services**
![imagen](https://user-images.githubusercontent.com/68130994/87227324-e46ed680-c35f-11ea-92c8-90e7ee6aa072.png)

**Comment by exelix11** [comment]
The list could be longer than that screen, anyway try a different port by opening a cmd in the client path and running `Sysdvr-client.exe --rtsp-port 9999` , any number greater than 1024 and smaller than ~65000 is a valid port, by default 6666 is used.

**Comment by ZawyNesio** [comment]
Yes the list of TCP/IP si pretty longer but any one show to use the 6666 port, anyway i follow your indications and tried to change the port... this is the answer of the cmd (running as admin).

**Tried to change 3 different ports but this is the answer of system.
![image](https://user-images.githubusercontent.com/68130994/87232432-a506b100-c384-11ea-93fd-82b2cbce1eb4.png)
**NOTE, i ve tried more than this 3 ports just to ilustrate the results.**

**Comment by exelix11** [comment]
My bad, the command should be `sysdvr-client usb --rtsp-port 9999`, you could have read the command description though

**Comment by ZawyNesio** [comment]
yep, sorry I was lazy in that. 
Following your instructions I managed to solve this using the port 8888, other ports like 9999 or 7777 have the same issue of 6666, 
Thanks a LOT dude. I close this thread as SOLVED.

**Comment by exelix11** [comment]
Glad you solved, still it's weird that so many random ports are in use on your pc, if i were you I'd look into that. Also FYI using 4 equal digits is just to remember it, you can use any number
