### ISSUE TITLE
[Bug] Failed to connect to SysDVR, is the module set up properly?

### ISSUE THREAD

**Issue by ferax4227** [exelix11/SysDVR#68]
I already followed all steps and still got this message on the switch. Im using SX OS V3.0.3 on switch lite

![image](https://user-images.githubusercontent.com/50665721/87228878-90bdb680-c37a-11ea-9959-4f583f50c32c.png)

**Comment by exelix11** [comment]
If you just copied the files reboot the console and wait about 30 seconds before launching the settings app.

**Comment by hj19957158** [comment]
me too,I also instant others plug-in

**Comment by ferax4227** [comment]
I forgot i have to save the files on the sxos folder and not the atmosphere
