### ISSUE TITLE
MPV player only opens once with the .bat before having to restart my entire computer

### ISSUE THREAD

**Issue by CrumpThePenguin** [exelix11/SysDVR#69]
Not really sure what else to say. It seems to launch fine once but after that I can't get it to launch again. If I restart my computer I can get it to launch once again before having to restart if the stream messes up and starts buffering forever for seemingly no reason or if I accidentally go to home screen. mpv's terminal is just a blank black screen.

I tried connecting to the rtsp with VLC and the terminal gives off lines like it's connected but nothing shows on VLC. Is there an alternative that works reliably?

Edit: Also when trying to connect to mpv manually (pictured below) the Window doesn't pop up but it shows up in my task manager. Closing the window will cause the process to also go away in task manager. This is the same thing that happens when using the bat. I had a similar issue a few months ago that just seemed to resolve on its own but I think it was just a fluke tbh.
![image](https://user-images.githubusercontent.com/24972809/87835496-e69ace80-c852-11ea-98f4-469cd8914edf.png)

**Comment by exelix11** [comment]
It seems  i accidently missed the notification about this issue, sorry about that.
Please try with latest update and open a new issue if you still face this problem.
