### ISSUE TITLE
[Bug] Crash after open other homebrew app when stream mode over usb

### ISSUE THREAD

**Issue by WahyuAdyP** [exelix11/SysDVR#72]
**Describe the bug**
When SysDVR stream over usb mode, opening other homebrew app that need usb (ex: nxmtd, [awo installer/ tinfoil] install via usb) making crash 

**To Reproduce**
1. a. Using SysDVR-USB-Only.zip (i think because automatically stream over usb mode after boot)
b. Select stream over usb
2. Launch other homebrew app that need usb like nxmtp

**Expected behavior**
When strem over usb, no make crash when launch other homebrew app

**Setup information**
 - PC Os: Windows 7 x64
 - Console firmware 10.0.4
 - Custom firmware name and version Atmosphere 0.4.0
 - SysDVR version 4.0.1

**Additional context**
![IMG_20200721_180432](https://user-images.githubusercontent.com/35764492/88053307-c6864a80-cb85-11ea-9e60-761948af3392.jpg)

**Comment by exelix11** [comment]
Multiple homebrew can't use USB at the same time. Usb only version is only for people who use many memory hungry sysmodules at the same time.
The full version of sysdvr has a settings app where you can disable USB access to be able to use other USB homebrew.

**Comment by durtydub** [comment]
How did you get the SysDVR Client to work on Windows 7??? I try to install the USB driver but I get an error every time saying “The INF file you selected does not support this method of installation”
