### ISSUE TITLE
Problem when streaming via USB

### ISSUE THREAD

**Issue by ANOUNYMOSGAMER** [exelix11/SysDVR#74]
**Bug Description**
I followed the guide and even looked at the bug section from here, only to find that someone else had encountered this before and it went unsolved without any solution for it. What happened is that SysDVR wrote this upon launching with "SysDVR-ClientGUI.exe" ;

libusb: error [enumerate_hcd_root_hub] program assertion failed - HCD 'PCI\VEN_8
086&DEV_1E31&SUBSYS_100D1043&REV_04\3&11583659&0&A0' child not found
Unhandled exception. System.Exception: Device not found
   at SysDVRClient.UsbHelper.GetSysDVRDevice()
   at SysDVRClient.UsbHelper.GetForInterface(StreamKind iface)
   at SysDVRClient.UsbStreamingSourceBase..ctor(StreamKind kind)
   at SysDVRClient.UsbStreamingSourceWinUsb..ctor(StreamKind kind)
   at SysDVRClient.UsbHelper.MakeStreamingSource(StreamKind stream)
   at SysDVRClient.Program.Main(String[] args)
 
followed by a popup message saying .NET Core Host has stopped working

**To Reproduce**
I honestly couldn't tell, I followed the inhouse guide fully (at least, to my best)

**Expected behavior**
SysDVR to work as it's supposed to

**Setup information**
 - PC Os: Windows 7 x64
 - Console firmware: 10.0.4
 - Custom firmware name and version: Atmosphere 0.12.0
 - SysDVR version 4.0.1

**Comment by exelix11** [comment]
Mh not sure, i'd say make sure SysDVR on your console is in USB mode, you can set that from the SysDVR-settings app, then unplug and plug back into your pc, sometimes it's needed after installing the driver, if still doesn't work try rebooting your pc.
If you're using an USB hub that may interfere, try connecting to the main USB ports of your pc.

**Comment by ANOUNYMOSGAMER** [comment]
I have set SysDVR to stream over USB from homebrew (SysDVR-settings app), I've also double-checked from device manager whether SysDVR is recognized whenever I plug my Switch to the pc, I don't use a USB hub. I'll try rebooting my pc in a sec, will see if that'll do it....

**Comment by zurce** [comment]
@ANOUNYMOSGAMER  can you tell us a couple of things?

How are you connecting your switch to your pc? is it usb c to usb c? 

can you try locking and unlocking your switch once the usb streaming has been enabled and see if it makes a difference?

**Comment by ANOUNYMOSGAMER** [comment]
Yes, Switch connected to pc via USB c to USB c. 
Pray tell, how does one "lock, then unlock" the Switch? Or do you mean like, turning the Switch to sleep then turning it on hence "unlock" it?

**Comment by zurce** [comment]
> Yes, Switch connected to pc via USB c to USB c. 
> 
> Pray tell, how does one "lock, then unlock" the Switch? Or do you mean like, turning the Switch to sleep then turning it on hence "unlock" it?

Yes put the switch to sleep and wake it up basically 

As well , I'm pretty the issue here is the usbc protocol switching to charge mode when it shouldn't, try connecting with a usb A cable (even if you have to use a dongle) since that will not make the console switch to charge mode

**Comment by ANOUNYMOSGAMER** [comment]
I'll give the unlock in method a try in a bit, but I won't be able to confirm USB A with type C dongle for a while.
Will confirm after I try both method

**Comment by exelix11** [comment]
Closing this as it seems to be related to https://github.com/exelix11/SysDVR/issues/81
