### ISSUE TITLE
[Help] Are there any better android app that work with Sysdvr

### ISSUE THREAD

**Issue by CommicKick69ing** [exelix11/SysDVR#77]
MpV-android has to much stream lag to be usable in any situation. Im asking are the any better android app that work with Sysdvr that have alot less stream latency?

**Comment by exelix11** [comment]
It all boils down to configuring your player for low latency, unfortunately mpv for android doesn't expose any simple UI. SysDVR uses RTSP which is a common protocol so other players like VCL should support it.

I'm closing this as it's not a SysDVR issue and android is not currently a supported platform, feel free to keep using this issue to report your experience with other players.

**Comment by DevanWolf** [comment]
NextPlayer should work.
