### ISSUE TITLE
Video and Audio Format

### ISSUE THREAD

**Issue by Natakout** [exelix11/SysDVR#8]
Hello,

would it be possible to know the video and audio format,
OBS need to know the format to turn it into a video or audio

Love your Project

**Comment by exelix11** [comment]
Video stream is composed of raw h264 nal units aka what you usually find in mp4 files but without the mp4 container wrapping it, audio stream is uncompressed audio samples 16bits 48kHz stereo.\
Not sure you can directly feed that into obs, if it does support it you can use tcp mode from UsbStream to relay the data to it, if your intent is streaming you should look into ffmpeg command line.\
About streaming i've looked into that a bit and will totally try to support it directly in the future, from what i've seen both twitch and youtube already support h264 video so in theory it's possible to stream the video data without having to re-encode.
The audio stream has to be encoded to AAC but you'll have to find a way to mux it with the video, i've seen an user doing this with named pipes on linux.\
From what i've seen most people just stream mpv's window, guess for now that's enough.

**Comment by DewGaming** [comment]
For those that want to just record straight from the switch to a file, could you list this in the main page.  This "issue" was the only place I saw this info about how to import the audio files

**Comment by exelix11** [comment]
Another note on this, when converting the h264 video file with ffmpeg make sure to set the framerate to 30 as h264 doesn't carry the information it will default to 25 causing a slightly slower video that won't match with the audio. The option is `-r 30` and not `-framerate 30` as it could seem.
