### ISSUE TITLE
`child not found` error for USB streaming

### ISSUE THREAD

**Issue by AngeryCinnabon** [exelix11/SysDVR#81]
So i've set up SysDVR and used it for tcp mode perfectly fine, but whenever i try to stream via usb i get this error.

`libusb: error [enumerate_hcd_root_hub] program assertion failed - HCD 'PCI\VEN_1B73&DEV_1100&SUBSYS_11001B73&REV_10\4&1741AB47&0&0048' child not found
Unhandled exception. System.Exception: Device not found
   at SysDVRClient.UsbHelper.GetSysDVRDevice()
   at SysDVRClient.UsbHelper.GetForInterface(StreamKind iface)
   at SysDVRClient.UsbStreamingSourceBase..ctor(StreamKind kind)
   at SysDVRClient.UsbStreamingSourceWinUsb..ctor(StreamKind kind)
   at SysDVRClient.UsbHelper.MakeStreamingSource(StreamKind stream)
   at SysDVRClient.Program.Main(String[] args)`
I have used zadig to set the usb drivers and they show up as SysDVR - Audio and SysDVR - Video. is there something i'm doing wrong?

**Comment by exelix11** [comment]
Likely configuration issue, try the suggestions from these issues with the same error. https://github.com/exelix11/SysDVR/issues/18 https://github.com/exelix11/SysDVR/issues/74

**Comment by AngeryCinnabon** [comment]
Tried all that and still didn't work for me, could the fact i'm using SX Core Emunand be the problem? i might try this on my old day 1 switch and see how it goes.

**Comment by exelix11** [comment]
Are you sure you installed the correct driver ? Try enabling `force libusb backend` in the GUI. Make sure windows detects SysDVR in device manager.

**Comment by AngeryCinnabon** [comment]
Still no luck, windows detects sysdvr like this so i assume that isn't an issue.
![image](https://user-images.githubusercontent.com/24904313/93928278-0f729080-fce8-11ea-9dbd-edbcaf7288b1.png)

Honestly i might just give up at this rate, considering every other streaming method on sysdvr works...

**Comment by exelix11** [comment]
The user solved the issue by switching to a different PC, still no answers about this specific error message. Reopening the issue to track reports.

**Comment by eggnacho** [comment]
Hi.

The usb method was working for me yesterday but i am getting the same error today.

![image](https://user-images.githubusercontent.com/98435995/151084119-2a2950cc-8806-4e7d-a574-2f904d7ce0d4.png)

**Comment by eggnacho** [comment]
Hello again.

I did some research and found this post:

https://github.com/exelix11/SysDVR/issues/109#fromHistory

Found that I had a device that was an "unknown device"

Referred to this post to figure out what the device was:
https://www.dell.com/support/kbdoc/en-ca/000151898/how-to-identify-an-unknown-device-in-device-manager#fromHistory

Found that my hardware id was "usb asmediausbd_hub&vid_040e&pid_0100&rev_0000"

Googled the hardware ID and found [here](https://www.driveridentifier.com/scan/usb-root-hub/download/89949417/678B8774B6D145AEA790A2EB94CF15DA/USB%5CASMEDIAUSBD_HUB%26VID_040E%26PID_0100) that the device was USB Root Hub Driver for ASUSTeK.

Did more research and found https://www.reddit.com/r/Windows11/comments/phbhdy/usb_31_port_died_after_update/ and i just so happened to update to windows 11 last night.


In the end, it was a driver issue with my usb ports. I assume other people with this issue also have an unknown device in their device manager. Updating the driver would potentially fix their issue as well.

**Comment by eggnacho** [comment]
Upon further looking, 
![image](https://user-images.githubusercontent.com/98435995/151094006-45900689-e908-4b93-84c5-fa4e2d16fdf6.png)
The Compatible Id matches exactly what the error shows. Im almost certain this is the fix for anyone having this issue

**Comment by AngeryCinnabon** [comment]
Well damn, I'll try this ASAP and see if this works. Pretty nice birthday gift to see a solution to this.

**Comment by eggnacho** [comment]
Happy birthday! Lmao. Let me know if you need some help finding your drivers.
