### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by iGotenz** [exelix11/SysDVR#84]
https://user-images.githubusercontent.com/30407192/95192419-786f0380-07d2-11eb-9ed8-8de3d1de891d.png

I keep getting this error with two pc's and have no idea what to do. please help

**Comment by exelix11** [comment]
Probably Sysdvr on the console is set to the wrong mode, change it as explained in the [relevant page of the guide](https://github.com/exelix11/SysDVR/wiki/Network-TCP-Bridge-mode):
> To use this mode select `Stream over TCP Bridge` in SysDVR Config.

**Comment by iGotenz** [comment]
Thanks, that fixed it.
