### ISSUE TITLE
[Help] Error while launching mpv

### ISSUE THREAD

**Issue by davidullo** [exelix11/SysDVR#88]
When I use the GUI and launch it in TCP bridge mode I get two windows, and one of them gives me this error:
```
Warning, two config dirs found:
   C:\Users\xxxxx\AppData\Roaming/mpv (main)
   C:/Users/xxxxx/Downloads/mpv-x86_64-20201025-git-49d6a1e (bogus)
You should merge or delete the second one.
```
The second row is the one where the mpv.com file is located, can't understand what the first row is about. If I delete the first row's folder (which contains nothing) my system keeps creating it again.

This is what I get on the second window:
```
C:\Users\xxxxx\Downloads\SysDVR-Client>SysDVR-Client bridge 192.168.1.232
SysDVR-Client - 4.0.1 by exelix
https://github.com/exelix11/SysDVR

Starting stream, press return to stop
If the stream lags try pausing and unpausing the player.
Now streaming via RTSP on port 6666
Connect with your player to rtsp://127.0.0.1:6666/
Terminating Video thread due to System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato. [::ffff:192.168.1.232]:9911
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at SysDVRClient.Exten.ConnectAsync(TcpClient tcpClient, String host, Int32 port, CancellationToken cancellationToken)
   at SysDVRClient.TCPBridgeSource.WaitForConnection()
   at SysDVRClient.StreamingThread.ThreadMain()
Terminating Audio thread due to System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato. [::ffff:192.168.1.232]:9922
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at SysDVRClient.Exten.ConnectAsync(TcpClient tcpClient, String host, Int32 port, CancellationToken cancellationToken)
   at SysDVRClient.TCPBridgeSource.WaitForConnection()
   at SysDVRClient.StreamingThread.ThreadMain()
Connection from 127.0.0.1:52624
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://127.0.0.1:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestPlay
Connection from 127.0.0.1:52765
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://127.0.0.1:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestPlay
```
I tried using different mpv version, same story. I can get the stream to work with RTSP (so without the client) but it freezes after few seconds. Can't find an answer anywhere else.

**Comment by exelix11** [comment]
the mpv message is unrelated, are you the same person who asked about it on discord a few days ago ? Either that or it's a bug introduced with latest mpv cause this is the second time i heard about that.
Your issue is explained in the error message sysdvr-client spits out
> Impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato. [::ffff:192.168.1.232]:9911

It means your console is not listening for requests on the TCP bridge port. 
Most likely you didn't switch mode from the sysdvr settings app, quoting from the [guide](https://github.com/exelix11/SysDVR/wiki/Network-TCP-Bridge-mode)
> To use this mode select `Stream over TCP Bridge` in SysDVR Config.

**Comment by davidullo** [comment]
No I'm not. Could you link me the Discord server so I can look for a solution there? By the way, my console was on the correct mode, I was switching back and forth while trying different approaches.

**Comment by exelix11** [comment]
[Here](https://discord.gg/rqU5Tf8).
Still there's basically only me answering questions there so idk what will you find.

More troubleshooting:
- Were you in a game that supports video recording ?
- Did you get back to the game after switching modes ?
- Is the IP address correct ?

**Comment by davidullo** [comment]
Okay so I changed the mpv version (now I'm using the older 0.31.0) and I get no errors on both of the screens, so problem solved. Although, I noticed that a particular game (Pokemon Sword) lets me record the screen while playing by pressing the record button, but it only lets me stream it on its menus (intro of the game and inventory), and as soon as I load my save or I switch back from the inventory the stream freezes.

**Comment by exelix11** [comment]
Pokemon will go into local wireless mode when in game to find other players nearby and that will disconnect from the wifi. Workaround is to use ldnmitm so it won't disconnect (or idk if pokemon has a setting to disable the local multiplayer)

**Comment by davidullo** [comment]
Okay so, I was using SXOS and apparently it didn't let ldnmitm to work properly. I installed atmosphere with ldnmitm and now it works perfectly. Thank you very much for your help, hope this can help other people as well.
