### ISSUE TITLE
[Bug] OBS doesn't work in TCP bridge mode

### ISSUE THREAD

**Issue by flawlessBadger** [exelix11/SysDVR#90]
both RTSP and TCP bridge work just fine when using mpv.
But when I try to use OBS, RTSP mode only passes video w/ no audio and when i try using tcp bridge it does not work at all. 
I can also see in print stats that I am receiving data.
I am running macOS 10.15.7, OBS 26.0.2, SysDVR 4.0.1 and atmosphere 0.14.1

**terminal output when using MPV:**
Connection from 127.0.0.1:60271
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://localhost:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestSetup
RTSP message received Rtsp.Messages.RtspRequestPlay

**terminal output when using OBS:**
Connection from 127.0.0.1:60323
RTSP message received Rtsp.Messages.RtspRequestOptions
RTSP message received Rtsp.Messages.RtspRequestDescribe
Request for rtsp://127.0.0.1:6666/
RTSP message received Rtsp.Messages.RtspRequestSetup

**OBS log**
12:49:36.585: Loaded scenes:
12:49:36.585: - scene 'Scene':
12:49:36.586: ------------------------------------------------
12:49:37.259: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
12:49:37.259: 
12:49:43.092: [Media Source 'Media Source']: settings:
12:49:43.092: 	input:                   
12:49:43.092: 	input_format:            (null)
12:49:43.092: 	speed:                   100
12:49:43.092: 	is_looping:              no
12:49:43.092: 	is_hw_decoding:          no
12:49:43.092: 	is_clear_on_media_end:   yes
12:49:43.092: 	restart_on_activate:     yes
12:49:43.092: 	close_when_inactive:     no
12:49:43.098: User added source 'Media Source' (ffmpeg_source) to scene 'Scene'
12:50:13.444: [Media Source 'Media Source']: settings:
12:50:13.444: 	input:                   rtsp://127.0.0.1:6666/
12:50:13.444: 	input_format:            
12:50:13.444: 	speed:                   100
12:50:13.444: 	is_looping:              no
12:50:13.444: 	is_hw_decoding:          no
12:50:13.444: 	is_clear_on_media_end:   yes
12:50:13.444: 	restart_on_activate:     yes
12:50:13.444: 	close_when_inactive:     no
12:50:13.591: MP: Failed to open media: 'rtsp://127.0.0.1:6666/'
12:50:31.714: Switched to Preview/Program mode
12:50:31.714: ------------------------------------------------
12:50:33.751: Switched to scene 'Scene'
12:50:33.755: Switched to regular Preview mode
12:50:33.755: ------------------------------------------------

**Comment by exelix11** [comment]
Unfortunately i don't have much control on obs' decoders and i don't regulairly use it, last time I tested with probably a version that is outdated by now it worked, guess try with a different version just to be sure that's the problem.
I'd recommend using screen capture with mpv.

**Comment by exelix11** [comment]
While closing old issues i noticed this is related to #60 .
Will keep this open to track reports even though with the [latest release](https://github.com/exelix11/SysDVR/releases/tag/v5.0) with the built-in video player i don't reccomend anymore using directly OBS to receive the video stream.

**Comment by SapphireMH** [comment]
I personally use the SysDVR client and then windowcapture that through OBS, it works flawlessly.

**Comment by ELY3M** [comment]
I have no issues on windows 10.   I am able to stream fine.   I used window capture in OBS Studio.

**Comment by SapphireMH** [comment]
I just noticed this was from November 10th last year...

I feel like you can safely close this @exelix11 @flawlessBadger
