### ISSUE TITLE
Dont know what happen

### ISSUE THREAD

**Issue by javok3000** [exelix11/SysDVR#92]
**Where do you get stuck ?**
After hitting start

**What's the error message you get ?**
Warning, two config dirs found:
   C:\Users\javie\AppData\Roaming/mpv (main)
   C:/Users/javie/OneDrive/Escritorio/Nueva carpeta (bogus)
You should merge or delete the second one.

**Setup information**
 - PC OS: Windows 10 x64
 - Console firmware 10.2.0
 - Custom firmware name and version Atmosphere 0.12.0
 - SysDVR version 4.0.1

The first folder is empty, it doesn't matter where I have the mvp player, every time it shows that warning

**Comment by exelix11** [comment]
> Warning, two config dirs found:
C:\Users\javie\AppData\Roaming/mpv (main)
C:/Users/javie/OneDrive/Escritorio/Nueva carpeta (bogus)
You should merge or delete the second one.

This is a bug in latest builds of mpv but it's just a warning and shouldn't affect video playback, 

No video showing usually means the game is not compatible or some configuration issue, see the [help page](https://github.com/exelix11/SysDVR/wiki/Troubleshooting#streaming-doesnt-work-where-is-the-problem-)

**Comment by exelix11** [comment]
Either way i just released a [new update](https://github.com/exelix11/SysDVR/releases/tag/v5.0) that doesn't require mpv anymore, can you try using that ?

**Comment by javok3000** [comment]
I´m trying with pokemon shield, now i updated to v5.0, when i launch it it doesn´t show anything, either using usb or network conection

**Comment by exelix11** [comment]
Pokemon is known to cause issues with network modes unless you use ldnmitm to prevent it from disconnecting from wifi, as for usb need more info. Follow the steps in the [troubleshooting page](https://github.com/exelix11/SysDVR/wiki/Troubleshooting#streaming-doesnt-work-where-is-the-problem-)

**Comment by javok3000** [comment]
Everytime I launch the client it close itself, i have been trying with out mpv player and it just close, it doesn't matter which option do i chose. USB drivers: WinUSB (v6.1.7600.16385) installer with zadig 2.5, the model on the switch fresh installed. i don't know what I'm doing wrong

**Comment by exelix11** [comment]
What happens if you double click SysDVR-Client.exe (not the gui) ?

**Comment by javok3000** [comment]
It pops an cmd windonw that close instanlly

**Comment by exelix11** [comment]
so with no error ? Interesting.
What happens if you open a cmd and run dotnet --info ?
And what if open a cmd in the sysdvr folder and run dotnet SysDVR-Client.dll  ?

**Comment by javok3000** [comment]
Running dotnet SysDVR-Client.dll in the sysdvr folder

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=win10-x64

Runnign dotnet --info

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by exelix11** [comment]
The error is that your SysDVR-Client version requires .net 3 while you have .net 5, but latest SysDVR-Client requires .net 5.
You have an old version of the client. Download latest release of SysDVR and make sure to update the version on your console too in case you're still running an older version.

**Comment by javok3000** [comment]
Thank you so much, it works perfectly
