### ISSUE TITLE
How to run full screen in built in video player SysDVR 5[Help]

### ISSUE THREAD

**Issue by Mudza09** [exelix11/SysDVR#98]
Run perfectly the built in video player of sysDVR version 5, but is there a way to make full screen like mvp in previous version of sysDVR, I try to maximize the window but there is still present the window bar (not full screen). Any idea how to get this?

**Comment by exelix11** [comment]
That's not implemented yet, may add it for the next update. In the meantime you can use third party apps like borderless-gaming that force other programs to run in full screen.

**Comment by exelix11** [comment]
Added with [latest release](https://github.com/exelix11/SysDVR/releases/latest)

**Comment by coolyzp** [comment]
> Added with [latest release](https://github.com/exelix11/SysDVR/releases/latest)

How to full screen in the latest version?

**Comment by exelix11** [comment]
Press F11

**Comment by coolyzp** [comment]
> Press F11

Thank you
