### ISSUE TITLE
white screen on built in sysdvr player

### ISSUE THREAD

**Issue by zyro670** [exelix11/SysDVR#99]
Hello, running latest release of sysdvr works fine through streaming via Media source on streamlabs OBS, however if I try with the SysDVR client as the player it just stays as a white screen. Not sure what I am missing here to get it to display through the built in client

**Comment by Flyken271** [comment]
Can you elaborate more on what you mean, are you saying that the source in OBS Studio is white and the player is fine or that the built-in player is completely white? is it a full white or more of a grey?

**Comment by zyro670** [comment]
Apologies, the built in player reflects a full white screen. I have the default settings in the switch config and am running the client via TCP

**Comment by Flyken271** [comment]
Could you possibly provide a screenshot of the window please?

**Comment by zyro670** [comment]
![Screenshot 2020-11-22 000506](https://user-images.githubusercontent.com/62817135/99895539-88458880-2c56-11eb-915c-91690ed55020.png)
![Screenshot 2020-11-22 000532](https://user-images.githubusercontent.com/62817135/99895540-8a0f4c00-2c56-11eb-84e0-0d509cd5ec89.png)

**Comment by Flyken271** [comment]
Could you show what the cmd window is showing?

**Comment by Flyken271** [comment]
It's currently late where I am, what I suggest is joining the discord to either seek assistance now or wait here for assistance when exelix can get to this.

**Comment by exelix11** [comment]
I se an error in the cmd, possibly you set the wrong mode on the console so it fails to connect, See the [Tcp bridge guide](https://github.com/exelix11/SysDVR/wiki/Network-TCP-Bridge-mode)

**Comment by zyro670** [comment]
That fixed it! Thank you, i was using the default settings in console config.
